### ISSUE TITLE
Request: Proton Pass

### ISSUE THREAD

**Issue by Dreuzz** [simple-icons/simple-icons#10261]
### Brand Name

Proton Pass

### Website

https://proton.me/pass

### Popularity Metric

The website isnt working for me! (Proton is still very popular and [simpleicons](https://simpleicons.org/) also has other proton logos.

### Official Resources for Icon and Color

svg: https://res.cloudinary.com/dbulfrlrz/image/upload/v1693233221/static/logos/proton-pass-full-logo_tjd3ko.svg

**Comment by PeterShaggyNoble** [comment]
The Similarweb rank wouldn't be relevant here as it would be the rank for Proton as a whole. Is there another metric of popularity, perhaps from #10114, that we could use to assess this one?

**Comment by service-paradis** [comment]
Just compared to some password managers we have is not really convincing:
https://trends.google.com/trends/explore?q=%2Fg%2F11sv_s58h4,%2Fg%2F11ghs9mscc,%2Fg%2F11c71b461w,%2Fm%2F05p5n9w,%2Fm%2F0115pj_z&hl=fr

**Comment by PeterShaggyNoble** [comment]
Closing this as out of scope but we'll be happy to revisit it if Pass gains some traction & popularity.

**Comment by Joelmatho** [comment]
I would love the icon for proton pass and proton auth

**Comment by jficz** [comment]
It's imho hard to fit any privacy-oriented service, product or business into the established popularity metrics (which mostly rely on third-party data) because their target audience is usually privacy-aware and tends to use all kinds of third-party tracker blockers and alternative sources. 

Using Google trends especially feels rather discriminatory as there is a good chance a large portion of the target audience may be actively avoiding Google. Not to mention that Proton itself campaigns massively against Google and other privacy-invasive services.

To point out a possibly relevant metric - there are logos in simple-icons for Proton Drive and Proton Calendar for example, whose apps have about the same download count in Play store (currently showing 500K+). So if both Drive and Calendar are considered eligible, I think Pass should be, too.
