### ISSUE TITLE
Request: FilamentPHP

### ISSUE THREAD

**Issue by Pola5h** [simple-icons/simple-icons#10344]
### Brand Name

FilamentPHP

### Website

https://filamentphp.com/

### Popularity Metric

The filamentphp rank is 127,898 .

![image](https://github.com/simple-icons/simple-icons/assets/81049021/b19cadfb-c3a0-4311-9316-749596e396d7)

### Official Resources for Icon and Color

none

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Pola5h 👍🏻 I'm not sure what we should be adding here for the icon, though. They use just the "fi" for their favicon and, while we generally avoid favicons as sources if that's the _only_ place that particular treatment is used, I think we could make a case here due to how the "i" is styled. So that's our first option, either with our without the background square. The other alternative is the lightbulb that can be seen when you hover over the logo on their website.

The latter would be my preference but what do you think, being more familiar with their brand? If you're not sure yourself and are a member of their Discord or active in their GitHub repo then it might be an idea to ask them directly for their input as to which they'd prefer.

**Comment by service-paradis** [comment]
A SVG that could be used as a a starting point of their favicon is available at https://github.com/filamentphp/filamentphp.com/blob/a71b3d88fd8e4d651d15176815dbd5f4b1f4b7a7/public/favicon/safari-pinned-tab.svg?plain=1#L4 if we decide to go this way.

But they mostly use the full wordmark everywhere ([website](https://filamentphp.com/), [docs](https://filamentphp.com/docs), [Github](https://github.com/filamentphp), [social medias](https://twitter.com/filamentphp), [products](https://shop.filamentphp.com/))

Any news from the community @Pola5h?

**Comment by Pola5h** [comment]
@service-paradis I attempted to contact the community through Discord but have not received any positive response so far.
