### ISSUE TITLE
Request: JetBrains RustRover

### ISSUE THREAD

**Issue by DaRealFrost** [simple-icons/simple-icons#10476]
### Brand Name

RustRover

### Website

https://www.jetbrains.com/rust/

### Popularity Metric

The SimilarWeb Rank is 4,853, visit https://www.similarweb.com/website/jetbrains.com/

### Official Resources for Icon and Color

https://www.jetbrains.com/company/brand/

**Comment by adamrusted** [comment]
Unfortunately, we can't accept the SimilarWeb rank for this - as it's for JetBrains, not specifically RustRover.
Is there another of our [popularity metrics](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity) we can use to gauge whether this is in scope?

**Comment by adamrusted** [comment]
I don't believe RustRover is JetBrains' primary product...

**Comment by DaRealFrost** [comment]
mb I read that wrong

**Comment by DaRealFrost** [comment]
idk if this helps, https://www.google.co.uk/search?q=rust+IDE  but the top result is [RustRover](https://www.jetbrains.com/rust/) as its the olny IDE in its field

**Comment by adamrusted** [comment]
How long has RustRover been a _thing_?
Our [guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity) would suggest that because it's still in preview, then we shouldn't add it. Their blog would back this up, with the announcement of the product only having happened in September 2023.

> ...a brand must be in existence for at least one year (from date of first stable release, where applicable) and meet one of the following metrics of popularity...

A quick glance at Google Trends also suggests this is well out of scope...
![image](https://github.com/simple-icons/simple-icons/assets/1830867/fa128775-2c96-4e0a-91d1-62f76573d698)

Given it's a closed-source project too, we can't use any GitHub or download stats from what I can see.

Therefore, I'm going to have to mark this one as out of scope for now. Feel free to re-open should it qualify under any of our metrics for inclusion.
