### ISSUE TITLE
Question: Icons showing on Website

### ISSUE THREAD

**Issue by moldypenguins** [simple-icons/simple-icons#1067]
I see my issue was closed and an icon was added but do not see it on the website.
How long before it shows?

**Comment by birjolaxew** [comment]
(assuming you're talking about #1064)

Usually this is because the icon hasn't been published yet - we like to group icon releases a bit so that we don't end up with a version `1.9.514` (and because I'm a lazy bastard). It'll usually get published within a day of being merged, although it may be slightly longer if all maintainers are busy IRL.

In this case the Autotask icon was published yesterday (#1066), and should show up on both the website and in the NPM package/on CDNs.
