### ISSUE TITLE
Clarify release notes for version 13

### ISSUE THREAD

**Issue by chris48s** [simple-icons/simple-icons#11412]
### Kind of Issue

Mistake

### Description

The release notes for version 13 at https://github.com/simple-icons/simple-icons/releases/tag/13.0.0 includes a list of removed icons, but it doesn't appear to be complete. For example, the skype icon is no longer in the set, but Skype doesn't appear on the list in https://github.com/simple-icons/simple-icons/releases/tag/13.0.0

I did have a look at https://github.com/simple-icons/simple-icons/pull/10019 which includes a list in the top post, but it looks like the exact icons removed evolved as the review process rumbled on.

Would it be possible to review the release notes in https://github.com/simple-icons/simple-icons/releases/tag/13.0.0 please?

**Comment by uncenter** [comment]
Thanking you for alerting us to this mistake and apologies about the inaccurate release notes! I've just gone through the diff of #10019 and added quite a few additional removals to the release notes. I'm going to tentatively close this for now since I believe the release notes should now be up to date.
