### ISSUE TITLE
README update: Google+ is discontinued, it might no longer make sense to have

### ISSUE THREAD

**Issue by Zarthus** [simple-icons/simple-icons#1173]
The README currently uses `Google+` as example, but it's a discontinued service.

I don't want to be opinionated towards a new icon (if one is desired in the first place), but if you're already using Google it might make sense to use the search engine (unlikely to be discontinued ever)

```js
{ 
  title: 'Google',
  hex: '4285F4',
  source: 'https://developers.google.com/+/branding-guidelines?hl=en',
  svg: '<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Google icon</title><path d="M12.24 10.285V14.4h6.806c-.275 1.765-2.056 5.174-6.806 5.174-4.095 0-7.439-3.389-7.439-7.574s3.345-7.574 7.439-7.574c2.33 0 3.891.989 4.785 1.849l3.254-3.138C18.189 1.186 15.479 0 12.24 0c-6.635 0-12 5.365-12 12s5.365 12 12 12c6.926 0 11.52-4.869 11.52-11.726 0-.788-.085-1.39-.189-1.989H12.24z"/></svg>' 
}
```

**Comment by ericcornelissen** [comment]
I agree that it would be better to not be opinionated towards any particular brand, hence I'd suggest we use the [Simple Icons](https://simpleicons.org/?q=simple%20icons) logo in the example. We can/should upgrade this regardless of whether or not Google+ is being discontinued.

What is your source for `Google+` being discontinued? Because we might also need to remove the icon itself. [This article](https://www.engadget.com/2018/10/08/google-shutting-down-google-plus/) says it is being discontinued as a consumer service, but will remain as an enterprise product.

**Comment by Zarthus** [comment]
Ah yes, you appear to be right. I was unaware there was an enterprise
component to begin with :)

>Active (Scheduled for shutdown for consumers in April 2019)

Absolutely in favour of using the simple icons logo. I will PR that
shortly.
