### ISSUE TITLE
Request: SendGrid

### ISSUE THREAD

**Issue by antoineducrot** [simple-icons/simple-icons#11946]
### Brand Name

SendGrid

### Website

https://sendgrid.com

### Popularity Metric

![Screenshot 2024-10-07 at 10 55 58](https://github.com/user-attachments/assets/8edd8d89-bcd3-403d-b2e5-34a81dc4eeba)

### Official Resources for Icon and Color

none

**Comment by service-paradis** [comment]
Sendgrid was requested a couple of times in the past. It were difficult to add this brand with their previous logo since it was really hard to convert to a monochrome version. It looks like they updated their logo (https://sendgrid.com/en-us/resource/brand).

I you want to give this a try @antoineducrot, you can take a look at our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).
