### ISSUE TITLE
Country Icons

### ISSUE THREAD

**Issue by williamluke4** [simple-icons/simple-icons#1278]

**Comment by ericcornelissen** [comment]
Can you elaborate @williamluke4? It is not really clear what you mean by "country icons" 🤔

**Comment by williamluke4** [comment]
https://www.flaticon.com/packs/countrys-flags

**Comment by ericcornelissen** [comment]
Since we only provide monochromatic icons I don't think we will be able to provide these, many of them will look identical. Also, I think this request is a bit out of scope for Simple Icons. This project's aim is to provide _"SVG icons for popular brands"_ and I won't categorize countries as brands per se.

Thanks for your request anyway, for now I think you're best of using the icons from the list you provided. If there is anything I can help you with let me know! 😄
