### ISSUE TITLE
Icon request: V8

### ISSUE THREAD

**Issue by sh7dm** [simple-icons/simple-icons#1283]
**Name:** V8 JS Engine
**Website:** https://v8.dev/
**Official resources for icon and color:** https://v8.dev/logo (all logos in SVG)

**Comment by sh7dm** [comment]
@davidklebanoff isn't it a `good first issue`? All icons are SVG

**Comment by birjolaxew** [comment]
@sh7dm Right you are - good catch

**Comment by davidklebanoff** [comment]
@sh7dm - I didn't tag this one as a `good first issue` because I foresaw potential difficulties in new users converting this icon to be monochromatic. I haven't looked at the SVG's source so I don't know for sure, but a quick glance at the icon lead me to believe that it may have some overlapping paths that may require some more "advanced" skills such as merging or taken the difference between paths, something perhaps a bit intimidating for a first time contributor.

It's all speculative, but that was my reasoning anyway. :)

**Comment by ericcornelissen** [comment]
The SVG for V8 was added in #1312 and will be available with the next release thanks to @birjolaxew 👌
