### ISSUE TITLE
URL- and code-friendly slugs

### ISSUE THREAD

**Issue by paulmelnikow** [simple-icons/simple-icons#1362]
Hi! Thanks so much for this package. It's been a huge help to be able to use this package in Shields.

### Kind of issue 
  - [x] Improvement
  - [ ] Bug
  - [ ] Other, namely: 

### This issue concerns 
  - [x] The NPM Package
  - [x] The website
  - [ ] Other, namely: 

### Description

It would be helpful to have a canonical slug for each icon that users could see on the website and could be used by consumers of the package to pull the corresponding logo programmatically.

It looks like the package only supports pulling logos by name. The website shows the name, though it exposes the filename when you download the svg, which is basically a slug.

In Shields we accept a logo in the query string and use that to look up the logos by a canonicalized slug. The [current transform code](https://github.com/badges/shields/blob/d1f00b93e8ac2adfcbdb92a8e6286cbdcfd1a194/lib/load-simple-icons.js#L8) looks like this:

```js
Object.keys(simpleIcons).forEach(key => {
  const k = key.toLowerCase().replace(/ /g, '-')
  ...
})
```

This is somewhat brittle. It isn't working well on Let's Encrypt (also Macy's) which use single right quotes rather than apostrophes. (badges/shields#3297)

Presenting a canonical slug on the simple-icons website seems like it would be helpful not only for Shields, but also for other applications which may consume simple-icons.

I'd suggest making the slug the default way to look up the icons, because it encourages people to switch to the slug, which may be a a more stable identifier. (Consider the Let's Encrypt example, which may cause confusion outside of Shields, too.) A `withName()` function could provide the old behavior.

Though that would be a breaking change, and maybe adding a `withSlug()` function would be fine, too.

I'm really curious to hear your thoughts!

**Comment by ericcornelissen** [comment]
Thanks for the suggestion and I think it is very important for us to consider. The most important thing that would prevent us from implementing it directly is backwards comparability, although I feel like we would've seen a report like this earlier if someone actually tried to use e.g. Let's Encrypt with the NPM package (like you said) 🤔 

We need some time to figure out how we can best solve this. What I can say is that it is unlikely it will be a function-like approach. Most likely it will be a change to the key itself, or an additional field on the object associated with the key. The former is more usable but worse for backwards compatibility, the former is good for backwards compatibility.

---

As for the suggestion about the changes to the website, I just want to note that #980 and #989 are two relevant issues.

**Comment by paulmelnikow** [comment]
Hi Eric, as you know Shields users have continued to run into this issue, and it would be really great to have a friendly solution for them (that avoids just supporting many versions of the icon names, which among other things isn't great for caching).

Have you given some thought about what approach you'd like to take here? If so do you think you could lay out the steps that are needed? If you like, possibly I or one of the other Shields maintainers could help with the lifting.

**Comment by ericcornelissen** [comment]
> Have you given some thought about what approach you'd like to take here? If so do you think you could lay out the steps that are needed? If you like, possibly I or one of the other Shields maintainers could help with the lifting.

I'm not quite sure what would be the best approach. I'm thinking of three possible approaches:

- Add a new key to the icon object, e.g. `slugName` (or just `name`? since the existing one is `title`) which would basically be equal to the filename of SVGs (using [this function](https://github.com/simple-icons/simple-icons/blob/7da861312f047a08d68508d5e32a85c00b69c964/scripts/utils.js#L6)).
- A similar approach but instead a method, this allows us to add other variants on the name (e.g. [HTML friendly](https://github.com/simple-icons/simple-icons/blob/7da861312f047a08d68508d5e32a85c00b69c964/scripts/utils.js#L31)) without cluttering the object to much, though I'm not sure if that is really a problem.
- Add a configuration option to simple-icons that changes what you get when you do `icon.title` (probably using a getter on the key).

Either of these approaches would be sufficient for what you need, @paulmelnikow. If you beat me to implementing any of these, go ahead and open a PR and I will have a look 😄 

---

However, there are two related things we need to think about. First, we should look into updating the way one can pick a specific icon using the first method. Without breaking backwards compatibility we can just add a `get` method that accepts a string and returns the icon object (I don't even think we have to deprecate the old approach, we should just encourage the new approach in the documentation). I'd imagine this `get` should work for the "title" of the icons as well as the "slug".

```javascript
const simpleIcons = require('simple-icons');
console.log(simpleIcons['Simple Icons']);

// For Let's encrypt?
console.log(simpleIcons['Let’s Encrypt']);
// Instead
console.log(simpleIcons.get('lets-encrypt'));
```


And second, we should also check how the second method is affected by this, i.e.:

```javascript
const icon = require('simple-icons/icons/simpleicons');
console.log(icon);

// for Let's encrypt
const icon2 = require('simple-icons/icons/lets-encrypt'); // ???
```

**Comment by ericcornelissen** [comment]
Quick update @paulmelnikow, I did some experiments and want to go with either the second or third approach. My reasoning being that it reduces to final file size. Instead of having 500+ slugs added, there is a single function that does the conversion in real-time, I don't think the cost of the conversion is that big, right?

I think the third approach is more elegant, however I can imagine use cases where you want both the nice title and the code friendly slug, so the second approach is probably the way to go.

---

Relatedly, if we decide to do this we might also look into doing a similar thing for the `path` property.

**Comment by ericcornelissen** [comment]
A slug has been added and that should be everything you guys need @paulmelnikow, let us know here if this is sufficient and I will try to release this feature as soon as possible 👍
