### ISSUE TITLE
ManageIQ Logo Request

### ISSUE THREAD

**Issue by europ** [simple-icons/simple-icons#1409]
**Name:** ManageIQ
**GitHub:** @ManageIQ
**Website:** http://manageiq.org/
**Official resources for icon and color:**
1. http://manageiq.org/logo/
2. https://github.com/ManageIQ/manageiq.org/tree/master/site/assets/images/logo

**Comment by ericcornelissen** [comment]
I'm sorry @europ but ManageIQ does not meet our standard [popularity threshold](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) with an [Alexa rank of ~1.5M](https://www.alexa.com/siteinfo/manageiq.org?ver=classic), is there any other indication of the popularity of the service?

**Comment by Fryguy** [comment]
ManageIQ is the downstream of Red Hat CloudForms, which you can find out more information here: https://www.redhat.com/en/technologies/management/cloudforms , so determining popularity is tricky because it's likely split between ManageIQ and CloudForms.

Some other things that might help:

- https://github.com/ManageIQ/manageiq - main repository with 820 GitHub stars, 696 forks.
- https://github.com/ManageIQ - entire org, including repos for a number of plugins

@cybette Do you know if there's any other information that might be helpful here?

**Comment by cybette** [comment]
We get around 200 downloads of the ManageIQ appliances weekly. I'm not sure if that's good enough of an indicator. The social channels are also quite active - [Twitter](https://twitter.com/manageiq), [Youtube](https://www.youtube.com/user/ManageIQVideo), [forum](http://talk.manageiq.org/).
