### ISSUE TITLE
Update Go language icon

### ISSUE THREAD

**Issue by ClydeDz** [simple-icons/simple-icons#1412]
**Name:** Go lang
**Official resources for icon and color:** https://blog.golang.org/go-brand and this [brand book](https://storage.googleapis.com/golang-assets/Go-brand-book-v1.9.5.pdf)

**Comment by birjolaxew** [comment]
There actually was [some discussion on this in the original PR](https://github.com/simple-icons/simple-icons/pull/944#pullrequestreview-149532388). The consensus seemed to be that, since it's been 4 months (at the time, now 1 year) since they published the new design and they haven't really started using it anywhere, we'd stick with the gopher for now and update at a later time when they start using the new design as their actual brand. As far as I can see that hasn't happened yet.

I'm open for discussion on the topic though.

**Comment by SimplyCodin** [comment]
Go now uses the new go logo on thier website so the time to update is now
