### ISSUE TITLE
Dynatrace

### ISSUE THREAD

**Issue by DeadManPoe** [simple-icons/simple-icons#1416]
**Name:** Dynatrace
**Website:** www.dynatrace.com
**Official resources for icon and color:** https://www.dynatrace.com/company/press-kit/

**Comment by hylickipiotr** [comment]
I'll take care of it!

**Comment by hylickipiotr** [comment]
I've almost done, but I have a problem choosing the color. In the logo are five different colors: 
* symbol: `#b4dc00` `#73be28` `#6f2da8` `#1496ff` 
* typography: `#1a1a1a`

I've also checked the Dynatrace website. The primary color of the website is `#0f1419`.

---
I think, better option is to use the color from the website `#0f1419`.

@DeadManPoe @birjolaxew What is your opinion?

**Comment by ericcornelissen** [comment]
This is a difficult one, I'm not sure but I do want to add that given the styling on their website `#6F2DA8` and `#1496FF` are also good options since they're used in the accent gradient, e.g.:

![image](https://user-images.githubusercontent.com/3742559/57999082-c485af00-7adc-11e9-87a3-688d14994a70.png)

**Comment by DeadManPoe** [comment]
I believe the best one is the colored one (green, blue, purple), it's the logo used everywhere except when the background is of a dark color
