### ISSUE TITLE
Icon request: GreenSock

### ISSUE THREAD

**Issue by celyes** [simple-icons/simple-icons#1461]
**Name:** GreenSock
**Website:** https://greensock.com/
**Official resources for icon and color:** https://greensock.com

**Comment by davidklebanoff** [comment]
Alexa Rank: ~53k

**Comment by ericcornelissen** [comment]
For anyone interested in picking this up, the header of their homepage has an SVG of the logo 👍

**Comment by celyes** [comment]
any news about the addition request ?

**Comment by birjolaxew** [comment]
@celyes Looks like nobody has made a PR for this - if you are interested in adding GreenSock to Simple Icons, the easiest way to get that done is to open a PR for it ;)

Our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) should cover everything you need, although they are a bit detailed. In short, you'd want to

1. Open [their official logo SVG](https://greensock.com/wp-content/themes/greensock/images/greensock-logo.svg) in a vector editor (e.g. Inkscape or Illustrator)
2. Delete anything that isn't part of the icon. This would mean the text and the background.
3. Edit the icon so that it's only one color. Delete any shadows and fills until you only have the black outline left.
4. Copy that into a new 24pt x 24pt document, resizing it to fit (so there is no empty space around it). Save that as `greensock.svg` in `icons/`
5. Edit `_data/simple-icons.json` by adding an entry for GreenSock (the color should probably be `#88CE02`).
6. Open a PR so we can merge it in and get it published :)

**Comment by celyes** [comment]
@birjolaxew Thank you so much for your detailed response !

**Comment by foo-dogsquared** [comment]
I made an SVG version of this icon. 
It's ready to be made an addition to the iconset. 

However, the SVG I made is not made to be exact with the logo. 
I removed some details (most notably, the shadows on the body) since it will make it look weird. 

Here's a side-by-side comparison with the original icon and the SVG I made. 

![2019-10-03-13-52-34](https://user-images.githubusercontent.com/34962634/66102590-6cf86380-e5e5-11e9-9804-b5d81c997af4.png)

**Comment by ericcornelissen** [comment]
Looking great @foo-dogsquared, I think you made the right decision with regards to removing shadows from the body, but keeping it on the cape. I think you can go ahead and open a PR. Though I would like to know @birjolaxew and @celyes opinions as well.

**Comment by birjolaxew** [comment]
@ericcornelissen I agree - that monochromization looks good to me. Nice work @foo-dogsquared!

**Comment by celyes** [comment]
@foo-dogsquared  Absolutely brilliant !
