### ISSUE TITLE
Main purpose of this repo?

### ISSUE THREAD

**Issue by greybax** [simple-icons/simple-icons#1512]
### Kind of issue 
  - [ ] Improvement
  - [ ] Bug
  - [x] Other, namely: 

### This issue concerns 
  - [ ] The NPM Package
  - [ ] The website
  - [x] Other, namely: 

### Description
Why all icons have only one color? That's actually not true for most brand icons. 
Would be nice to add some clarifications to Readme. So you'll get more PRs I think because it's not obvious for now why some of the icons do not fit your requirements.

**Comment by ericcornelissen** [comment]
> Why all icons have only one color? That's actually not true for most brand icons.

So, and this does indeed lead to a lot of confusion, the color is supposed to represent the brand rather then the icon itself. Though, admittedly, that is often the same. The reason why it is monochromatic is, I guess, because it started out that way (and updating all existing icons would be quite an undertaking). Relatedly, this has also kind of been discussed in #1060.


> Would be nice to add some clarifications to Readme.

I don't think something like that would hurt.


> So you'll get more PRs I think because it's not obvious for now why some of the icons do not fit your requirements.

Can you elaborate, most icons do fit our requirements. If we deny icons it is typically because the brand is not popular enough (yet). One exception to that I can think of is Sketch (#1141), which is blocked because the brand guidelines explicitly forbid monochromatic use of their icon.

**Comment by ericcornelissen** [comment]
Going to close this for now as it is a bit stale. Feel free to comment/reopen if anyone wants to continue the discussion :slightly_smiling_face:
