### ISSUE TITLE
Resolve non-alphanumeric characters in brand slugs

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons#1531]
### Kind of issue 
  - [ ] Improvement
  - [ ] Bug
  - [x] Other, namely: _future proofing_

### This issue concerns 
  - [x] The NPM Package
  - [ ] The website
  - [ ] Other, namely: 

### Description

> Ye, that definitely should be removed in slugs too. We might want to consider a catch-all stripping of unknown characters (e.g. `.replace(/\W/g, "")`) at the end of our `titleToFilename`.

_Originally posted by @birjolaxew in https://github.com/simple-icons/simple-icons/pull/1519#issuecomment-511227997_

Not sure if it should be all unknown characters (`/\W/g`), all non-ascii characters, or all non-alphanumeric characters. Anyway, the idea arose from removing at least single quotes (`'`) from the filename/brand slug.

For reference, currently this is our algorithm to convert the brand name to the filename/brand slug:

https://github.com/simple-icons/simple-icons/blob/7672bfb2dbd0fa89bfa9d45c1749d288a1c48093/scripts/utils.js#L6-L24

Pinging @birjolaxew, @davidklebanoff, and @paulmelnikow for feedback.

**Comment by paulmelnikow** [comment]
Hi! Thanks for the ping. 😀

This is the formula @RedSparr0w developed in https://github.com/badges/shields/pull/3641#issuecomment-509394351:

> Leave `-`, `.`, `a-z` and `0-9` characters:

Input | Output
:-- | :--
`let’s-encrypt` | `lets-encrypt`
`.NET` | `.net`
`Not a Re@l Service` | `not-a-rel-service`
`Yahoo!` | `yahoo`

It seemed to work for everything except Google and Google+.

I'm curious whether or not that's an improvement over what you're using now. If looks like what you have will change `google+` to `googleplus` which seems better, though I guess moot since #1513 is merged.

Are there any with @ signs in them?

Also pinging @chris48s who, like @RedSparr0w has done a lot of work on the logos in Shields, and may have input.

**Comment by ericcornelissen** [comment]
> Leave -, ., a-z and 0-9 characters:

Leaving dashes (`-`) in seems reasonable to me, unfortunately introducing dots (`.`) is a bit of a problem for us at this point in time (and also, in my opinion, not ideal for filenames).

> I'm curious whether or not that's an improvement over what you're using now. If looks like what you have will change google+ to googleplus which seems better, though I guess moot since #1513 is merged.

I think our approach (replacing e.g. "+" by "plus" and "." by "-dot-") is more robust than simply removing them entirely, avoiding potential name clashes. Then again, we do remove exclamation marks (I believe so far our transformation is based on how you say the brand name, e.g. you say "Google plus" for "Google+" but you don't say "Yahoo exclamation" for "Yahoo!").

> Are there any with @ signs in them?

I believe currently not, but I'm pretty sure we want to remove them as well. I would imagine we want to replace it with "-at-" given my explanation above 🤔

**Comment by paulmelnikow** [comment]
> Leaving dashes (`-`) in seems reasonable to me, unfortunately introducing dots (`.`) is a bit of a problem for us at this point in time (and also, in my opinion, not ideal for filenames).

Makes sense. Dots are less of a problem in a query string, but not great in filenames.

Your solution sounds really good!
