### ISSUE TITLE
Yamaha Motor Corp

### ISSUE THREAD

**Issue by gh0st** [simple-icons/simple-icons#1553]
**Name:** Yamaha Motor Corp
**Website:** https://yamaha-motor.com/
**Official resources for icon and color:**

**Comment by phatbhoy67** [comment]
[Alexa Rank](https://www.alexa.com/siteinfo/yamaha-motor.com): 76,863

[Original .png](https://yamaha-motor.com/application/themes/yamaha_motor/public/assets/images/logo.png) from website
![official logo .png](https://yamaha-motor.com/application/themes/yamaha_motor/public/assets/images/logo.png).

![yamaha-motor-logo](https://user-images.githubusercontent.com/18670428/67703727-d9c80900-f9ab-11e9-981e-606f9dc4cb50.png)


A: is [wikipedia .svg](https://upload.wikimedia.org/wikipedia/commons/d/de/Yamaha_Motor_logo.svg).

B: is isolated from A.

C: [official "common" yamaha logo .svg](https://www.yamaha.com/_common/images/yamaha.svg) version of the motif.

I think C is clearer although not the specific Motor Corp version, what do you think @simple-icons/maintainers?

Brand colour proposed is red from the logo `#E60012`

**Comment by ericcornelissen** [comment]
I would expect **B** given my experience with the brand, where is **C** used in practice (and what does "common" mean in your wording) @phatbhoy67?

**Comment by phatbhoy67** [comment]
Hey @ericcornelissen "common" was in reference to the parent company Yamaha and the tuning fork motif, it's used on (https://www.yamaha.com/en/) where I found the .svg version "C", so not the Motor Corp version.

I've since found this specific reference to the differences between the two versions at the bottom of this [page](https://www.yamaha.com/en/about/history/logo/), B is the correct configuration of the forks (cutting the circle) to use for Yamaha Motor Corp.

Although now having looked at it again, I think I might suggest another version, B1 below:
![yamaha-motor-logo-updated](https://user-images.githubusercontent.com/18670428/67726912-67711c00-f9df-11e9-9f9f-a53dc326c98b.png), let me know what you think.

**Comment by bonez0607** [comment]
@ericcornelissen Ha that's funny - my experience is version "c" because that is the version the music side of the corporation uses. As @phatbhoy67 noted there are two distinct logos and aspects of Yamaha -- Yamaha Motor Co and Yamaha Corps. 

It might be prudent to have them distinctly separate as I can see motor folks needing the motor version (B or B1) and musicians/musical entities needing version c. As such, I'd vote B1 for Yamaha Motor Co and c for Yamaha corp.

**Comment by ericcornelissen** [comment]
Definitely agree with @bonez0607 👍 If you want you can create a Pull Request for both versions @phatbhoy67
