### ISSUE TITLE
Request: NetBeans IDE

### ISSUE THREAD

**Issue by l0c4lh057** [simple-icons/simple-icons#1563]
**Name:** NetBeans
**Website:** https://netbeans.apache.org/
**Official resources for icon and color:**
https://netbeans.apache.org/images/apache-netbeans.svg

**Comment by phatbhoy67** [comment]
Possible options for mono version, "A" is official colour .svg
![netbeans-options](https://user-images.githubusercontent.com/18670428/68088309-dd4d0b80-fe55-11e9-9553-1331e6ba0667.png)

Suggested hex value `#1B6AC6` present in logo and on website.

**Comment by foo-dogsquared** [comment]
I'm conflicted between Option B and C. 
IDK about option D, though. 

How about filling the outer edges of the logo, @phatbhoy67 ?
What does it look like?

**Comment by phatbhoy67** [comment]
Hey @foo-dogsquared, not exactly sure what you mean by filling the outer edges, so I've added a few more configurations:
![netbeans-options1](https://user-images.githubusercontent.com/18670428/68089543-d5936400-fe61-11e9-8c62-5ed3e2561f8a.png)

**Comment by phatbhoy67** [comment]
Few more options........
![apache-netbeans-options2](https://user-images.githubusercontent.com/18670428/68154928-8f610200-ff40-11e9-80a6-7c5aa63a8e59.png)

**Comment by ericcornelissen** [comment]
Making this logo monochrome is quite challenging (and there doesn't seem to be any guidelines for it, except for a version of the logo found in [their YouTube](https://www.youtube.com/user/netbeansvideos) banner, though it is probably outdated?). I think either **B**, **C**, and **I** are good for our purposes.

The versions where some edges are filled and others are not is not particularly recognizable and doesn't really stay true to the original in my opinion. And even though I like **E** and **H** I also think they don't stay true to the original as the different colours of the faces are not represented.

I personally like **I** the best out of these options, because in contrast to **B** and **C** it captures the fact that the inner square has a different colour. Alternatively, we may consider an inverted version of **I** :thinking:

**Comment by phatbhoy67** [comment]
![netbeans-options3](https://user-images.githubusercontent.com/18670428/68171377-63a74180-ff6b-11e9-98fc-db831eb51153.png)

Hey @ericcornelissen, I have added option "Ia" which I think is what you meant as an inverted version of "I".

The original logo, if viewed as an isometric pattern rather than as a different colour cube in the middle, and without colour to work with, I think it is best represented by options (in my preferred order) "J","G","B" or "C". I think "J" best represents the repeating nature of the original design, although this is an interpretation for sure. 🤔

**Comment by birjolaxew** [comment]
[It seems](https://cwiki.apache.org/confluence/display/NETBEANS/NetBeans+Logo) that the logo is intended as a cube, at least judging by [the other logo suggestions](https://cwiki.apache.org/confluence/display/NETBEANS/NetBeans+Logo) from when they updated their logo (or as a tesseract, as suggested by some people on their [mailing list](https://lists.apache.org/thread.html/241eb5e9f304fb6238aabd340f7d9d7b2a4957fdd6fc69d05ecd5453@%3Cdev.netbeans.apache.org%3E)).

I am personally of the opinion that B (perhaps with thicker lines?) is the safer option, for the simple reason that we would not be doing any interpretation of the original logo. If we wish to highlight the cube-within-border of the original logo, I am personally leaning towards I - but that does run the risk of being read more as a hexagon or a hex nut.

**Comment by ericcornelissen** [comment]
> But that does run the risk of being read more as a hexagon or a hex nut.

That is a good point, I did not look at the logo in that way.

In that case I'm in favour of **B** as well.
