### ISSUE TITLE
gentoo

### ISSUE THREAD

**Issue by henning-schild** [simple-icons/simple-icons#1592]
Name: gentoo
Website: https://www.gentoo.org/
Official resources for icon and color: https://wiki.gentoo.org/wiki/Project:Artwork/Artwork

It should probably be one of the "g" logos

https://wiki.gentoo.org/wiki/Project:Artwork/Artwork#Variations_of_the_.22g.22_logo

**Comment by henning-schild** [comment]
Is any information missing here, or why does it seem to be stuck?

**Comment by birjolaxew** [comment]
@henning-schild Mostly because nobody has put in the work needed to complete this issue. If you want to contribute Gentoo to the project, we [have a guide on adding new icons](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) - all contributions are very welcome :)

**Comment by henning-schild** [comment]
thanks! but somehow i can not create badges with it

see https://img.shields.io/badge/test:bla-green.svg?logo=Gentoo
vs https://img.shields.io/badge/test:bla-green.svg?logo=debian

**Comment by birjolaxew** [comment]
@henning-schild It [looks like](https://github.com/badges/shields/blob/2c39ee489a58d4367410d02568f09de8d966c83c/package.json#L62) the Shields.io project haven't updated Simple Icons past `1.16.0` - we are currently on `1.18.0`.

That is a problem with them, though. I suggest you [open an issue in their repo](https://github.com/badges/shields/issues) to make them aware of the problem.
