### ISSUE TITLE
Google Ads (formerly Adwords)

### ISSUE THREAD

**Issue by prionkor** [simple-icons/simple-icons#1676]
**Name:** Google Ads
**Website:** https://ads.google.com

**Comment by el1f** [comment]
Guideline for the logo [here](https://designguidelines.withgoogle.com/ads-branding/google-ads/logos.html#logos-brand-logo-lockups)

**Comment by ericcornelissen** [comment]
> It doesn't seem to explicitly state that the logo shouldn't be made into a monochromatic version but it also completely brushes over the possibility of using it in such a way, also by it being such a color dependant logo it seems hard to pick a "correct" way to convert it into a monochromatic version.

That is correct @el1f, we could decide not to add it based on that but since it is not explicitly forbidden I don't think we have to go that way. If someone can find a suitable monochromatization then I would be fine adding it. If you want you can try a few things and report back here, I would be interested in seeing what you come up with :smile:

**Comment by el1f** [comment]
Will try my hand at it tomorrow morning then! I think the best approach would be to make the right section and the circle solid while keeping the other segment as an empty outlined rectangle.
Also, regarding the color: shouls we just stick with the generic Google blue?

**Comment by ericcornelissen** [comment]
> Will try my hand at it tomorrow morning then! I think the best approach would be to make the right section and the circle solid while keeping the other segment as an empty outlined rectangle.

Keep us updated :+1: 

> Also, regarding the color: shouls we just stick with the generic Google blue?

I think that is fine
