### ISSUE TITLE
Would love a C and C sharp icon

### ISSUE THREAD

**Issue by kchateau** [simple-icons/simple-icons#1693]
**Name:**
**Website:**
**Official resources for icon and color:**

**Comment by nil3sh99** [comment]
Name: C and C++ icon
Official Resource: 
1. C++ - https://www.dropbox.com/s/yyg1hqo4ndbjmlz/C%2B%2B.svg?dl=0
2. C - https://www.dropbox.com/s/pxf4aszkoor5pfn/C-Programming.svg?dl=0

**Comment by ericcornelissen** [comment]
Thanks @nil3sh99, where did you find those?

**Comment by nil3sh99** [comment]
Hey @ericcornelissen , i took a lil help from svg icons and modified them to suit the needs of website.

**Comment by ericcornelissen** [comment]
> i took a lil help from svg icons

I'm sorry but I'm not quite sure what you mean @nil3sh99?

**Comment by el1f** [comment]
The C logo proposed in this issue seems to be an alteration of the the C++ logo endorsed by Standard C++, you can find it being used on the [ISO website for C++](https://isocpp.org/).
It seems like the correct C logo has been already added by @PokiDokika anyways so that's great.
The water's a little muddier with the C# logo. There seems to be no actual official logo for C# as referred in [this stackoverflow question](https://stackoverflow.com/questions/2100109/is-there-an-official-logo-of-c) and this [issue in another repo](https://github.com/exercism/meta/issues/27) which seems to leave us with two possibilities regarding which logo to use: [this one](https://camo.githubusercontent.com/0617f4657fef12e8d16db45b8d73def73144b09f/68747470733a2f2f646576656c6f7065722e6665646f726170726f6a6563742e6f72672f7374617469632f6c6f676f2f6373686172702e706e67), which uses the C++ style and has been featured on seeveral other websites or [this other one](https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/C_Sharp_wordmark.svg/1024px-C_Sharp_wordmark.svg.png) which is being used in Wikipedia.

I am open to vectorizing the one that we decide to end up using.

**Comment by PokiDokika** [comment]
@el1f I submitted a c logo that was based off the c++ logo, but everyone wanted me to remake it in the style of the K&R book. I still have the original if you wish to have it.

**Comment by ericcornelissen** [comment]
@PokiDokika that is correct, the related discussion can be found in that Pull Request for anyone interested. As for the C# logo, you can follow the progress in #1807 @el1f.

All in all, this issues does not need any contributions at the moment (i.e. the C logo has been added and the C# logo has an open Pull Request).

**Comment by el1f** [comment]
I didn't bring my point home in the previous comment. I agree on the decision to use the K&R logo for C and the current version of the C++ logo. My point was mostly about the addition of the C# logo but I didn't realize that there's already an open PR for that. I apologize for the misunderstanding

**Comment by ericcornelissen** [comment]
With #1807 for C# merged now (and #1819 C earlier) I will close this issue 👍
