### ISSUE TITLE
quarkus

### ISSUE THREAD

**Issue by maxandersen** [simple-icons/simple-icons#1748]
**Name:** quarkus
**Website:** https://quarkus.io
**Official resources for icon and color:**
  
https://design.jboss.org/quarkus/

Search for "Icon files - FULL & ONE COLOR" and find various links
like https://design.jboss.org/quarkus/logo/final/PNG/quarkus_icon_1color_32px_reverse.png
for single color icons.

**Comment by maxandersen** [comment]
@ericcornelissen is there anything else I need to do for this to be merged ?

**Comment by ericcornelissen** [comment]
> is there anything else I need to do for this to be merged?

I (nor any of the other maintainers) haven't had time to review your Pull Request yet, if it requires extra work we will ask you about it in the Pull Request itself :wink:

Note that maintaining this project is a purely voluntary effort from our side and we might not be able to review every Pull Request within a day. This is not uncommon for open source projects, you just need to be a bit patient.

The reason I assigned labels etc. is because that takes like two seconds and I can do it easily while I'm waiting for a few minutes. The (potential) reason why other Pull Requests have been merged before yours (even if they where submitted later): we don't have a policy for reviewing Pull Request, whenever we have time we just pick some Pull Request and give it a review :+1: 

I hope you understand :slightly_smiling_face: We are super grateful for your willingness to contribute though!
