### ISSUE TITLE
GitHub Icon, maybe?

### ISSUE THREAD

**Issue by theishaanbedi** [simple-icons/simple-icons#1785]
**Name:**
**Website:**
**Official resources for icon and color:**

**Comment by phatbhoy67** [comment]
Hi @theishaanbedi , the [GitHub icon](https://simpleicons.org/?q=github) has already been added, you can search for icons by name on the website (https://simpleicons.org/).

Have a look at the [contributing.md](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) for steps to follow for requesting an icon and for submitting pull requests. 

Hope that helps 😄 

If you have any other questions I will try and answer then for you here, otherwise I will close this issue as a duplicate icon request.
