### ISSUE TITLE
Shutterstock (stock content provider)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#2157]
**Name:** Shutterstock 
**Website:** https://www.shutterstock.com
**Official resources for icon and color:** https://www.shutterstock.com/press/media 
  

Alexa ranking: [~125](https://www.alexa.com/siteinfo/shutterstock.com)

**Comment by PeterShaggyNoble** [comment]
Although it's not explicitly mentioned on their media page, they use the `o` in a box as their favicon and as their [app icon](https://www.shutterstock.com/explore/customer-mobile-app) so I wonder would we get away with using that instead of the full wordmark.

The colour, extracted from the SVG in the homepage header, should probably be `#ee3625`.

**Comment by PeterShaggyNoble** [comment]
A recreation of the app icon from the page linked above:

![Shutterstock](https://user-images.githubusercontent.com/15157491/77099510-f7a21300-6a0b-11ea-8816-084b32413f74.png)

**Comment by PeterShaggyNoble** [comment]
Looking into it a bit more, they're incredibly inconsistent with the padding of the box and the rounding of its corners throughout their site and apps so maybe the box isn't all that important and we can just go with the `o`.

![Shutterstock](https://user-images.githubusercontent.com/15157491/77151017-041a8000-6a8d-11ea-9287-278e32cb1da6.png)
