### ISSUE TITLE
GNOME

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2160]
**Name:** GNOME
**Website:** https://www.gnome.org/
**Alexa Rank:** [~19k](https://www.alexa.com/siteinfo/gnome.org)
**Colour:** `#4a86cf`
**Official resources for icon and color:** https://wiki.gnome.org/Engagement/BrandGuidelines - logo found in [trademark guidelines](https://www.gnome.org/logo-and-trademarks/) and colour found in [style guide](https://raw.githubusercontent.com/gnome-design-team/gnome-marketing/master/brand/style-guide.png).

Two possibilities here and, while I prefer the first, I fear we may have to go with the second.

[![GNOME](https://user-images.githubusercontent.com/15157491/71085608-d113d800-218f-11ea-9b83-00c7c3808ff2.png)![GNOME](https://user-images.githubusercontent.com/15157491/71085469-84300180-218f-11ea-9f47-d1965c1d8a56.png)](https://github.com/simple-icons/simple-icons/files/3978331/gnome.zip)

**Comment by runxel** [comment]
The [brand guide](https://www.gnome.org/logo-and-trademarks/) states:
- "logo must contain GNOME"
- "logo must be black or white (other colors are not permitted)"

:
- Again, personally I think it's laughable when people have no trust in their brand. But alas, we did it with Cryengine, so we will do it here as well. (However I think its okay to omit the ™️ since it has no meaning anyway)
- That wouldn't be in favor of the proposed blue color (even though I personally find it more suitable).

**Comment by PeterShaggyNoble** [comment]
Thanks for the feedback, @runxel. I wonder by "black" do they mean `#000000` or `#333333`, as found in their style guide? I'll get the PR updated in the morn'.
