### ISSUE TITLE
CD Projekt (game developer company)

### ISSUE THREAD

**Issue by foo-dogsquared** [simple-icons/simple-icons#2181]
**Name:** CD Projekt 
**Website:** https://www.cdprojekt.com/
**Official resources for icon and color:** 

* https://www.cdprojekt.com/en/media/logotypes/ 
* [There is another convenient SVG found in the header](https://www.cdprojekt.com/en/wp-content/themes/cdprojekt/assets/images/CDProjekt-Black.svg) but I think it is more appropriate to get the source in the given media link. 
* Suggested brand color is `#DB0D15` extracted from the SVG. 
  

Alexa ranking: [~292k](https://www.alexa.com/siteinfo/cdprojekt.com)

**Comment by runxel** [comment]
Would you say the bird is enough? Or should it contain the word mark as well? 🤔

**Comment by foo-dogsquared** [comment]
I think it is safe to assume that the bird is enough. 

It is the favicon of the site and it is used as the profile pic by the [official Twitter account of CD Projekt Red](https://twitter.com/CDProjektRED).

**Comment by runxel** [comment]
Asking the @simple-icons/maintainers for help here:
Would you think it's okay to have the bird filled completely or does it need to have the black parts stenciled out?

**Comment by PeterShaggyNoble** [comment]
@runxel, I *would* have said to knockout the black bits but this file begs to differ: https://www.cdprojekt.com/en/wp-content/themes/cdprojekt/assets/favicons/safari-pinned-tab.svg

![](https://www.cdprojekt.com/en/wp-content/themes/cdprojekt/assets/favicons/safari-pinned-tab.svg)

**Comment by PeterShaggyNoble** [comment]
Obviously, this is very rough but it doesn't look great with the black bits knocked out of the red so, in the absence of an official monochrome version, I think the completely filled version could be the lesser of 2 evils.

![](https://user-images.githubusercontent.com/15157491/71971738-24af9980-3203-11ea-9ba8-23eb684996cd.png)

**Comment by phatbhoy67** [comment]
Your red version @PeterShaggyNoble better represents the brand than the totally filled version, it matches their twitter avatar as @foo-dogsquared mentioned above 👇 

![twitter](https://pbs.twimg.com/profile_images/466632606901997568/sq6SsgP9_400x400.jpeg)

and website favicon 👇 
![favicon](https://www.cdprojekt.com/en/wp-content/themes/cdprojekt/assets/favicons/favicon-96x96.png)

The totally filled version doesn't look like the brand logo. 👀

**Comment by runxel** [comment]
I'd be still slightly more in favour for a filled version (since they also use it, see Safari thing above).
But from you it's a tied 1:1 right now.
Let's get another @simple-icons/maintainers weighing in. I will gladly make any version ;)

**Comment by phatbhoy67** [comment]
> I'd be still slightly more in favour for a filled version (since they also use it, see Safari thing above).

The "safari-pinned-tab.svg" has been really helpful in finding versions of logos for use here before.

On other occasions it has thrown up some really poor quality svg as @PeterShaggyNoble mentioned were probably just run through potrace.

On this occasion I don't think it helps, and in my view should probably be a secondary source since there is an actual .svg version of the full logo we can use and make look like the website favicon just by ungrouping it, isolating the red part, unsetting the fill and resizing it.

The Safari version is most likely them following the instructions found here: (https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html)

The other 15 versions of app icon/favicon/ms-tile etc included in the website source or mentioned in the manifest.json all look like the ones I linked above ☝️.

So I'd rescore that 15:1, although I agree we should seek further input from @simple-icons/maintainers 😉

**Comment by foo-dogsquared** [comment]
@phatbhoy67 pretty much nailed my opinion (and I couldn't say it any better). 

That and also because there's an ["official" monochrome version from gog.com](https://menu-static.gog.com/assets/img/cdprojekt-logo.svg). 
(The 'official' in quotes because gog.com is a part of CD Projekt but I don't know where this stands.)

**Comment by runxel** [comment]
Good find, @foo-dogsquared!

So shall it be then! 🧙🏻‍♂️
