### ISSUE TITLE
Spinnaker Icon

### ISSUE THREAD

**Issue by valouille** [simple-icons/simple-icons#2250]
**Name:** Spinnaker
**Website:** https://www.spinnaker.io
**Official resources for icon and color:** https://github.com/spinnaker/spinnaker.github.io/tree/master/assets/images

**Comment by PeterShaggyNoble** [comment]
Alexa rank: [~233k](https://www.alexa.com/siteinfo/spinnaker.io)

**Comment by phatbhoy67** [comment]
Some options: 
![spinnaker](https://user-images.githubusercontent.com/18670428/71773461-69160d80-2f55-11ea-93ca-f5352b08f5e1.png)
D is more evocative of sails in my view, but it is an interpretation, thoughts @simple-icons/maintainers @valouille 🤔

**Comment by valouille** [comment]
Thanks for these ! My preference goes to D as well. 

I would not go for A because with a background we would need to fill the white part with the background colour to keep a monochromatic logo, and that would look like there's a hole in the sails...
C suggests transparency but I'm afraid this logo won't look too good in smaller sizes, and B would look great in small size with a colour background but we less see the sails than with D.

Another option would be to contour the smaller sail to suggest it's over the larger one like they did in [this logo](https://github.com/spinnaker/spinnaker.github.io/blob/master/assets/images/spinnaker-logo-og.png) instead of contouring the smaller one, though I believe your interpretation is more accurate.

**Comment by ericcornelissen** [comment]
I like **D** the most as well, perhaps the dividing line should be a bit bigger for when the icon is displayed at a smaller size?

> Another option would be to contour the smaller sail to suggest it's over the larger one like they did in this logo instead of contouring the smaller one, though I believe your interpretation is more accurate.

That is a good one, can you give a preview for that as well @phatbhoy67?

**Comment by phatbhoy67** [comment]
Suggested option plus a few more possibilities ⛵️ 

![spinnaker-updated](https://user-images.githubusercontent.com/18670428/71783760-4af6ee80-2fe3-11ea-8eca-b4d3cfdbed1b.png)

**Comment by runxel** [comment]
Nicely done! Impressive collection 👍 

Having a quick look at their original svg I would say option `E E`, since the smaller shape sits infront of the other.
The remaining options don`t quite convoy the same feeling. (But `A` is also something I would be okay with)

**Comment by valouille** [comment]
Impressive ! My preference goes to `E E` as well !

**Comment by PeterShaggyNoble** [comment]
There's a problem of perception here; I see the smaller "sail" sitting behind the larger one, so I'd lean towards `DD` or `D`, rather than either of the `E`s. `B` would remove that problem but you'd also lose the meaning & intent behind the icon.

@valouille, would you be willing to reach out to Spinnaker to see if they have a preference or, better yet, have their own monochrome version we could use?

**Comment by runxel** [comment]
@PeterShaggyNoble 
Ha! Your comment looks exactly like the one I wanted to make – until I opened their SVG.
While you're right: the theory of perspective teaches us that smaller shapes must be in the background (because they are further away).
However: if this are really sails of ship, well, then the smaller sails are infront of the bigger sails.
(And again, as mentioned: in _their_ svg the small sail is stacked upon the bigger one)

**Comment by phatbhoy67** [comment]
Avast, me hearties ☠️ ! 

I'm no sailor, but I think the spinnaker is usually attached to the bow, making it the furthest forward. 

![image](https://purelatitude.com/wordpress-cms/wp-content/uploads/2018/07/MD-spinnaker-handling.jpg)

It would make sense if the darker part of the logo is trying to capture the part where the spinnaker and smaller sail silhouette as in the image above, so I think HH is probably closer to the original in spirit 🤔

**Comment by gcomstock** [comment]
![IMG_0320](https://user-images.githubusercontent.com/3046463/72281342-2efcd980-35ef-11ea-94f0-f7f55fb6792d.jpg)
Hey everyone! Sorry for the delay in replying here. I'm the Spinnaker designer over at Netflix. I spoke to the previous designer on the team (and creator of the logo) to see if he had any opinions on what the proper 1-color version of the logo should be, but he feels either of the applications shown in my photo are valid. (basically EE vs A) He does not have either of these files any more. 

I lean towards EE because the simpler line work will probably hold up better when small, but I do hear the argument for the spinnaker sail being in the front.

**Comment by PeterShaggyNoble** [comment]
Thanks for taking the time to reply, @gcomstock, and narrowing the options down.

Of those two, my vote would also go to the mug version, which matches up with @phatbhoy67's option `DD`. To save you the time creating a new version (although it would be handy to have something official to work off), you could instead provide feedback the PR for this, when it gets to that stage.
