### ISSUE TITLE
Parity Substrate (blockchain framework)

### ISSUE THREAD

**Issue by goldsteinsveta** [simple-icons/simple-icons#2253]
Name: Parity Substrate
Website: http://substrate.dev/, https://www.parity.io/substrate/
Icon: ~~https://substrate.dev/img/substrate-icon.svg~~ https://substrate.dev/img/Substrate-logo.svg
Color: #282828, #ff1864

**Comment by PeterShaggyNoble** [comment]
Substrate's Alexa rank is [~719k](https://www.alexa.com/siteinfo/substrate.dev), which would put it [outside the scope of this project](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon). It also only has about [1.8k stars on Github](https://github.com/paritytech/substrate/stargazers). However the parent company's rank is [~140k](https://www.alexa.com/siteinfo/parity.io), which is staying my hand from closing this one outright.

Could you provide a bit more info or maybe some other metric of popularity that might help us determine whether or not we should include this one?

Could you also let us know where you sourced the icon you linked to? I don't see it used anywhere on their homepage nor can I find it in the HTML source. From what I have seen, I would expect their icon to be based on https://substrate.dev/img/Substrate-logo.svg

**Comment by goldsteinsveta** [comment]
Hi, thanks for quick response.

[The icon](https://substrate.dev/img/substrate-icon.svg) is derived from the logo you've linked and was used in other Substrate projects ig https://sub0.parity.io/ Substrate Conference. Current version of the logo is not final, however the given icon will remain a central branding element. It also works better than current logo in the small size.

Substrate is one of the most popular blockchain building frameworks. Currently there're 80 teams building their projects based on it including: https://polkadot.network ([288k](https://www.alexa.com/siteinfo/polkadot.network)), polymath.network ([306k](polymath.network)) and https://chain.link ([109k](https://chain.link)). There are requests to add Substrate icon to simple icons from those teams too, ig https://github.com/paritytech/substrate/issues/4258; this is actually the main reason I submit this request. 

Feel absolutely free to close this one though, I can resubmit later when metrics are fitting the Simple Icons library 🌟

**Comment by PeterShaggyNoble** [comment]
Thanks for the extensive info, @goldsteinsveta. Based on your comments of it being official, I'd agree with the icon you originally suggested as, as you say, it works better at smaller sizes.

I will, however, leave the final decision to this to any one of the other @simple-icons/maintainers who may know more about cryptocurrencies than I, which wouldn't be difficult as my knowledge level is precisely zero! 😆

**Comment by phatbhoy67** [comment]
Thanks @goldsteinsveta  and @PeterShaggyNoble for your work on this issue 👏 .

I think it would be better to add the official icon for now, that is, the icon isolated from the full logo, available to download from (https://www.parity.io/assets/parity-media-kit.zip) `logo-parity-substrate.svg` .

As it stands, this in my view best represents the brand. 

If you look at most of the other icons for the Parity technologies they have a common theme of diagonal lines/boxes, which would be missing if (https://substrate.dev/img/substrate-icon.svg) was used.

I think it would also be helpful @goldsteinsveta to update the title to "Parity Substrate". 

This would make it easier to add other Parity brands/technologies should they be requested.

Based on discussion here (https://github.com/paritytech/substrate/issues/4258) it looks as though the icon will eventually be updated to a version of (https://substrate.dev/img/substrate-icon.svg).

When that happens we can update the version here quite easily.

The colour `#282828` can be found in the full logo available to download from (https://www.parity.io/assets/parity-media-kit.zip) so that gets my vote 👍

**Comment by goldsteinsveta** [comment]
Thank you for suggestions @phatbhoy67! All done, all clear
