### ISSUE TITLE
Semantic Web

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2366]
**Name:** Semantic Web
**Website:** https://www.w3.org/standards/semanticweb/
**Alexa Rank:** n/a (W3C subdirectory)
**Colour:** Not sure. W3C blue? Or one of the colours from the logo itself?
**Official resources for icon and color:** https://www.w3.org/2007/10/sw-logos.html

Cross-posted from [MDI#4510](https://github.com/Templarian/MaterialDesign/issues/4510) on behalf of @ecow.

[![Semantic Web](https://user-images.githubusercontent.com/15157491/72343672-532be980-36c7-11ea-9327-39f06f2756c0.png)](https://github.com/simple-icons/simple-icons/files/4059044/semanticweb.zip)

**Comment by foo-dogsquared** [comment]
All looking good to me, @PeterShaggyNoble. 
As for the color, I'll have an input from another maintainer (@simple-icons/maintainers). 
I agree with the color as it is created by the W3C org, after all. 

Though I have to point out this little detail that may or may not be intentional. 

![2020-01-16-05-42-42](https://user-images.githubusercontent.com/34962634/72474271-6653cc00-3823-11ea-92c2-ffaacafb85f4.png)

It is present in the official vectorized versions (both the SVG and EPS).
