### ISSUE TITLE
Google Translate

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#2390]
**Name:** Google Translate
**Website:** https://translate.google.com/
**Alexa Rank:** n/a (Google subdomain)
**Colour:** `#4285f4`
**Official resources for icon and color:** First option is based on [this SVG](https://upload.wikimedia.org/wikipedia/commons/d/d7/Google_Translate_logo.svg), second is [Google's own icon](https://material.io/resources/icons/?search=g_translate&icon=g_translate&style=baseline) from their Material Icons library.

[![Google Translate](https://user-images.githubusercontent.com/15157491/72619008-406a1c80-3934-11ea-865b-f97f02fb5b16.png)![Google Translate](https://user-images.githubusercontent.com/15157491/72619042-5677dd00-3934-11ea-8f2b-f8c97129965b.png)](https://github.com/simple-icons/simple-icons/files/4077192/googletranslate.zip)

**Comment by ericcornelissen** [comment]
I think we should use the right version because Google provides it for a purpose similar to ours. But I could be persuaded otherwise.

Unfortunate that the [Parter Marketing Hub](https://partnermarketinghub.withgoogle.com/#/brands) doesn't have Google Translate...

**Comment by PeterShaggyNoble** [comment]
We have previously rejected icons from Material Icons in favour of the full logo - ref: #1750 & #1515

**Comment by ericcornelissen** [comment]
> We have previously rejected icons from Material Icons in favour of the full logo - ref: #1750 & #1515

Good point, didn't think about that. It must be said, though, that these two icons are much more alike than those of Google Maps 🤔

**Comment by PeterShaggyNoble** [comment]
Personally, I think we should use the Material versions when they're available. But I also believe we should be consistent so, given that (to the best of my knowledge) we haven't used any of them yet, we should continue using the product logos as a source.

What do the other @simple-icons/maintainers think?

**Comment by phatbhoy67** [comment]
I would lean towards using the brand/product logos where available.

The wikipedia version looks true to the icon as seen on the [Google Translate](https://translate.google.com/intl/en/about/) website, which is also used for their app icon.

From what I understand Material Design adjust icons to fit within their design system, even if MD is related to Google (in this case), it is an official interpretation/simplification of the original, otherwise they would be identical in the first place? 🤔 

In this particular case the Google Translate icon is referred to as an "action" so I guess the intention would be for the Material Design version to be used as/on a button within an app/website to complete the action (translate something) rather than an attempt to represent the brand/product. With all the icons on that app/website looking the same because they follow the Material Design principles..........

Plus, if someone wanted to use the Material Design version of this icon (or any other) there is no reason they can't? 🤔

**Comment by ericcornelissen** [comment]
> In this particular case the Google Translate icon is referred to as an "action" so I guess the intention would be for the Material Design version to be used as/on a button within an app/website to complete the action (translate something) rather than an attempt to represent the brand/product

That is a very good point, from that I say we **should** use the logo version (the left one in the original post) 👍 Thanks for the comment @phatbhoy67!

**Comment by PeterShaggyNoble** [comment]
I was thinking about these over the weekend and came to the realisation that I was coming at them with a bias from being involved with MDI for so long and, looking at them more objectively, I don't think they're suitable for our purposes.

If they were merely simplified so that they worked better at smaller sizes, that would be one thing, but in the majority of cases their core design is also changed to fit [Google's Material guidelines for system icons](https://material.io/design/iconography/system-icons.html). See the aforementioned Google Maps, for example, as well as the difference between our icon for Material Design itself and their version from Material Icons Extended (ref: #1320).
