### ISSUE TITLE
troy credit cart 

### ISSUE THREAD

**Issue by eturerer** [simple-icons/simple-icons#2600]
https://seeklogo.com/vector-logo/355235/troy

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @eturerer.

Troy's Alexa rank is down below 800k, which is beyond our cut-off point of 500k. Assessing the popularity of a brand that only has _national_ significance by its _global_ rank probably isn't all that accurate, though, in my opinion. Having said that, given the fact that they're the only company in Turkey providing the service they do, I would expect that rank to be, at least, a bit closer to 500k.

Or, would I be correct in saying that they provide their services to other financial institutions and, therefore, wouldn't get much traffic through their own site? Much like you would go to your bank's website if you wanted to apply for a Visa card, rather than directly to Visa's?

The other thing that concerns me is that they've only been around since 2015, which doesn't (yet), in the industry they're in, speak to their longevity.

Personally, I'm thinking this is probably going to be out of scope (pending feedback) but I'd like to hear from the other @simple-icons/maintainers before rejecting it.

On an unrelated note, to help you in the future:
- Please stick to our issue template, it reduces our workload a bit.
- Generally, we prefer icons to be sourced from an official source - such as the company itself, its parent company or an affiliated company - or Wikipedia/Wikimedia.

**Comment by ericcornelissen** [comment]
I would like to have some more numbers about how much they're being used, as @PeterShaggyNoble pointed out it is reasonable to assume that the website isn't accessed directly because the cards may be issued by other banks.

However, I wasn't able to find anything like that myself. @eturerer could you provide some more details on the popularity of Troy?

**Comment by PeterShaggyNoble** [comment]
I'm closing this out as out of scope for now as it's been a month without reply.

@eturerer, if you can provide us with some of the information requested, we'll be happy to revisit this.
