### ISSUE TITLE
Most of the Icons cannot be edited/opened in standard SVG-Programs

### ISSUE THREAD

**Issue by nise** [simple-icons/simple-icons#2713]
### Kind of issue 
  - [ ] Improvement
  - [x] Bug
  - [ ] Other, namely:

### This issue concerns 
  - [ ] The NPM Package
  - [ ] The Packagist Package

### Description
Inkscape 0.91 for instance is not capable to open icons of Apache Flink, Apache Spark, R, and so on. The SVG-DOM is valid. The Files are also visible using the major browsers.

**Comment by ericcornelissen** [comment]
@nise we are aware of this problem (see e.g. #2061) and are trying to find a solution that doesn't impact our contributors, Unfortunately haven't been able to do that yet. (we are working to automate the optimization with a CI pipeline)

The problems stems from an [SVGO](https://github.com/svg/svgo) option that is enabled by default and therefore affects SVGs optimized with [SVGOMG](https://jakearchibald.github.io/svgomg/). This is a fairly recent change so older icons (or icons optimized with SVGO instead of SVGOMG) should work just fine in Inkscape.

The reason we haven't, so far, taken drastic measures against this issue is because (we believe) most of our users use the icons in browsers (where they work just fine, as you pointed out).

**Comment by runxel** [comment]
Hey @nise!
Interestingly is Adobe way more brittle here: Please try with Inkscape 0.92. I can't reproduce your problems there. Everything opens gracefully.

**Comment by runxel** [comment]
Closed due to being a duplicate and inactivity.
