### ISSUE TITLE
freedesktop.org

### ISSUE THREAD

**Issue by wolframroesler** [simple-icons/simple-icons#2727]
**Name:** freedesktop.org
**Website:** https://www.freedesktop.org/
**Official resources for icon and color:** https://www.freedesktop.org/wiki/logo.png
  

Needed for the Settings dialog in the KeePassXC password safe (https://github.com/keepassxreboot/keepassxc/pull/4110#issuecomment-593883103).

Big thanks in advance!

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @wolframroesler.

With an Alexa rank of [~2.1m](https://www.alexa.com/siteinfo/freedesktop.org), this is currently [outside the scope](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) of this project. However, Alexa only reports a ranking for the past 2 months, rather than the usual 3, suggesting that this is a relatively new site - is there another metric of popularity we can use to determine whether or not to include this icon?

**Comment by ericcornelissen** [comment]
Interesting @PeterShaggyNoble, you're Alexa rank is for `freedesktop.org`. If you instead look at [the Alexa rank for `www.freedesktop.org`](https://www.alexa.com/siteinfo/www.freedesktop.org) you find its rank is 150k, which is why I :+1:ed.

Apparently subdomains are treated separately by Alexa? :thinking:

**Comment by PeterShaggyNoble** [comment]
> Apparently subdomains are treated separately by Alexa?

:confused: Now that's very weird - this is the only occasion that I've, so far, seen Alexa differentiate a subdomain.

Anyway, whatever the reason, it seems this is indeed within our scope, so.

**Comment by wolframroesler** [comment]
Great work, and super fast as always. Thanks from KeePassXC for your support.
