### ISSUE TITLE
all: add xlink and symbol to allow icons in <use>

### ISSUE THREAD

**Issue by nektro** [simple-icons/simple-icons#2911]
add `xmlns:xlink="http://www.w3.org/1999/xlink"` to the main `<svg>` elements, and encapsulate the `<path>` in `<symbol id="{name}">`

**Comment by ericcornelissen** [comment]
@nektro, I'm not terribly familiar with `<use>` but I played around with it a little bit and found that [this achieves what you want](https://jsfiddle.net/gpyc2a6u/10/) (in FireFox). Simply adding an `id` to our SVGs (in the `<svg>`) should allow you to reference them in other SVGs!

Correct me if I'm wrong, if that is not what you're looking for, or if the browser support isn't all that good with this solution.

Note that my solution still requires _you_ to add an ID to the SVG.

**Comment by PeterShaggyNoble** [comment]
@ericcornelissen, that doesn't work in Chrome and only works if the original SVG is embedded directly in the same file as the `use` element referencing it.

We could probably do with looking into some way to allow people to generate an SVG sprite containing all the icons they want to use, of the form:
```
<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
    <symbol id="icon-1" viewBox="0 0 24 24">
        <path d="...">
    </symbol>
    <symbol id="icon-2" viewBox="0 0 24 24">
        <path d="...">
    </symbol>
    ...
</svg>
```

This would allow the file to be used as either an inline or external sprite.

@nekto, simply wrapping the `path` in each of our files in a `symbol` tag is going to break things for everyone.

**Comment by ericcornelissen** [comment]
> that doesn't work in Chrome

:disappointed: 

> only works if the original SVG is embedded directly in the same file as the use element referencing it.

Isn't that true in any case? Or is your point that the simple-icons `<svg>` needs to be in the document *outside* the other `<svg>`? If so, again in FireFox, it also works if you put the SVG you want to include inside the SVG in which you want to use it (then it also doesn't display twice), see [this example](https://jsfiddle.net/gpyc2a6u/10/).

> We could probably do with looking into some way to allow people to generate an SVG sprite containing all the icons they want to use, of the form:

Not saying we couldn't provide *better* support, but our package already provides `path` value for every icon which can be used for this (see [the docs](https://github.com/simple-icons/simple-icons#node-usage))

**Comment by nektro** [comment]
@PeterShaggyNoble @ericcornelissen's `[id]` fix works for me in both Firefox and Chrome. What versions are you using?

`68.7.0esr (64-bit)` and `79.0.3945.130 (Official Build) (64-bit)` for me.

**Comment by nektro** [comment]
Is adding the `id` attribute like in the codepen something Simple would be open to?

**Comment by ericcornelissen** [comment]
@nektro, unfortunately we prefer not to fill the id-space of every webpage where our icons are used with a bunch of IDs (even if they're _probably_ unique, like `id="simpleicons-{name}"`).

May I ask how you're planning to use the SVGs ([Node package](https://www.npmjs.com/package/simple-icons), [PHP package](https://packagist.org/packages/simple-icons/simple-icons), [JsDeliver](https://www.jsdelivr.com/package/npm/simple-icons), [Unpkg](https://unpkg.com/), [our website](https://simpleicons.org/), other)? That might help us find a suitable solution for you :slightly_smiling_face:

**Comment by nektro** [comment]
Not a problem at all :) I mostly use either Unpkg or directly link from the website and was hoping to do something similar to the below:

```html
<svg xmlns="http://www.w3.org/2000/svg" height="24">
	<use href="https://unpkg.com/simple-icons@latest/icons/discord.svg#icon" fill="#7289DA"></use>
</svg>
```

but I may be able to work around this by setting the background color instead in the meantime.

**Comment by ericcornelissen** [comment]
Hmm, I do agree that styling the SVGs when imported from e.g. Unpkg is a bit cumbersome... Maybe [this solution](https://jsfiddle.net/a3ns1k4t/53/) (based on [this blog post](https://codepen.io/noahblon/post/coloring-svgs-in-css-background-images)) is a nice solution?


> I mostly use [...] directly link from the website 

You mean [simpleicons.org](https://simpleicons.org/)? Just so you know, we don't provide any guarantee's on the "API" of the website. So, in contrast to e.g. Unpkg, it might break from one day to the next. This is also why it isn't documented as a way to use the icons.

**Comment by runxel** [comment]
> You mean [simpleicons.org](https://simpleicons.org/)? Just so you know, we don't provide any guarantee's on the "API" of the website. So, in contrast to e.g. Unpkg, it might break from one day to the next. This is also why it isn't documented as a way to use the icons.

Isn't this even dangerous? SVGs can contain arbitrary code and you certainly don't want to run in this kind of issue! Also this makes your webpage cross-origin.

(Back in my days™ sourcing from other domains was also frowned upon 😂)

**Comment by ericcornelissen** [comment]
> Isn't this even dangerous? SVGs can contain arbitrary code and you certainly don't want to run in this kind of issue! Also this makes your webpage cross-origin.

Arguably, yes, but I think that is besides the point of this conversation and an oversimplification (see below for a "brief" explanation).

In short, CDNs are pretyty common for loading things on the web (also JS),. They're not (very) dangerous to use, and have one big advantage, namely: caching.

<details>
<summary>More info about the security risks</summary>

Loading from a CDN is potentially dangerous as you need to trust the CDN provider and the package provider. If you trust us and our SVGs then you're probably fine, as a CDN being malicious is a sure thing to get them out of business (though, of course, still possible) The only other thing to worry about here is how secure the CDN is. E.g. can someone impersonate them, or break into their systems and insert malicious code?

If you compare that to using a service like NPM or Packagist, there is actually not much of a difference from a security point of view. Again you need to trust the package manager and the package provider. You need the same level of trust in a package manager as you need in a CDN, you need to trust that they give you the real code and that they cannot be impersonated/hacked.

Now, package managers usually do use some integrity checks, but that actually does very little to prevent attacks, unless you verify them manually yourself as well. A reason for why package managers are actually safer is the simple fact that there are fewer connections to the outside world (namely, once to get the code you need; instead of every time the page is loaded).
</details>

**Comment by nektro** [comment]
Back to the original point, I'm going to try the solution proposed by the blog post `ericcornelissen` recommended and will report back.

**Comment by ericcornelissen** [comment]
I'm glad to hear that @nektro, if that changes in the future (or if anyone else has the same problem), be sure to let us know here or in a new issue :slightly_smiling_face:
