### ISSUE TITLE
Add raku icon

### ISSUE THREAD

**Issue by sumanstats** [simple-icons/simple-icons#3055]
The Raku Programming language is a new feature rich expressive language with elegant syntax.

I wanted to include the mascot of the raku programming language while preparing my website with [hugo academic theme](https://themes.gohugo.io/academic/) in skills section. But I could not find it in your collection. So could you add this mascot of raku programming language?

**Name:** Raku
**Website:** https://raku.org/
**Official resources for icon and color:** https://commons.wikimedia.org/wiki/File:Camelia.svg

**Comment by ericcornelissen** [comment]
Hi @sumanstats, thanks for the request. Unfortunately, Raku [does not meet our standard popularity threshold](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon). Is there an alternative measure of popularity we can consider?

**Comment by sumanstats** [comment]
Hi there, 

Alexa ranking shows quite substantial traffic to the central hub of information https://raku.org/

https://www.alexa.com/siteinfo/raku.org

<img width="503" alt="Capture" src="https://user-images.githubusercontent.com/8075886/81561800-7cc5fa80-93b3-11ea-88f3-68e5893663d3.PNG">

If **Raku** fails your threshold, issue can be closed. No worries.

Thank you.

**Comment by ericcornelissen** [comment]
Our minimum requirement is 500k (500,000), so unfortunately Raku fails to meet the threshold.

**Comment by PeterShaggyNoble** [comment]
I looked into this one when we were [trying to figure out which icon to use for Perl](https://github.com/simple-icons/simple-icons/issues/2172) and meant to come back to it.

Given its relationship to Perl, you would think that it should be a shoe-in for inclusion. However, the numbers make it dubious, as it has been around for a good few years. It's low Alexa rank has already mentioned but that could be mitigated by the fact that it was renamed from Perl 6. Except for the fact that was done 6 or 7 months ago and its Alexa rank is on a severe decline when, if they _were_ recovering from the rename, you would expect it to be rising.

Next thing to look at is its popularity and activity on GitHub but [that all looks to be very low](https://github.com/perl6). So, unless there is some _other_ metric we can use to determine its popularity or, for some reason, adoption of Raku and migration from the last version of Perl has been _extremely_ slow and we see an increase in that uptake soon, I'm afraid I agree with, Eric that this is currently beyond our scope.

Which is a shame because it looked like it would be a fun icon to work on and have in our library.
