### ISSUE TITLE
icon-cup

### ISSUE THREAD

**Issue by SunshineSteven** [simple-icons/simple-icons#3125]
**Name:**
**Website:**
**Official resources for icon and color:**

**Comment by ericcornelissen** [comment]
- Hi @SunshineSteven, coul you provide some more information about the brand you want to request, such as a link to the website or an example of the logo?

You can do so either by editing the original post or by commenting in this thread.

**Comment by PeterShaggyNoble** [comment]
I'm _guessing_ this is a request for a generic cup icon rather than a brand, in which case it would be outside the scope of this project. If I'm wrong, please feel free to reopen this with the details requested by Eric.

For generic icons, I highly recommend [Material Design Icons](https://materialdesignicons.com/).
