### ISSUE TITLE
Request: Bazaar

### ISSUE THREAD

**Issue by gizmecano** [simple-icons/simple-icons#3149]
**Name:** Bazaar

**Website:** [Bazaar](https://bazaar.canonical.com/en/)

**Alexa rank**: circa [150'000](https://www.alexa.com/siteinfo/canonical.com) (note that this rank is for [Canonical](https://canonical.com/) main website as Alexa doesn't seem to consider subddomain)

**Official resources for icon and color:**

1. logotype is available in [`SVG`](http://wiki.bazaar.canonical.com/LogoOptions) format
2. by examining the `SVG` file, a suitable color may probably to be set between the two colors delimiting the gradient: `#fdf189` and `#f1d704`

I know that almost everyone mainly uses Git today, but it can still be useful to have logos for more version control systems (such as **Bazaar**). As the Alexa rank cannot be clearly specified, I let you judge the (even former) popularity of such a tool.

**Comment by ericcornelissen** [comment]
You are right that the Alexa ranking doesn't help in this case as it's just the popularity of the Canonical website :disappointed: I wish there was some other popularity metric that we could employ here...

 Unfortunately, judging from the website and [Wikipedia page](https://en.wikipedia.org/wiki/GNU_Bazaar) the project hasn't been updated since 2015 and is still written in Python 2 (which is no longer being officially since recently, if I'm not mistaken). This makes me believe **Bazaar** isn't "popular" enough by our metric (in this case mainly meaning that there is a good chance we will need to delete it sometimes soon).

Any opinions from others (@simple-icons/maintainers)?

**Comment by gizmecano** [comment]
> Unfortunately, judging [...] the project hasn't been updated since 2015 [...] This makes me believe **Bazaar** isn't "popular" enough by our metric (in this case mainly meaning that there is a good chance we will need to delete it sometimes soon).

I fully understand this point of view (I also expressed my own observations within my initial message).

Nevertheless, I think that adding such icons concerning abandoned (or about to be abandoned) brands or products can be interesting, or even useful in some cases: specific projects may want to refer to such tools (eg. to illustrate a history, a changelog, etc.). Adding such files could therefore allow to constitute a kind of valuable graphical legacy for various purposes...

You will also note that this version control system (although it is now quite inactive and probably less and less used) was one of the backbones of a site like Launchpad (whose icon is present within the project since 2015: cf. #128 and d90e3a973e7aa627b1c4c1ce6d04f19b9e527568).

I hope these elements will contribute to discuss about these kinds of requests regarding brands or products which can be rightly considered as "less popular"...

**Comment by runxel** [comment]
Hey @gizmecano!
Thank you for this request. While you're certainly right in that there might be demand for this type of icons (I wouldn't argue against that), it doesn't quite fit with what we aim for. It's true, our name is not _popular brands icons_, but as a description it's right there the first sentence in the readme 😅
To stay consistent, I would not include "Bazaar".
Have a great day!

**Comment by PeterShaggyNoble** [comment]
Hmm ... tricky one 🤔 I wouldn't be _too_ concerned that development seems to have stagnated on this and less so that it use Python 2 - I'm sure we're going to see plenty of existing systems still running on it for a while to come - if enough people are still using Bazaar to make it popular eough, it would be within our scope. So we'd need to find _some_ sort of usage stats or other indication of its popularity. Unfortunately, [its Launchpad repo](https://launchpad.net/bzr) doesn't give us any of the usual metrics we use to judge a repo's popularity. So, in the absence of anything else to go on, I'm afraid I agree with @ericcornelissen & @runxel that this is out of scope for us.

However, as It's a simple enough icon, I threw this together for you to use; click to download it. Note that, as it was quite rushed and hasn't been through our review processes, it probably won't be up to our usual standards.

[![GNU Bazaar](https://user-images.githubusercontent.com/15157491/83511754-11111200-a4c7-11ea-9353-6c873742ba05.png)](https://github.com/simple-icons/simple-icons/files/4716609/gnubazaar.zip)

**Comment by gizmecano** [comment]
I fully understand that it was necessary to define a borderline, but the rank is only indicators of a supposed popularity. It isn't because I use Git frequently that I regularly visit the devoted website. Furthermore, metrics fluctuates over time: the oldest internet users know that a quarter of a century ago, the most popular search engine was [Alta Vista](https://en.wikipedia.org/wiki/AltaVista)... 😉

Keeping track (perhaps in another repository) of a some brands or products that are now abandoned (but which have been "popular" before) _or_ that have changed their emblematics, seemed to me an idea that could be helpful, but I fully understand that such a huge scope redrafting could add major constraints for a project of this size.

Thank to @PeterShaggyNoble for taking the time to design an icon anyway: this could be useful for those who would want to illustrate this software without having to open a new issue about this subject.

And thank you to @ericcornelissen and @runxel for fruitful discussion.

**Comment by gizmecano** [comment]
> That is a very interesting point given, for example, the somewhat recent addition of Windows XP (#2653)

Indeed, It is a very good example: this product has been effectively "popular" in the past, but it is no longer up-to-date.

> I do indeed think that right now this is outside our capabilities. 

Of course, I fully understand this point.

> I love the idea (...) (and I would suggest moving things like the Windows XP icon there)

I'm going to think about various possibilities for considering past or outdated brands and will open a dedicated issue when I will get adequate propositions to do.
