### ISSUE TITLE
Page too large to display Twitter Card

### ISSUE THREAD

**Issue by gizmecano** [simple-icons/simple-icons#3197]
### Kind of issue

  - [x] Improvement
  - [ ] Bug
  - [ ] Other, namely:

### Description

If you add a link to the site into a tweet (as I did [this morning](https://twitter.com/gizmecano/status/1270612947702865920)), you will see that the Twitter card is not displayed.

The problem is due to the size of the page, which is too large to be fully handle. The 
[Card validator](https://cards-dev.twitter.com/validator) reports:

`ERROR: Fetching the page failed because the response is too large.`

A similar issue seems to have been resolved by [adding a dedicated sniffer](https://twittercommunity.com/t/error-fetching-the-page-failed-because-the-response-is-too-large-when-i-try-to-validate-a-url/132274/3) to read only the `<head>` of the page.

**Comment by ericcornelissen** [comment]
Liquid is just a preprocessor, it's not a server. Jekyll is the "server" component but it's meant to just serve static files (and an RSS feed) as far as I know. In any case, through GitHub pages you have no control over the server.


> The problem was the amount of inline svg, so i added a Twitterbot sniffer and told it to only sniff the head. This resolved the error.

[This](https://twittercommunity.com/t/error-fetching-the-page-failed-because-the-response-is-too-large-when-i-try-to-validate-a-url/132274/5) sounds to me like a different solution, but I'm not sure how exactly they achieved it 🤔

**Comment by PeterShaggyNoble** [comment]
#2384 could possibly resolve this, depending on how it's implemented.

**Comment by PeterShaggyNoble** [comment]
Given that this will be resolved by other work we'll be undertaking on the website, I'm going to close this issue out.
