### ISSUE TITLE
mastercomfig

### ISSUE THREAD

**Issue by micwoj92** [simple-icons/simple-icons#3199]
**Name:** mastercomfig
**Website:** https://mastercomfig.com/
**Official resources for icon and color:**
 https://mastercomfig.com/favicon.png
svg version https://gist.github.com/micwoj92/1f8b84da5df616fe75aeb23bb1c90086

**Comment by NovaGL** [comment]
I noticed that SVG is on your repo. Can you advise the original source or did you convert it yourself?

Since you have done most of the work would you consider adding the logo yourself?

Follow the below steps for how to do it.
[Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)

**Comment by micwoj92** [comment]
SVG was just added to official repo 
https://github.com/mastercomfig/mastercomfig.github.io/blob/master/img/mastercomfig_logo.svg
I didnt make the logo, one of community members made it, but he has no github account. I have no experience with svgs.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request and the clarification, @micwoj92.

Unfortunately, as it stands, with an Alexa rank of [~869k](https://www.alexa.com/siteinfo/mastercomfig.com) this would currently be beyond our scope as our cut-off for that metric is 500k. We also use GitHub stars as an alternative metric but, with just 292, that's also below our cut-off of 5k. I suspect, though, that that last one in particular may not be an accurate measure of popularity for this brand so, to help us decide whether or not we can add it, do you have any suggestions for an alternative metric we can use to gauge their popularity?

If we do add this then they also offer an option without the background, which is what I think we should go with: https://raw.githubusercontent.com/mastercomfig/mastercomfig.github.io/master/img/mastercomfig_logo_transparent_i.svg

As for the colour: being more familiar with the brand, would you agree that `#209688` from the SVG you linked above is the correct choice for us?

**Comment by micwoj92** [comment]
I contacted the creator, I hope she will answer here + this way we will have an official statement from owner which should resolve all ambiguities.

**Comment by PeterShaggyNoble** [comment]
Thanks, @micwoj92

However, the first things we need to address is my second paragraph above: assessing the popularity of this brand and its suitability for inclusion in our library.

**Comment by micwoj92** [comment]
So what I have thought of are github downloads 
https://somsubhra.com/github-release-stats/?username=mastercomfig&repository=mastercomfig
But the problem is that the website is caching files using Cloudflare.
https://github.com/mastercomfig/mastercomfig.github.io/blob/master/js/mastercomfig-cf-worker.js
So it also isn't 100% accurate, but it is up to you to decide if that is popular enough.

**Comment by PeterShaggyNoble** [comment]
OK, so it wasn't clear whether the total at the top of the page was _just_ for those releases listed on the page, dating back to 2019-11-20, which would be impressive, or for _all_ releases on GitHub, dating back to 2016-12-16, which would be less impressive. So I checked! And they have indeed had ~760k downloads since November last year. _And_ you say that number should actually be higher because of some issue with caching?

Based on those numbers, I'm now leaning slightly more in favour of this being within scope but, as this is a new measurement of popularity, I'd like to hear what the other @simple-icons/maintainers think too.

**Comment by micwoj92** [comment]
So when it is downloaded via github, the tracker can count it. 
Download page https://mastercomfig.com/download doesnt use github api anymore and on top of that it  caches the files for 12 hours. It was made to make the site faster. So the github download tracker can't directly track the downloads there.

**Comment by PeterShaggyNoble** [comment]
Do you know, by chance, what the primary source of their downloads is, @micwoj92? If it's at least roughly equal between their website and GitHub, with at least as many downloads between the two then that would definitely make a better case for its inclusion.

**Comment by micwoj92** [comment]
I only know that the caching was added to website  around 10 days ago. Not sure how the downloads were handled before. The owner is the only one who could provide more insight in this information.

**Comment by mastercoms** [comment]
Hello, I am said owner/maintainer of mastercomfig!

To clarify, I am not aware of caching affecting GitHub release stats. The file downloads themselves should be directly served by GitHub, even when using the website. Cached API access is just done to check the version.

That being said, it seems like this stats site only lists the last 30 versions (which is the default pagination for the GitHub API). mastercomfig has had GitHub release downloads since December 2017, so I ran my own Python script to count the downloads:

```py
total_downloads = 0

for release in g.get_repo("mastercomfig/mastercomfig").get_releases():
    for asset in release.get_assets():
        total_downloads += asset.download_count

print(total_downloads)
```

Which comes up with 1,793,284 total downloads since December 6, 2017 (version 6.0.0). Unfortunately, before that point, the installation method was downloading the repo/cloning and as far as I am aware, there are no metrics available for that.

**Comment by PeterShaggyNoble** [comment]
Thanks for the additional information, @mastercoms and for taking the time to post, much appreciated. After some internal discussion on the using downloads as a metric of popularity, we've decided to add this one :+1:

@mastercoms, do you agree with the choices of icon and colour I made in [this comment](https://github.com/simple-icons/simple-icons/issues/3199#issuecomment-642562114).

**Comment by mastercoms** [comment]
Yes that icon and color seems appropriate. Thank you for your consideration!

**Comment by PeterShaggyNoble** [comment]
Thank _you_ for taking the time to provide feedback, @mastercoms 👍

@micwoj92, would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this one a try yourself?

**Comment by micwoj92** [comment]
Yes sure, but now I have 2 closing weeks of school, being busy this is low priority for me. Same goes for #3187 . I will definitely end this and the tftv before end of week 27

**Comment by PeterShaggyNoble** [comment]
No problem, @micwoj92 and, certainly no rush 🙂

Seeing as you've already put a good bit of work into reaching out to the community and maintainers of both brands, I'm going to assign both issues to you for now so, if you find that you can't take them on yourself, please let us know either if we can help you or if you'd like us to reassign them.

**Comment by PeterShaggyNoble** [comment]
Are you still planning to work on this one, @micwoj92?

**Comment by micwoj92** [comment]
Yes, but I was just waiting first till 3271gets merged or rejected

**Comment by fbernhart** [comment]
@micwoj92 Would you mind if I create a PR for this issue or do you still want to work on this one yourself?

By the way: The Alexa rank increased to [469,689](https://www.alexa.com/siteinfo/mastercomfig.com) over the last couple of months. 👍🏼

**Comment by micwoj92** [comment]
> @micwoj92 Would you mind if I create a PR for this issue or do you still want to work on this one yourself?
> 
> By the way: The Alexa rank increased to [469,689](https://www.alexa.com/siteinfo/mastercomfig.com) over the last couple of months. 👍🏼

Sure you can. The logo colour was only changed from `#209688` to `#009688`

https://github.com/mastercomfig/mastercomfig.github.io/commit/f1278482676ca6c5faa1242ce3552124acbe4a5b#diff-edf688585dc953bd95c9cae218bcc8530975dcb7f4d3668ddb4a73a1ec0e7190
