### ISSUE TITLE
Redefine issue templates

### ISSUE THREAD

**Issue by NovaGL** [simple-icons/simple-icons#3205]
Currently there is only the following issue templates.

- Icon request
- Icon update
- Packages
- Website

If someone asks a question that doesn't fit in the a valid category they will most likely choose an incorrect one.

There is no template for documentation, or general\ misc ideas.
More issue types should be included to avoid blank issues or the incorrect type being selected.

**Comment by PeterShaggyNoble** [comment]
I think, as you mentioned in #3200, a new issue template that covers documentation could be a good idea. Although, I would suggest that rather than it _just_ being for documentation, that it be for the more generic "meta" label, which I see docs as a sub-category of, allowing it to cover all aspects of the Simple Icons project. We could have documentation as one of the checkboxes within the template and a member of the @simple-icons/maintainers can easily change the labels if that is checked.

Beyond that, though, I don't know that we should add any more as we don't want to overwhelm people with choices, especially people that are submitting their first issue. Personally, I'm OK with people opening a blank issue for anything that isn't covered by the available templates - I actually wish GitHub would make that option more prominent on that screen.

**Comment by ericcornelissen** [comment]
> I think, as you mentioned in #3200, a new issue template that covers documentation could be a good idea. Although, I would suggest that rather than it just being for documentation, that it be for the more generic "meta" label, which I see docs as a sub-category of, allowing it to cover all aspects of the Simple Icons project. We could have documentation as one of the checkboxes within the template and a member of the @simple-icons/maintainers can easily change the labels if that is checked.

If we are going to add that I would prefer either adding both `docs`  and `meta`, or just `docs`. In some sense `meta` is a superset of `docs` (I view `meta` primarily as things concerning e.g. config files and linting) but since we have a dedicated `docs` label I would prefer to not use `meta` as well for all `docs` issues. The reason I prefer a template for `docs` is because it is clearer what it means, `meta` is quite abstract and to the best of my knowledge not very common in open source projects.

Also, yes, we can manually edit the labels, but if we are going to add extra templates anyway I would prefer to avoid having to do it manually.

> Beyond that, though, I don't know that we should add any more as we don't want to overwhelm people with choices, especially people that are submitting their first issue. Personally, I'm OK with people opening a blank issue for anything that isn't covered by the available templates - I actually wish GitHub would make that option more prominent on that screen.

I agree with this as well and it's the reason why I didn't add any more templates in the first place (and yes, GitHub should consider making that more prominent). We could also just add a blank template ourselves 🙃

**Comment by PeterShaggyNoble** [comment]
> The reason I prefer a template for docs is because it is clearer what it means, meta is quite abstract and to the best of my knowledge not very common in open source projects.

Good points :+1: I agree with that approach, so.

@NovaGL, would you like to work something up for this and submit a PR for further discussion?
