### ISSUE TITLE
Request: FreeNAS / TrueNAS

### ISSUE THREAD

**Issue by CoreyVidal** [simple-icons/simple-icons#3255]
**Name:** FreeNAS / TrueNAS
**Website:** freenas.org / ixsystems.com
**Alexa rank:** 81,462 / 32,613

**Official resources for icon and color:**
  https://www.ixsystems.com/blog/new-new-truenas-logo-unveiled/

**Comment by CoreyVidal** [comment]
I originally came here only to request an icon for FreeNAS (which is a single-colour shark logo). But while searching for resources, I've discovered that it's about to be renamed TrueNAS, and they just recently released their new logos.

FreeNAS is free and open-source NAS (network-attached storage) operating system: https://en.wikipedia.org/wiki/FreeNAS

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @CoreyVidal 

First of all, to summarise everything that was mentioned here and in the linked blog entry (it was a bit confusing on the first read-through!), as much for reference by anyone requesting any of the other logos in the future. The only point below that are really relevant to this issue are 2, 3 & 7 but please correct me if I'm wrong on any of it.

1. There's a company called iXsystems.
2. They have a product called FreeNAS which uses [this logo](https://www.freenas.org/wp-content/uploads/logo_flat_V2.png).
3. They are currently in the process of rebranding that product as "TrueNAS CORE", which will use the second logo in [this image](https://static.ixsystems.co/uploads/2020/06/Stacked_Primary_TrueNAS_Logos.png).
4. They have another product, currently called TrueNAS, which, as part of the rebranding, is being renamed as "TrueNAS Enterprise" and will use the third logo in [this image].(https://static.ixsystems.co/uploads/2020/06/Stacked_Primary_TrueNAS_Logos.png).
5. Both products are being bundled together as a suite to be called "TrueNAS Open Storage", which will use the first logo in [this image](https://static.ixsystems.co/uploads/2020/06/Stacked_Primary_TrueNAS_Logos.png).
6. There's an third product in development called "TrueNAS SCALE", which will use the last logo in that image.
7. This issue is a request for FreeNAS (soon to be TrueNAS Core) only.

Assuming point 7 to be correct then there are 2 possible approaches we can take, depending on the timescale of the rebranding.
1. If it's still a good few months out then we add the current shark logo as FreeNAS now and update to the new logo and name when the rebrand is complete.
2. Or we hold off for now and wait for them to complete the rebrand before adding it (although, if someone wants to open a PR now ,we can slap the "pending" label on it)

The next thing to clear up is the naming, do we go with:
1. TrueNAS Open Storage, the parent suite that shares a logo with,
2. TrueNAS Core, the new name for FreeNAS, which is what's being requested here, or,
3. simply TrueNAS?

**Comment by NovaGL** [comment]
I think we should add the FreeNAS logo for Legacy purposes. Not everyone will update their box quickly and they might like to reference that logo. We should just add the one TrueNAS logo and then people can raise issues or pull releases if they would like the other logos.

**Comment by PeterShaggyNoble** [comment]
You raise a good point, there, @NovaGL - the rebranding isn't going to immediately render existing FreeNAS products obsolete and (in a UI, for example) it could be confusing to use the new icon to represent them, especially for people with products from both before and _after_ the rebrand.

My suggestion would then, therefore, be to add the current FreeNAS logo as well as TrueNAS one and remove the FreeNAS one (much) further down the road.

**Comment by CoreyVidal** [comment]
Hi, just following up on this.

**Comment by adamrusted** [comment]
Icons were added in #4573 and #4574 - closing this issue.
