### ISSUE TITLE
Rakuten

### ISSUE THREAD

**Issue by thefatguide** [simple-icons/simple-icons#3294]
**Name:** Rakuten
**Website:** rakuten.co.jp
**Alexa rank:** 93
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @fatclick :+1:

I think we're OK to go with just the underlined "R" here, rather than the full wordmark. The "Club R Everywhere" image on [this page](https://www.rakuten.co.uk/toolbar-plugin) includes a vector version of it.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?

**Suggested colour:** `#bf0000`, from UK website logo
