### ISSUE TITLE
Add Wasi (web assembly system interface) logo

### ISSUE THREAD

**Issue by softprops** [simple-icons/simple-icons#3299]
**Name:**

Wasi

**Website:**

https://wasi.dev/

**Alexa rank:**
  

2,761,202

**Official resources for icon and color:**
  
  
https://github.com/bytecodealliance/wasi.dev/blob/gh-pages/polyfill/WASI-small.png

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @softprops :+1:

However, on the 2 metrics I can see, this is currently out of scope for us; we have a cut-off of 500k for Alexa ranks and 5k for GitHub stars. Is there another metric we could use to ascertain the popularity of this one and its suitability for inclusion in our library?

**Comment by softprops** [comment]
There bet this project is placing is that webassembly (already important enough to be covered by simple icons) will as valuable outside of the browser as it is inside the browser. The Alexa rank is a likely indicator of a typical [technology adoption curve](https://en.m.wikipedia.org/wiki/Technology_adoption_life_cycle).

Here's a quote from the creator of Docker as an indicator of relevance

> If WASM+WASI existed in 2008, we wouldn't have needed to created Docker. That's how important it is. Webassembly on the server is the future of computing. A standardized system interface was the missing link. Let's hope WASI is up to the task!

[Ref](https://twitter.com/solomonstre/status/1111004913222324225?s=19)

**Comment by ericcornelissen** [comment]
I think it is unlikely that this project will ever have an Alexa ranking that is high enough to be considered for inclusion, so that won't be our reason for dismissing this request.

From my point of view, as it stands now, it is difficult for us to accept this request for the simple reason that, in addition to not showing any signs of significant popularity (we provide _SVG icons for popular brands_ after all), the project seems still very young and it is not clear whether it will succeed at the goal it set out for itself. As you and the creator of Docker say: "it's a bet [...]" and "let's hope WASI is up to the task."

In other words, it seems WASI is not popular enough nor does it show significant signs of longevity (yet).

As much as I personally also hope that WASI succeeds, the simple icons project aims to provide icons of "popular" (which is of course a fuzzy word) brands or brand-like things. We simply don't have the capacity nor the goal to add, review, and maintain SVG versions of the logos of every new project that has huge potential, but may also stop in a year or two.

Based on this I think this issue can be closed, for now, unless @softprops or someone else can provide us with altnerative indicators of popularity and/or longevity. And, as always, we are happy to add the logo once the project popularity has increased.
