### ISSUE TITLE
Create some icons for cyber security related like metasploit framework logo,and etc.. i have many ideas if you really want then I'll help you 

### ISSUE THREAD

**Issue by Z4nzu** [simple-icons/simple-icons#3333]
**Name:** Mr.Z4nzu
**Website:** GitHub.com/Z4nzu
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by ericcornelissen** [comment]
Hi @Z4nzu, thanks for your request. It would help us if you could open an issue for each icon you're interested in, and please take the time to try and find brand guidelines or vector version of the logo as well. Also, the issue template is designed to be filled out with the details of the brand, rather than your own details. Thanks :slightly_smiling_face:
