### ISSUE TITLE
Replace Alexa rank with SimilarWeb Global rank or Traffic Overview

### ISSUE THREAD

**Issue by AryanBeezadhur** [simple-icons/simple-icons#3338]
**I find the Alexa rank confusing since the statistics and rank are hard to spot and very badly laid out.**

**Let's look at the [Alexa ranking for github.com](https://www.alexa.com/siteinfo/github.com). Can you find the traffic or ranking anywhere? No? Neither can I :(**

![image](https://user-images.githubusercontent.com/34424160/87829672-69358500-c877-11ea-84f8-dfd5bab63991.png)

**Now let's look at the [SimilarWeb global rank for github.com](https://www.similarweb.com/website/github.com/). Can you spot all three ranks? Of course you can! It's even above the fold.**

![image](https://user-images.githubusercontent.com/34424160/87829634-5458f180-c877-11ea-839d-e80329cba49e.png)

**We can even judge the site by [traffic overview](https://www.similarweb.com/website/github.com/#overview) instead, saying that for a site's logo to be submitted as an Icon Request, it needs at least 5k monthly visits, for example since SimilarWeb provides this data.**

![image](https://user-images.githubusercontent.com/34424160/87829792-a437b880-c877-11ea-8df8-d5def37e8b62.png)

**SimilarWeb provides much more detailed and well-laid out ranking information than Alexa, and is a better site to help us judge if a website is popular enough for the logo to be added as a new icon to Simple Icons.**

**Comment by NovaGL** [comment]
Thanks for this @AryanBeezadhur 

Can I suggest you make a pull request of how you would change the documentation and we can discuss it further?
If you don't feel comfortable, we can get input from some of the other maintainers for feedback.

**Comment by ericcornelissen** [comment]
That's an interesting proposal @AryanBeezadhur, the results page from Alexa have ~recently changed and I agree that it's not for the better (at least for our purposes).

I'd definitely be interested in giving it a try. However, we will need to asses if it is "good enough" for our purposes. From some trying I have a couple of findings:

- The ranking seems to be slightly different, this is not necessarily a problem, just something to keep in mind
- It seems to be unable to find some icons that Alexa ranks at 500 or higher
- One drawback from my point of view is that it is unable to find a website if you include `https://` in the search, which is a bit annoying when I copy the URL from my browsers URL bar.
- In my opinion they're a bit too afraid of bots. After trying just 4 websites I already got a CAPTCHA to verify I'm not a bot. Granted this is not a problem for contributor, but as a maintainer it's quite common to check several domains in a row when there are a bunch of new icon requests.

Again, these are just some initial observations. I think we should definitely consider this since, as @AryanBeezadhur points out, it is much easier to see the actual rank on SimilarWeb than it is with Alexa. But I'd suggest holding off on creating a PR with changes a bit until we have a clearer picture of the advantages and disadvantages.

**Comment by PeterShaggyNoble** [comment]
We can certainly try it out as another alternative means of measuring popularity but given, among others, the issues Eric has mentioned above ([they don't seem to know we exist!](https://www.similarweb.com/error/simpleicons.org/)), I don't see it as a viable replacement for Alexa.

**Comment by AryanBeezadhur** [comment]
The URL you provided is wrong. This is the correct one: https://www.similarweb.com/website/simpleicons.org/

SimilarWeb acknowledges that the site exists by displaying the site favicon and tagline, but they do not display any detailed stats for a site with less than 50k visits.

**Comment by AryanBeezadhur** [comment]
> Similar to how search engines like Google index the web, SimilarWeb employs an automated technique for capturing and indexing public data from over a billion website pages and apps every month.

[Source](https://support.similarweb.com/hc/en-us/articles/360001631538-SimilarWeb-Data-Methodology#:~:text=SimilarWeb's%20public%20data%20sources%20are,pages%20and%20apps%20every%20month.)

[SimilarWeb Data Sources](https://www.similarweb.com/corp/ourdata/)

SimilarWeb has [many fortunte500 clients](https://www.similarweb.com/corp/clients/#:~:text=Trusted%20and%20Loved%20by).

**Comment by PeterShaggyNoble** [comment]
Thanks for bringing this to our attention, @AryanBeezadhur. While it will definitely come in handy as one of our alternative measurements of popularity, there are just too many issues with it for it to (yet) replace Alexa as our primary metric. Consider, for example, that we could easily be checking the popularity of 10 or more sites in a single sitting and, if we don't get results from SimilarWeb, we'd have to go to Alexa anyway, which would take more time.

I'd definitely be happy to revisit this, though, should they make a few improvements to their service.
