### ISSUE TITLE
Request to add icon for "OpenCV"

### ISSUE THREAD

**Issue by Severus11** [simple-icons/simple-icons#3341]
**Name:** OpenCV
**Website:** https://opencv.org/
**Alexa rank:** 16,634
  

**Official resources for icon and color:** https://opencv.org/resources/media-kit/

**Comment by ericcornelissen** [comment]
Unfortunately the media kit does not contain an SVG, but [Wikipedia does have an SVG version of the logo](https://en.wikipedia.org/wiki/OpenCV#/media/File:OpenCV_Logo_with_text_svg_version.svg) (didn't check its quality).

Would you be interested in contributing this icon yourself @Severus11? You can read more about how to do that in [the Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)

**Comment by Severus11** [comment]
Sure @ericcornelissen ! 
I will refer to the guidelines are give a try !

**Comment by PeterShaggyNoble** [comment]
Are you still interested in taking this one on, @Severus11?

Looks like the media kit has been updated since @ericcornelissen checked it as it now includes SVGs which we can use.

Tricky choice on the colour; we could go with one of the 3 from the logo but, for some reason, I find myself leaning towards the purple they use for the hover colour on their social media links, among other places.

**Comment by Severus11** [comment]
heyy 
i was not able to add the icon because while reducing the size its quality is degrading.
will look on the media kit as well or someone from simply icons could try

**Comment by JoaoPedroMoraes** [comment]
I would like to take this pr

**Comment by ericcornelissen** [comment]
Great @JoaoPedroMoraes :smile: I assigned you to the issue so that other can easily find that out as well :+1:
