### ISSUE TITLE
Please add GIT-LFS Icon

### ISSUE THREAD

**Issue by sodre** [simple-icons/simple-icons#3368]
**Name:** Git LFS
**Website:** https://git-lfs.github.com/
**Alexa rank:**
  

**Official resources for icon and color:**
  
https://raw.githubusercontent.com/git-lfs/git-lfs/master/script/windows-installer/git-lfs-logo.ico
https://raw.githubusercontent.com/git-lfs/git-lfs/master/script/windows-installer/git-lfs-logo.bmp

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @sodre :+1:

The first thing we need to decide is whether this can be considered a brand in its own right or is it just a feature of GitHub. I'd lean towards the latter but we have already added GitHub Actions, which I also viewed as a feature rather than a brand. Thoughts, @simple-icons/maintainers?

If we do decide to add it, there's an SVG embedded in the HTML of the website's header and, for the colour, I'd suggest either `#f64935` from that SVG or `#f64b18` from the website's stylesheet.

**Comment by sodre** [comment]
Hi @PeterShaggyNoble thanks for looking into it.

Although git-lfs was written by github, the technology is implemented in other sites, e.g. GitLab, BitBucket and Sonatype Nexus can all host "git-lfs" content.

I am happy with either color ;)

**Comment by PeterShaggyNoble** [comment]
Yep, that definitely makes a better case for inclusion than Actions :+1: Thanks for the info, @sodre. Would still like some feedback from the other @simple-icons/maintainers before we move on with this, though.

**Comment by ericcornelissen** [comment]
Git LFS to me seems like something that can be included in the collection, thanks for the request @sodre :+1:

**Comment by PeterShaggyNoble** [comment]
Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself, @sodre?

**Comment by loganmarchione** [comment]
@PeterShaggyNoble  - Thoughts on this? If ok, I can submit.
`<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Git LFS icon</title><path d="M0 16.592l12.04 6.948v-9.675L24 6.957 19.368 4.28l-11.96 6.908v3.883l-2.776-1.601V9.586l11.965-6.908L11.966.005 0 6.913zm12-2.79l.04 9.738L24 16.63V6.957z"/></svg>`

```
        {
            "title": "Git LFS",
            "hex": "F64935",
            "source": "https://git-lfs.github.com/"
        },
```

**Comment by PeterShaggyNoble** [comment]
Fire away with the PR and we'll take it from there, @loganmarchione :+1:

**Comment by sodre** [comment]
@loganmarchione thank you so much!
