### ISSUE TITLE
Request: Unilever icon

### ISSUE THREAD

**Issue by KarthikNayak024** [simple-icons/simple-icons#3475]
**Name:** Hindustan Unilever Limited
**Website:** [HUL](https://www.hul.co.in/)
**Alexa rank:** 85,087
  

**Official resources for icon and color:**

**Comment by NovaGL** [comment]
Since this logo is the same as the parent brand I changed the subject to be easier to identify.

Color:  `#1F36C7`

Do you think you would be up to trying to do a pull request, you can use the logo embedded in the site.

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by KarthikNayak024** [comment]
> Change the icon's viewbox/canvas/page size to 24x24.
I did not understand how to do this. Can you please help with this step @NovaGL ?

**Comment by NovaGL** [comment]
Try opening it in inkscape that's how I do it

**Comment by KarthikNayak024** [comment]
Thanks, but there is width and height property got inserted in the SVG tag. Is that fine?

**Comment by NovaGL** [comment]
No it's not, if you're not sure look at how other icons are formatted and make sure if you run it through SVGOMG or similar.
