### ISSUE TITLE
Request: Alibaba Cloud

### ISSUE THREAD

**Issue by yenkhoon** [simple-icons/simple-icons#3538]
![](https://seeklogo.com/images/A/alibaba-cloud-logo-898D58C1CE-seeklogo.com.png)

**Name:** Alibaba Cloud
**Website:** alibabacloud.com
**Alexa rank:** 6158
  

**Official resources for icon and color:** grey and white

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @yenkhoon. I haven't been able to find a vector version of this logo (as yet) but for anyone with the skills to redraw it from a raster file, there's a decent quality PNG available [here](https://www.alibabagroup.com/en/news/library).

Also, are you sure about the colour? My research so far would lead me to choose the orange rather than the grey.

**Comment by adamrusted** [comment]
I've been able to vectorize just the icon from the PNG @PeterShaggyNoble linked - full path (which passes Linter) below.

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>AliCloud icon</title><path d="M24 8.592v6.816a4.082 4.082 0 0 1-4.082 4.082h-5.204l1.219-1.812 3.591-.93a2.164 2.164 0 0 0 1.533-2.07V9.381c0-.98-.659-1.838-1.606-2.091l-3.471-.925-1.254-1.855h5.191A4.081 4.081 0 0 1 24 8.592zM4.476 16.749a2.164 2.164 0 0 1-1.533-2.07V9.381c0-.98.659-1.838 1.606-2.091l3.485-.929 1.247-1.852H4.082A4.083 4.083 0 0 0 0 8.592v6.816a4.082 4.082 0 0 0 4.082 4.082h5.183l-1.234-1.822-3.555-.919zm3.48-3.847h8.013V11.06H7.956v1.842z"/></svg>
```

**Comment by fbernhart** [comment]
I guess we could use this PDF (page 19) as well as source here for a vectorized version:
https://doc.irasia.com/listco/hk/alibabagroup/annual/2020/ar2020.pdf
