### ISSUE TITLE
dts (sound)

### ISSUE THREAD

**Issue by tomlut** [simple-icons/simple-icons#3610]
**Name:**dts
**Website:**https://dts.com/
**Alexa rank:**388,008
  

**Official resources for icon and color:**https://dts.com/

**Comment by jorgeamadosoria** [comment]
@tomlut after some back and forth and given a long time to check the ups and downs of this website on the Alexa Ranking, it seems that it has spent more time over 500k than below. 
I think that given this, we need to close this issue due to the brand not achieving the requirements for inclusion.
If you keep an eye on the website ranking and it stays below 500k for three months, then feel free to reopen this issue or open a new one for the same brand.
Best of luck.
