### ISSUE TITLE
Addition of Icon: OSF

### ISSUE THREAD

**Issue by ramlaxman** [simple-icons/simple-icons#3651]
**Name:** OSF
**Website:** https://osf.io/
**Alexa rank:** 52,644
  

**Official resources for icon and color:**  https://osf.io/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @ramlaxman.

There's an SVG available [here](https://github.com/CenterForOpenScience/ember-osf-web/blob/develop/public/assets/images/default-brand/cos-logo-white.svg) but it's pretty terrible so we're probably best to have someone manually recreate it.

**Comment by service-paradis** [comment]
Additional info at #6811 from @roaldarbol

**Comment by einbandi** [comment]
I took a stab at redrawing their logo.

Because the logo is always used in its blue/white variant, I had to modify it slightly to make it work in monochrome. Are there any guidelines about how this is usually done (e.g., line widths of the outlines separating to colored faces)?

Below you can see five versions:

1. The (truly terrible) SVG mentioned by @PeterShaggyNoble.
2. A redrawn version based on the PNGs menioned by @service-paradis (fixing some minor alignment issues that seem to be present in all versions)
3. A monochrome variant of the redraw, which obviously does not work.
4. A version with the outlines in a similar thickness as I found it in other icons.
5. A version with much thicker outlines, optmized for very small sizes (such as usage in shileds.io badges).

![osf-logo](https://user-images.githubusercontent.com/11440522/186390346-d6c8fe5c-e3f1-47e3-acb4-4fdcb781c133.png)

Once I get some feedback on the linewidth I'd be happy to make a pull request.

**Comment by einbandi** [comment]
I just found the info on the 0.5 px gaps on the contribution page. I'll create the SVG accordingly and prepare a pull request.
