### ISSUE TITLE
Request: Castorama logo

### ISSUE THREAD

**Issue by MathRobin** [simple-icons/simple-icons#390]
French retailer specialized in house stuff 

Ask me if you need details

**Comment by mike3run** [comment]
make a PR man, lol

**Comment by MathRobin** [comment]
The better I can draw is a circle... And I can fail twice before succeed. Sorry :s

**Comment by mike3run** [comment]
Lol you don't need to draw anything man, also since you're talking about a large company you can always google:

`castorama logo svg` yields this:

https://upload.wikimedia.org/wikipedia/fr/1/1b/Castorama_2014_logo.svg

So download that make a Fork add it to the logos and submit a PR.

Github 101 😄 

Hope this helped you get oriented

**Comment by MathRobin** [comment]
It's more easy presented like this

**Comment by birjolaxew** [comment]
Their logo (as seen on their LinkedIn)

![Castorama logo](https://user-images.githubusercontent.com/4542461/27997744-57f28cb8-64ff-11e7-9ca3-7cde6acba024.png)
