### ISSUE TITLE
Update Google Meet/Chat

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#4134]
**Name:** Google Meet
**Official resources for icon and color:**
  https://apps.google.com/meet/

**Name:** Google Chat
**Official resources for icon and color:**
  https://chat.google.com/error/noaccess?pli=1

See popular questions in https://apps.google.com/meet/

- Google Hangouts Meet has been renamed Google Meet in 2019
- Google Hangouts Chat has been renamed Google Chat in 2019

**Comment by ericcornelissen** [comment]
Thanks for bringing this up @service-paradis, I opened a PR for the name change so that that is included in the v4 release. As I mentioned in that PR, I wonder if we should actually update the logos as well. I think yes as they both use new logos in the headers of their website. But, interestingly, both still use the old logo for their favicon. (Perhaps so people still recognize the product in a pined tab?)

Anyway, in both cases an SVG version of the logo can be found in the header. The Meet logo seems pretty easy to make monochrome, the Chat icon will be harder.

**Comment by service-paradis** [comment]
This issue is "kind of" related to #3725 where we talked about updated icons. The difference is the name changing for those 2.
I think we should update the SVG too as part of the name change.
We can also wait and take the time to track and update every Google outdated logos.

**Comment by ericcornelissen** [comment]
Seems like it is related yes. I went ahead and did the name change because otherwise we need a separate major release for that which isn't all that nice. Of course, the sooner they're updated the better but given that Google still uses the old versions I felt like we are fine with the old ones for a bit as well.

**Comment by service-paradis** [comment]
> Seems like it is related yes. I went ahead and did the name change because otherwise we need a separate major release for that which isn't all that nice. Of course, the sooner they're updated the better but given that Google still uses the old versions I felt like we are fine with the old ones for a bit as well.

Totally agree!
Should we update #3725 to list every Google icons that needs to be updated and pin it like you've done for #2887? In this case, we could close this one.

**Comment by ericcornelissen** [comment]
I think it's a good idea to keep track of all Google related icons in one issue like #2887 yes. We can either use #3725 for that purpose (or this issue), or create a new issue all together - linking and closing #3725 and this.

**Comment by service-paradis** [comment]
Closing in favor of #4205
