### ISSUE TITLE
Dealing with requests for individuals, musicians, bands, sport clubs, universities, government agencies etc.

### ISSUE THREAD

**Issue by fbernhart** [simple-icons/simple-icons#4274]
Most of the icons at simple-icons concern either software projects or big, international companies. But there are a number of other "brands" out there, that people are requesting to be added to simple-icons.

The purpose of this issue (based on the discussion in #4270) is to create a unified place to discuss what should be added to simple-icons and what not. And how to measure the popularity, as an Alexa rank or stars on GitHub might not be the best metric to measure popularity for every brand.

### Type of brands

Here is a list of types of "brands" that have been requested or might be requested:

Type | Related issues/PRs | Examples
--- | --- | ---
Musicians or bands | #4270 | Ed Sheeran, Kanye West, Rammstein
YouTubers, YouTube Channels | #2944 | [PewDiePie](https://www.youtube.com/user/PewDiePie/featured), [5-Minute Crafts](https://www.youtube.com/c/5MinuteCraftsYouTube/featured), ...
Sport clubs or sport organizations | #2406 #2791 (discussed in #2513) | FC Bayern München, Bundesliga, NBA, WWE, Olympic, ...
Universities or educational institutes |  - | MIT, Oxford, Stanford, ...
Governmental organizations / departments / programs / agencies | #1635 #2318 |  Gov.uk and FedRAMP (which are actually already part of simple-icons), US AirForce, NASA, ESA (European Space Agency), ...

What are your opinions on these ones? Which ones would you consider a brand? Which could be added to simple-icons?

### Popularity and how to measure it

- For musicians, bands and YouTubers/channels probably an Alexa rank won't be the best option to measure popularity.
I can image that for example some individuals are very popular on YouTube with millions of views and subscribers, but have a website that isn't visited that much (and therefore has a low Alexa rank). What do you think about another metric for musicians, band and YouTube channels? Could the number of subscribers or views be an adequate replacement for an Alexa rank in this case?
With GitHub stars (5k at least) we already have an alternative measurement to measure popular software projects with not much traffic to their websites.
Of course this would only apply to musicians/YouTubers that are using a logo. If they are just popular but don't have any logo, we can't add them anyway.

- I guess sport clubs, sport organizations and universities could be covered by the Alexa rank. They should have enough traffic to their sites, if they are popular enough. So we could add MIT and Oxford, but not that small university in rural India for example. Same with sport clubs/organizations: Olympic, WWE, FC Bayern München could be added by their Alexa rank, but not the small soccer team from the neighbour village.

- I guess we could measure governmental departments / agencies as well by their Alexa rank. But here I have some doubts concerning legal stuff. I'm not too sure if it's legal to publish for example the logo of the US Air Force on simple-icons. It shouldn't look like we are acting on their behalf.
Should we check this for every request individually or not allow any governmental stuff at all? That would mean to probably as well remove the [gov.uk icon](http://simpleicons.org/?q=gov.uk).

Opinions from @simple-icons/maintainers as well as from other contributors are highly welcome! 😊

**Comment by NovaGL** [comment]
I brought this up before sports clubs no problem as they're hugely popular. I don't think we should do gov icons as then we go down the slippery slope of allowing flags as they are technically a brand of the country.

I also mentioned yearly releases eg NBA 20219 2020 etc, we agreed that it comes down to popularity and should be decided on a case by case basis.

There is never going to be a hard and fast rule for everything.

**Comment by fbernhart** [comment]
I personally would be fine with adding universities, sport clubs and sport organizations (if their Alexa rank is above 500k). I would not add governmental stuff (due to possible legal reasons).

I'm divided on musicians, bands and Youtube channels. My feeling is that it would be better to stick to "organizations/companies" than to add brands of individuals.

**Comment by ericcornelissen** [comment]
Regarding governmental organisations: I think we **could** clearly state that organisations are okay while explicitly disallowing flags. I'm not sure about the legal reasons regarding governmental stuff, but if there's evidence this could be a problem I agree we should disallow it (just like we disallow a lot of Disney stuff).

> I'm divided on musicians, bands and Youtube channels. My feeling is that it would be better to stick to "organizations/companies" than to add brands of individuals.

This is interesting (and good, imo) wording. I agree that it would exclude many such brands, while still allowing some when it makes sense. To check my intuition of this, would organisations such as The Gates Foundation still be allowed or not? I would be fine either way, but in my reading of your comment it would be allowed.

**Comment by mondeja** [comment]
I would like to state that, apart from the point of view of admissibility, we must take into account what we can reasonably cover. In this sense, for example, accepting sports clubs could be admissible, but not achievable and this inclusion could compromise the affordability of this project, in addition to increasing the risks of legal problems.

So, point by point, I think the following:

- Sport clubs or sport organizations: Sport organizations yes, clubs not. We can ask users who want sports club icons to maintain a side project in which they only accept sports clubs, since the scope can be well defined.
- YouTubers, YouTube Channels: any brand representing individuals should be avoided. Representatibily here means that the name is directly related with the services provided by an individual. This would be unrestricted to Youtube Channels.
- Musicians or bands: as I've stated for sport clubs, this could be separated in another project to preserve maintainability, and if someday we can afford it, include them in simple-icons.
- Universities or educational institutes: I'm not against these inclusions.
- Governmental organizations / departments / programs / agencies: of course, not because this could introduce political biases and legal problems to the project, due to government brands are treated differently from commercial ones in many countries. I'm in favour of remote GOV.UK, this icon should never have been added to the project.

**Comment by service-paradis** [comment]
I, mostly, have the same though as @mondeja on this subject.
There are [~300 potentially valid request](https://github.com/simple-icons/simple-icons/issues?q=is%3Aissue+is%3Aopen+label%3A%22new+icon%22) right now. If we open this repo to Sports club, bands, musician, ..., it can become unmaintainable real fast.
The number of invalid request would probably be higher too, since people will need to determine which measure is valid depending on the brand they ask.

The idea of having separate repos for some of them might be a good idea (ex. simple-icons/band-icons, simple-icons/sports-icons, ...), but would need to find people able to maintain those as well...

**Comment by ericcornelissen** [comment]
Some more good and clear guidelines. I would agree by and large. I do have one question regarding your list @mondeja: what is the difference between Universities and Sports clubs (say, e.g., at the scale of Soccer clubs in Europe)? I'd say they're pretty much at the same level :thinking: 

> The idea of having separate repos for some of them might be a good idea (ex. simple-icons/band-icons, simple-icons/sports-icons, ...), but would need to find people able to maintain those as well...

We could encourage anyone who submits an out-of-scope request to start such a repository using the same/a similar format to this. If it looks promising it could be included in the simple-icons organisation.

**Comment by mondeja** [comment]
> what is the difference between Universities and Sports clubs (say, e.g., at the scale of Soccer clubs in Europe)?

You're right, are in the same level. My Eurocentric vision makes me forget that in countries like the United States sports clubs and universities are most of the time united. In Europe this is very rare, and when I wrote it down I was thinking about the inclusion of Universities above all, mistakenly believing that the majority of educational centers might not reach the level of popularity of simple-icons, but now I realize that this is not the case. I've edited in the comment above.

**Comment by ericcornelissen** [comment]
Okay, I did a quick pass over the current icons and if we decide on these guidelines it seems we only have to remove two government-related icons, namely: [GOV.UK](https://simpleicons.org/?q=gov.uk) and [FedRAMP](https://simpleicons.org/?q=FedRAMP). It seems currently we are in agreement between @mondeja, @service-paradis, and @ericcornelissen. Would like to know the opinion of one more @simple-icons/maintainers before we "finalize" this with a PR.

Also, I have a two more potential categories that are not entirely clear to me yet:

- We allow international organisation right? E.g. [International Air Transport Association](https://simpleicons.org/?q=iata) or [WHO](https://simpleicons.org/?q=world%20health%20organization).
- What about metro/public transport brands? They're often/sometimes government "owned" (e.g. [Transport for London](https://simpleicons.org/?q=Transport%20for%20London), [Transport for Ireland](https://simpleicons.org/?q=Transport%20for%20Ireland), [Karlsruher Verkehrsverbund](https://simpleicons.org/?q=Karlsruher%20Verkehrsverbund), [Metro de Madrid](https://simpleicons.org/?q=Metro%20de%20Madrid), [Metro de Paris](https://simpleicons.org/?q=Metro%20de%20Paris), [Metro de la Ciudad de Mexico](https://simpleicons.org/?q=Metro%20de%20la%20Ciudad%20de%20Mexico), [Moscow Metro](https://simpleicons.org/?q=Moscow%20Metro), [Shanghai Metro](https://simpleicons.org/?q=Shanghai%20Metro), [Shenzhen Metro](https://simpleicons.org/?q=Shenzhen%20Metro), [Tokyo Metro](https://simpleicons.org/?q=Tokyo%20metro), [Guanzhou Metro](https://simpleicons.org/?q=Guanzhou%20metro), [Cairo Metro](https://simpleicons.org/?q=cairo%20metro))

* * *

Also, just for for, I put together a short list of alternative simple-icons repositories:

- band-icons
- gov-icons
- retro-icons
- legacy-icons (e.g. [Windows 95](https://simpleicons.org/?q=Windows%2095))
- product-icons (e.g. Windows icon in this category, Microsoft icon in simple icons)

Can we think of more? If these are adopted as separate projects into the organization, simple-icons should probably be renamed _brand-icons_.

**Comment by mondeja** [comment]
> We allow international organisation right?

For me, yes. I suppose they would be more inclined to enter the terms of the license.

> What about metro/public transport brands?

Since a lot of work has already been done on these and many could be under public concession, I would leave them in the project. If someday there are problems with any of them, we could eliminate them.

Regarding the list of alternative repositories, we could add 'sport-icons'.

**Comment by runxel** [comment]
Late to the party, but still willing to throw my 2 cents into the discussion, since it is valuable and has a high impact for the future (:

I mostly agree with what has already been said, tho.

❌ **Flags** are a hard no. Not even as a side-repo. There are other people doing this. Or just use emojis anyway.
❌ **Gov** icons should not be a part of simple-icons. This includes any agencies and departments directly related, as well of course any military and intel stuff.  
This should _not_ include any forms of companies, which belong to the state but providing services for the general public, like the public transport icons already added, or train services (like "Deutsche Bahn") etc. [1]  
A grey area are things like NASA and ESA and other state institutions in the science area to me. I wouldn't be as harsh there.
❌ **Sport clubs** just open the floodgate for soooo many requests. A clear "no" on this one. BUT we can allow sport _organizations_. There are only this much of them.   
E.g. "Bayern Munich" is not allowed, but "Deutsche Bundesliga" (football org/league) is.
❌ **Universities**
❌ **YouTube** Channels. Popularity might be relatively easy to determine, but again, this just opens the floodgate to soo many requests and would make the whole project unmaintainable.
❌ **Musicians** and bands. Same as above.
❌ **Yearly releases** of anything. Even if they are hugely popular. They won't be next year. 🤷‍♂️

✅ **International Orgs** and **NGOs** are okay for me. E.g. "Unicef", "WHO".


I like @ericcornelissen's shortlist!  
Not sure if Windows 95 is "legacy" or "retro" tho 😄   

For sport-icons I'm not as sure if they would even work with our current approach, however. See: Many sport icons do not only have one color but multiple (see "Bayern Munich). They might be not as easy to make monochrome as other brands.

---

[1] Any governmental icons should be removed in the next major version.

**Comment by ericcornelissen** [comment]
> > What about metro/public transport brands?
> 
> Since a lot of work has already been done on these and many could be under public concession, I would leave them in the project. If someday there are problems with any of them, we could eliminate them.

Fair point, I agree 👍 


> Late to the party, but still willing to throw my 2 cents into the discussion, since it is valuable and has a high impact for the future (:
> 
> I mostly agree with what has already been said, tho.
> 
> ❌ **Flags** are a hard no. Not even as a side-repo. There are other people doing this. Or just use emojis anyway.
> ❌ **Gov** icons should not be a part of simple-icons. This includes any agencies and departments directly related, as well of course any military and intel stuff.
> This should _not_ include any forms of companies, which belong to the state but providing services for the general public, like the public transport icons already added, or train services (like "Deutsche Bahn") etc. [1]
> A grey area are things like NASA and ESA and other state institutions in the science area to me. I wouldn't be as harsh there.
> ❌ **Sport clubs** just open the floodgate for soooo many requests. A clear "no" on this one. BUT we can allow sport _organizations_. There are only this much of them.
> E.g. "Bayern Munich" is not allowed, but "Deutsche Bundesliga" (football org/league) is.
> ❌ **Universities**
> ❌ **YouTube** Channels. Popularity might be relatively easy to determine, but again, this just opens the floodgate to soo many requests and would make the whole project unmaintainable.
> ❌ **Musicians** and bands. Same as above.
> ❌ **Yearly releases** of anything. Even if they are hugely popular. They won't be next year. 🤷‍♂️
> 
> ✅ **International Orgs** and **NGOs** are okay for me. E.g. "Unicef", "WHO".

Thanks a bunch, even if you're late. Also, thanks for including the "yearly releases" thing, can't remember where that came up first but I'm also against it.

I also like the use of emojis, wonder if we should do this in the Contributing Guidelines as well 🤔 


> Any governmental icons should be removed in the next major version.

Given the discussion (and seeming concensus) here, yes. I propose we add a separate issue for that once this issue is closed, add it to [the v5 milestone](https://github.com/simple-icons/simple-icons/milestone/4) and label it as [a 1 breaking change1 ](https://github.com/simple-icons/simple-icons/issues?q=is%3Aopen+is%3Aissue+label%3A%22breaking+change%22).


* * * 


> I like @ericcornelissen's shortlist!
> Not sure if Windows 95 is "legacy" or "retro" tho 😄

Yes, I wasn't sure either. I choose legacy because legacy is a bit easier to define than retro, I think.


> For sport-icons I'm not as sure if they would even work with our current approach, however. See: Many sport icons do not only have one color but multiple (see "Bayern Munich). They might be not as easy to make monochrome as other brands.

Fair point. Then again, there have been discussion here on allowing multiple colors as well...

**Comment by ericcornelissen** [comment]
Given we seem to have reached consensus, any of the @simple-icons/maintainers up for adding these details into the Contributing Guidelines?

**Comment by fbernhart** [comment]
I'll create a PR so change the contribution guidelines.

But just to double check:

### Won't add
- Governmental icons (we'll remove Gov.uk and FedRAMP)
- Flags
- Youtube Channels
- Musicians, Bands
- Universities
- Sport Clubs
- Yearly releases of anything
- Any other brands representing "individuals"

###  Allowed stuff
- Sport Organizations
- International Organizations / NGOs (Unicef, WHO)


How about brands that are kind of related to governmental stuff? NASA or ESA for example?

**Comment by mondeja** [comment]
> How about brands that are kind of related to governmental stuff? NASA or ESA for example?

I would allow them if its role clearly falls within the supranational general interest.

**Comment by ericcornelissen** [comment]
> How about brands that are kind of related to governmental stuff? NASA or ESA for example?

We can add explicitly that space-related brands are allowed, even if they're governmental. We could add further exceptions in the future if necessary. In any case, it might be worth repeating the following sentence from the existing Contributing Guidelines:

> If you are in doubt, feel free to submit it and we'll have a look.

**Comment by fbernhart** [comment]
Done. Feel free to have a look at it --> https://github.com/simple-icons/simple-icons/pull/4373
