### ISSUE TITLE
theCwind solutions, inc. CA

### ISSUE THREAD

**Issue by DrmedPatrickSchur** [simple-icons/simple-icons#4329]
**Name:** theCwind solutions, inc.
**Website:** www.theCwind.com
**Alexa rank:** This is very expensive, we cannot and will not take an Alexa account because of this, please advise. Patrick.schur@theCwind.com 
  

**Official resources for icon and color:**
  

![09](https://user-images.githubusercontent.com/28396318/101988851-af630900-3c9c-11eb-823a-457e261fb4f2.gif)

**Comment by fbernhart** [comment]
Hi @DrmedPatrickSchur, thanks for your request.

Getting ranked by Alexa is actually for free. You just need a website that is more or less popular and gets enough traffic.

Unfortunately it seems like your website is either pretty new and therefore not ranked yet. Or there is simply very little traffic to your site.

Both are indicating, that "the C Wind" isn't really a popular brand. We are having a limit of an Alexa rank of at least 500,000 in order to be added to simple-icons icons.

I'll close this issue for now. If "The C Wind" will every reach this target, feel free to reopen the issue or create a new one.
