### ISSUE TITLE
Remove impossible labels automatically

### ISSUE THREAD

**Issue by mondeja** [simple-icons/simple-icons#4332]
After reviewing a pull request, it is very common that I forget to remove some tags from it, such as when the pull was marked as `changes requested`, it becomes accepted, the merge is done and ... have I removed the tag? :thinking:

So, I've created [a simple Github Action](https://github.com/mondeja/remove-labels-gh-action) that just removes tags from issues and pull requests. Combining it with github events and filtering by their states, we can forget the need of remove the impossible tags for each context, shown below. There is in their README a possible configuration for `simple-icons`.

> You can see running with [this action](https://github.com/mondeja/test-gh-actions-webhooks/runs/1542804434?check_suite_focus=true) for [this issue](https://github.com/mondeja/test-gh-actions-webhooks/issues/9) when I close it.

What do you think? I'm too lazy :sweat_smile: and this is something too intrusive, or could improve the review speed? Is there a label that I am forgetting for some context?

### Pull request closed

- `in discussion`

### Pull request merged

- `awaiting reply`
- `changes requested`
- `duplicate`
- `in discussion`
- `invalid`
- `out of scope`
- `pending`
- `won't add`

### Issue closed

- `in discussion`
- `pending`
- `tracking`

**Comment by fbernhart** [comment]
How about "awaiting reply" for closed issues?



And as this fits pretty well here:

What do you think about the following small change to the pull request template:

Instead of "Issue:" we could use the word "Closes", which will automatically close the open issue, if the PR get's merged. So we don't have to close the issue manually after merging the PR.

See https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

**Comment by mondeja** [comment]
> How about "awaiting reply" for closed issues?

At first I was going to include it, but on second thought I have come to the conclusion that a issue could be closed because there was no response from the user who opened it. But I'm not against add it.

 > What do you think about the following small change to the pull request template.

I agree, but perhaps a user not experienced with Github could link to an issue (eg, a tracking one) marking for close it without realizing it, which might be strange to him. I guess we should keep the repository accessible to novice contributors. Anyway, this can be discussed in #3205.

**Comment by fbernhart** [comment]
Ok, thanks for the feedback!

I agree with both. 😊👍🏼

**Comment by ericcornelissen** [comment]
First of all: love it! I have been considering this so many times :laughing: Apparently not enough for me to create an issue and an Action though :upside_down_face: I do think that [`tracking`](https://github.com/simple-icons/simple-icons/labels/tracking) should be removed from closed issues as well.

> At first I was going to include it, but on second thought I have come to the conclusion that a issue could be closed because there was no response from the user who opened it. So, maintain the awaiting reply label in a closed issue could have sense if you say to the user: "reopen this if you don't agree with x...". But I'm not against add it because this behaviour could a bad practice.

I agree that this one is a bit ambiguous. In the case that we close an issue because we were waiting for a replay for too long I think we should either add a comment as you said, or perhaps introduce a `stale` label instead of `awaiting replay` (*). In other words, I would say that keeping `awaiting replay` on closed issues is (somewhat) bad practice.

That said, I would be fine leaving `awaiting replay` on closed issues. I definitely think we can start using the action before we made a decision in this regard!


(*): I don't think your action can do conditional removals of issues yet, but that would be ideal in this case.

**Comment by mondeja** [comment]
Thanks for your feedback @ericcornelissen

> I do think that tracking should be removed from closed issues as well.

You're right, I've added to the list.

> In the case that we close an issue because we were waiting for a replay for too long I think we should either add a comment as you said, or perhaps introduce a `stale` label instead of `awaiting replay` (*).

Yes, this behaviour would be better. I think that we can use another action that could add a new `stale` label if the closed issue has a `awaiting reply` label using Github Actions `if` conditionals and, in the next step, to use this action to remove the `awaiting reply`. Because this type of configuration is possible I prefer to maintain the action as a label remover only.

I'm adding tests to the action and after adding them I will open a pull request.

**Comment by ericcornelissen** [comment]
> Yes, this behaviour would be better. I think that we can use another action that could add a new stale label if the closed issue has a awaiting reply label using Github Actions if conditionals and, in the next step, to use this action to remove the awaiting reply. Because this type of configuration is possible, I prefer to maintain the action as a label remover only.

Sounds even better :+1:
