### ISSUE TITLE
Request BeautifulSoup Icon

### ISSUE THREAD

**Issue by Joylish** [simple-icons/simple-icons#4353]
**Name:** BeautifulSoup (bs4)
**Website:** https://www.crummy.com/software/BeautifulSoup/bs4
**Alexa rank:** https://www.alexa.com/siteinfo/crummy.com
  

**Official resources for icon and color:**
  
  
![image](https://user-images.githubusercontent.com/52230415/102066137-ce989c80-3e3c-11eb-94a7-66888cc7801e.png)

**Comment by fbernhart** [comment]
Hi @Joylish, thanks for your request.

Unfortunately the Alexa rank of [64,866](https://www.alexa.com/siteinfo/crummy.com) is only valid for the website crummy.com (the organization behind BeautifulSoup) and not for BeautifulSoup (a Python library, by the way) itself. Although their probably most famous (and only famous piece of software as far as I'm aware of) is BeautifulSoup. So probably most of the traffic to crummy.com is produced by people looking for BeautifulSoup; mostly because [the documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/) is as well hosted on crummy.com.

As well they [host their source code on launchpad](https://code.launchpad.net/beautifulsoup), which doesn't seem to have any kind of metrics to measure popularity (similar to the stars on GitHub).

As I'm programming in Python myself, I know that BeautifulSoup is pretty popular in the Python community. [PyPI stats](https://pypistats.org/packages/beautifulsoup4) indicates that there are around 9 million downloads of the BeautifulSoup library every month. So I personally would be in favour of adding it to simple-icons.

But I'd like to hear what the other @simple-icons/maintainers think about it.

**Comment by mondeja** [comment]
I agree with the inclusion, but the provided image is the official one? I'm not sure... :thinking: Where did you get the image from @Joylish?

**Comment by fbernhart** [comment]
@mondeja Thanks, I just had the same thought. There in fact doesn't even seem to be an official logo. The image provided is probably from https://funthon.wordpress.com/2017/05/21/beautiful-soup-4, which seems to be a unofficial logo someone quickly created.

So I guess we have to close this anyway.

**Comment by mondeja** [comment]
Thanks for the feedback @fbernhart. I agree with you that seems not to be an official logo.
Feel free to reopen this issue if you don't agree @Joylish
