### ISSUE TITLE
Streamlit icon missing

### ISSUE THREAD

**Issue by rlew631** [simple-icons/simple-icons#4368]
**Name:**
Streamlit
**Website:**
https://www.streamlit.io/
**Alexa rank:**
130,572 globally
95,588 US
48,401 India

**Official resources for icon and color:**
  https://www.streamlit.io/brand

**Comment by fbernhart** [comment]
**Source**: I haven't found any SVG version of their logo, neither on their website nor in their GitHub repo. So probably it's necessary to vectorize the PNG logo from their [brand page](https://www.streamlit.io/brand). I guess it would look good, if the color changes are highlighted with gaps (width 0.35px), similar to #4367.

**Color**: On their website they use `#FF4B4B` for buttons and headings. It's as well the leftmost color of their logo.

**Comment by rlew631** [comment]
It doesn't look like I can upload an svg so I put it in my repo. Strangebrewstrategies had actually made the [logo with the name](https://strangebrewstrategies.com/clients/client-streamlit.svg) the way you suggested and I just pulled the name out. Here's the logo: ![logo](https://raw.githubusercontent.com/rlew631/rlew631/dc0ff1cc96e78231c8748ba864b89505527c5369/streamlit.svg)

**Comment by fbernhart** [comment]
@rlew631 Thanks, but actually I don't think that we can use this version, as it seems to be of very bad quality.

If you zoom in, you should be able to see it:
![image](https://user-images.githubusercontent.com/70264417/102679250-8bc52480-41ae-11eb-9cc5-446bea028a93.png)

**Comment by rlew631** [comment]
@fbernhart Ah, that's a bummer. I've spent a good bit of time screwing around in photoshop but haven't messed with svgs much so I'll see what I can do

**Comment by rlew631** [comment]
Update! This is definitely better, but I've been squinting at that corner too long so let me know

Black Logo:
![black](https://raw.githubusercontent.com/rlew631/rlew631/5fcb1cee69c8034bfa2b98aad94b584fcff8d84f/streamlit.svg)
Red Logo:
![red](https://raw.githubusercontent.com/rlew631/rlew631/5fcb1cee69c8034bfa2b98aad94b584fcff8d84f/streamlit_red.svg)

**Comment by fbernhart** [comment]
@rlew631 I haven't looked at your SVGs in detail, but they look promising so far. 🎉 Would you like to give it a try and create a pull request yourself? 😊

All the necessary information can be found here: https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md

And yes, the gap width was relative to the standard size that we're using, which is a viewbox of 24x24 pixels. It's not necessary to stick to this width, it was just a suggestion because it turned out to have looked good on other logos.

**Comment by rlew631** [comment]
@fbernhart I can't seem to get the icon to be exactly centered and 24px wide using inkscape and exporting with a decimal precision of 3. It currently fails the checks since 24.001 isn't close enough. #4412

Any pointers?

**Comment by fbernhart** [comment]
@rlew631 I've had pretty bad experiences with setting the precision in Inkscape itself (File --> Save As --> Optimized SVG). The few times that I've tried it, it changed the shape of the SVG pretty much.

I'd recommend always optimizing it with SVGO (or [SVGOMG](https://jakearchibald.github.io/svgomg/) instead).

The failing check is due to the fact, that sometimes the optimization slightly changes the size (due to rounding). So that although your size is exactly 24.000, it might be 24.001 after optimization and therefore failing the linter.

- You could either try to set the size in Inkscape to 23.999 (the size of the icon, not the viewbox), so that after optimization it might end up being exactly 24.000.

- Or you could use a higher precision instead - 4 instead of 3 for example.

I would give the first one a try and if that doesn't work, you could still increase the precision to 4. I hope that helped. 😊

**Comment by rlew631** [comment]
Using SVGO to optimize fixed it. I figured I'd be able to make it work between inkscape and manually editing the file but looks like that wasn't the case. Thanks for all the pointers!

**Comment by fbernhart** [comment]
@rlew631 Which workflow do you mean? Creating an issue first?

You don't have to create an issue, you can directly create a PR as well.
