### ISSUE TITLE
I Created a Simple Icon Generator

### ISSUE THREAD

**Issue by peterpme** [simple-icons/simple-icons#443]
:wave:

Thanks for putting together this awesome list of icons!

[I've created a simple icon generator](https://github.com/peterpme/create-simple-icon)

I was hoping for two things:
- Being able to expose the json as an npm package
- Linking my generator to your repo

Right now I scrape the json and it works fine, but I'm not sure if this'll ever fail. If you have any questions for how the generator works or find any glaring bugs, I'd love to be able to work this out together!

**Comment by danleech** [comment]
@peterpme This is a popular request. I’ve never published on NPM so will need to do some reading.

**Comment by peterpme** [comment]
Hey @danleech! Thank you for considering this option! I'd to open a PR and help do this :)

**Comment by danleech** [comment]
Please do!

**Comment by RusinovAnton** [comment]
@danleech Hello, great job with library! Is there some problems with publishing it to npm? Can I help on it?  
I'm interested in npm package too because I want to make a react library based on it.  
There is already such lib [react-simple-icons](https://github.com/jxnblk/react-simple-icons), but I don't like the approach where all icons being hardcoded into JSON file and paths are read from it tho. I want make icon components more dynamically.
Looking forward for progress on this issue. Thanks

**Comment by ericcornelissen** [comment]
Going to close this issue since its main purpose, create a npm package, is fulfilled (see [here](https://www.npmjs.com/package/simple-icons))
