### ISSUE TITLE
Simplify CSS colours

### ISSUE THREAD

**Issue by edent** [simple-icons/simple-icons#4459]
### Kind of issue 
  - [X] Improvement
  - [ ] Bug
  - [ ] Other, namely:

### This issue concerns 
  - [x] The NPM Package
  - [x] The Packagist Package

### Description

Many of the colours in can be minified. for example, `#000000` can become `#000`, and `#9999FF` can become `#99F` etc.

This results in some bandwidth savings for sites which are trying to keep things as small as possible.

**Comment by fbernhart** [comment]
Hi @edent. Thanks for your idea.

Just to get some opinions from the other maintainers if this is a good idea, I'd like to ping them. @simple-icons/maintainers 

We've done something similar recently to display the icons on our website: https://github.com/simple-icons/simple-icons/pull/4333

**Comment by ericcornelissen** [comment]
I'd personally be against this. If you want to have minimize your bandwith usage through CSS/JS you should use a minifier, if it is a good one it will minimize the hex values for you. The reason I'm not in favor of doing this is twofold: the first is that I don't think we can assume these hex shorthands are supported everywhere - they are on the web due to CSS and as a result many design software packages as well, but I don't think it is universal (if you can convince me otherwise that would be great). The second is that it makes contributing slightly more difficult (if this was the only reason I wouldn't be against this suggestion but in combination with the other arguments this becomes relevant).

**If** we do decide to go ahead with this change, I do think we should only do it with a major release, as people may be depending on the fact that the color hex is six characters.

**Comment by NovaGL** [comment]
I agree with Eric, consistency is key.

Eg we have a rule that HEX's have to be uppercase, if we start allowing to many variations we lose control over it.

**Comment by adamrusted** [comment]
I'm going to close this for now. As @ericcornelissen and @NovaGL have mentioned, hex codes can be minified inside of whatever project is using Simple Icons, and it's important we maintain consistency in the data we put out via the packages. @simple-icons/maintainers feel free to reopen this if you think it needs further discussion.
