### ISSUE TITLE
Aderant

### ISSUE THREAD

**Issue by aduguid** [simple-icons/simple-icons#4466]
Name: Aderant

Website: https://www.aderant.com/

Alexa rank: 582,178

Official resources for icon and color: https://www.aderant.com/api/terms/

**Comment by fbernhart** [comment]
@aduguid Thanks for your request.

Unfortunately this seems to be out of scope for Simple Icons at the moment. We're requesting an Alexa rank of 500k and below for a brand in order to be added.

See our contribution guidelines for more details: https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md

Feel free to reopen this issue as soon as Aderant is popular enough.
