### ISSUE TITLE
I've created brandifyjs tool based on icons from this repo

### ISSUE THREAD

**Issue by greybax** [simple-icons/simple-icons#454]
Hi Dan,

Thank you for this repo. It rocks! :rocket: :sunny:

I'd like just to suppose 2 things:

* :thumbsup: for npm package
* I've created tool based on icons from this awesome repo. You can check it out on [brandifyjs playground](https://greybax.github.io/brandifyjs). I've also noticed issue https://github.com/danleech/simple-icons/issues/443 by @peterpme and this is great tool too. We can use it for automation process of creating new icons. I'd be really appreciate if you can do [brandifyjs](https://github.com/greybax/brandifyjs) part of this repo f.e. as sample of app where icons from this repo can be used.

:v:

**Comment by ericcornelissen** [comment]
@greybax I'm going to close this issue as I don't think its relevant to keep it open. Even though its an interesting project, I don't think we should include this project (or projects like it) in for example the README. Especially since the [Github dependency graph](https://github.com/simple-icons/simple-icons/network/dependents) already shows which projects are using Simple Icons.

One option could be to add repos like yours as organization repos, but I don't think your project necessarily adds any value to the organization 🙂
