### ISSUE TITLE
Tidyverse

### ISSUE THREAD

**Issue by JackDaoud** [simple-icons/simple-icons#4763]
**Brand Name:** Tidyverse
**Website:** https://www.tidyverse.org
**Alexa rank:** 44,252
  

**Official resources for icon and color:** I'm not sure where to get these...

**Comment by fbernhart** [comment]
Which one is the logo/icon you're looking for?

This one? https://www.github.com/tidyverse/tidyverse.org/tree/master/static%2Fimages%2Fhex-tidyverse.png

**Comment by JackDaoud** [comment]
Yes, that's the one!

**Comment by fbernhart** [comment]
I haven't found any official SVG version of their logo on their [website](https://www.tidyverse.org/), in their [website repo](https://github.com/tidyverse/tidyverse.org) or the [tinyverse repo](https://github.com/tidyverse/tidyverse). 

BUT I've found a SVG here https://github.com/rstudio/hex-stickers! As tinyverse seems to be supported by RStudio (according to the footer on their website) and as Rstudio has a repo with SVGs of popular R-packages (like tidyverse), I would consider it as a valid official source.

This is the SVG: https://github.com/rstudio/hex-stickers/blob/master/SVG/tidyverse.svg

Would you like to give it a try and create a pull request yourself, following [our contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)? @JackDaoud

**Comment by JackDaoud** [comment]
Thank you @fbernhart for finding the SVG. I'd love to give it a try and create a pull request myself, it'd be my first contribution :smiley:

**Comment by PeterShaggyNoble** [comment]
Given their alignment with RStudio, @fbernhart, I think we can safely assume that that SVG was either supplied by Tidyverse or, at least, is used with their blessing so I think we can consider official enough for our purposes. If we have doubts, though, we could ping someone from Tidyverse to confirm.

**Comment by JackDaoud** [comment]
@fbernhart, I looked over your [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md). Most of it looks doable for creating a pull request, except this one part:

`Using your preferred tool you should:

1. Isolate the icon from any text or extraneous items.
2. Merge any overlapping paths.
3. Compound all paths into one.
4. Change the icon's viewbox/canvas/page size to 24x24.
5. Scale the icon to fit the viewbox, while preserving the icon's original proportions. This means the icon should be touching at least two sides of the viewbox.
6. Center the icon horizontally and vertically.
7. Remove all colors. The icon should be monochromatic.
8, Export the icon as an SVG.`

I downloaded [Inkscape](https://inkscape.org/), but I don't have any experience editing SVG images. I was wondering if you had a specific resource I can refer to? An article or YouTube video?

**Comment by fbernhart** [comment]
@JackDaoud Sorry, but I don't have any specific resource that I can recommend. I've started with Inkscape and editing SVGs myself just some few months back. All I did was just "trial & error" and some quick Google searches. 😄 Maybe the Tidyverse icon isn't the easiest icon to start with, but here is what I would do concerning this icon:

- I find it easy to work with both, the "Objects" (`Object` - `Objects`) toolbox and the "XML Editor" (`Edit` - `XML Editor`) toolbox. So maybe make sure you enable both of them.
- In both toolboxes you can see that the icon consists of quite some polygons and polylines (all the "stars"). It's easier to convert all of them to paths first and then just work with the paths. So just click on them and then `Path` - `Object to Path` (Ctrl + Shift + C).
- Now just merge all the "stars" to one path, using `Path` - `Union` (Ctrl + +). Same with the www.rstudio.com and the tidyverse letters.
- Then I would delete the filling of the big hexagon, as it's not really needed.
- Now merge the stars, the hexagon itself, the www.rstudio.com letters and the tidyverse letters together. So that in the end you're having only one single path.
- The single path might be grouped, so ungroup it, using `Object` - `Ungroup` (Ctrl + Shift + G)
- Make sure you delete all the `style` attributes and everything else from that single path (can be seen in the XML Editor toolbox) It only needs the `d` attribute with the path.
- Then set the `viewBox` in the XML Editor to `0 0 24 24` and delete any other attributes. (Somehow I need to save and close Inkscape and open the file again on my machine. Otherwise Inkscape isn't showing the viewBox in the right size and behaves strangely on the next step - but this might be different on your machine)
- Click on the single path, and resize the bigger side to 24px (using the toolbar at the top). In this case it's the height. Make sure you've clicked on the lock icon before, so Inkscape will keep the height/width ratio!
- After that, click on `Object` - `Align and Distribute` (Ctrl + Shift + A). A toolbox will open, where you can align the icon horizontally and vertically.


That should basically be it! 😅  After that just optimize the SVG with either SVGO or SVGOMG and if you have npm installed, you can lint the resulting SVG file locally, to see if there are any more things that you will need to address. If not, just create a PR and our CI will lint it and tell you the same.

Feel free to give it a try. If you have any further questions, let me know here or just in your pull request. You could as well us our new Discussions section: https://github.com/simple-icons/simple-icons/discussions/categories/help-with-svgs We've created a room there for anyone that needs help with working with SVGs.

**Comment by PeterShaggyNoble** [comment]
Are you still working on this one, @JackDaoud?

**Comment by JackDaoud** [comment]
Yep @PeterShaggyNoble , been a bit busy but will get to this soon.

Forgot to reply @fbernhart but thank you for the detailed breakdown of how I can go about editing this icon. I'll look into it soon.
