### ISSUE TITLE
Snapcast logo

### ISSUE THREAD

**Issue by 70MM13** [simple-icons/simple-icons#4805]
**Brand Name:** Snapcast
**Website:** https://github.com/badaix/snapcast
**Alexa rank:** 75, but.. probably for github?
  

**Official resources for icon and color:**
https://github.com/badaix/snapcast/tree/master/doc
![](https://raw.githubusercontent.com/badaix/snapcast/master/doc/web_hi_res_512.png)

**Comment by adamrusted** [comment]
Hi @70MM13, thanks for the request!
Unfortunately, you're right about the Alexa Rank being for GitHub - and while we can also consider GitHub stars as a measure of popularity, Snapcast only has ~3.5k stars, which is too few for us to include them based on that metric. If you're able to provide a measure of popularity similar to those listed in the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) then we'd be able to look at it, otherwise it'd be out of scope at the moment, I'm afraid.

**Comment by 70MM13** [comment]
Hi,

Too bad! I looked if I could find a way to show how popular this is but couldn't find anything helpful... 1000+ downloads on Android won't help I guess? And I'm not going to track it down all those linux distributions :)

Thanks anyway

**Comment by PeterShaggyNoble** [comment]
Thanks for the information, @70MM13. Unfortunately, only 1000+ downloads on Google Play does still put it outside our scope so I'm going to close this out for now. If it ever does reach one of the thresholds of popularity that have been mentioned, though, feel free to reopen the issue.
