### ISSUE TITLE
Request: bookmeter.com (in Japanese: 読書メーター)

### ISSUE THREAD

**Issue by HelloRusk** [simple-icons/simple-icons#4824]
**Brand Name:** bookmeter (読書メーター)
**Website:** https://bookmeter.com/
**Alexa rank:** [23,152](https://www.alexa.com/siteinfo/bookmeter.com)
  

**Official resources for icon and color:**
  
  

There is [an SVG file](https://bookmeter.com/assets/common/logo-2bd6d48f3447beaa56041246b812bc2eb6e11706e1fea2ab027ac1d3420ba78d.svg) that is provided in the banner of the official website. This image includes the brand logo at the left side, but personally I don't like to use it because it seems to be too abstract (there could be many organizations that have similar logos, right?).  
Instead I'd like to convert [this PNG asset](https://bookmeter.com/images/common/profile_image.png) into SVG. It is a user's default icon who do not set their own profile icon. It's cute and quite familiar for everyone who use this website.

**Comment by adamrusted** [comment]
Thanks for the request @HelloRusk!

Unfortunately I would say given that the [Android](https://play.google.com/store/apps/details?id=com.bookmeter.android) and [iOS](https://apps.apple.com/jp/app/id509979590) apps both use the icon mentioned in the SVG, we'll have to go with that one as the `official brand icon` instead of the PNG profile icon you mentioned. The hex code in the SVG is `#64BC4B`, so that seems like a safe bet to go with. Would you like to contribute this icon yourself by following our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)?

**Comment by PeterShaggyNoble** [comment]
Picking up on an internal discussion, I think we can go with "Bookmeter" here, @adamrusted, as they do on [the App store](https://apps.apple.com/us/app/bookmeter/id509979590).

But it does raise a good point (somewhat related to #4797) of what to do when a brand does not have a name that's transl(iter)ated to the extended Latin alphabet?

**Comment by HelloRusk** [comment]
@adamrusted Thank you for your investigation. I agree with you.
I'd like to contribute by myself 😃
