### ISSUE TITLE
Request: Electron App like The Noun Project?

### ISSUE THREAD

**Issue by gastonmorixe** [simple-icons/simple-icons#484]

**Comment by ericcornelissen** [comment]
Can you elaborate on why you want this? Because I don't think having this project as a standalone app adds any value...

Is it the drag and drop feature? I'm curious as to how they did it, and perhaps it is even possible from the browser! Is it the coloring feature? That is possible in the browser too (maybe that is even a nice feature to add). Is it something else entirely, something that is not on their [landing page](https://thenounproject.com/for-mac/)?

**Comment by birjolaxew** [comment]
I think this would be a too big undertaking for the project; we're having trouble with just fulfilling all requests as it is.

If you want to start working on a desktop app, it would be much appreciated - but I'm closing this as out of scope for now.
