### ISSUE TITLE
Namecheap icon cannot be displayed

### ISSUE THREAD

**Issue by Latezly** [simple-icons/simple-icons#4887]
`https://img.shields.io/badge/-Namecheap-DE3723?style=flat-square&logo=namecheap&logoColor=ffffff`
![](https://img.shields.io/badge/-Namecheap-DE3723?style=flat-square&logo=namecheap&logoColor=ffffff)

\----

`https://img.shields.io/badge/-Namecheap-DE3723?style=flat-square&logo=cloudflare&logoColor=ffffff`
![](https://img.shields.io/badge/-Namecheap-DE3723?style=flat-square&logo=cloudflare&logoColor=ffffff)

like this,I replaced the parameter behind "logo=" with "cloudfalre" or any other icon name, which can be displayed normally

**Comment by adamrusted** [comment]
Hi @Latezly, thanks for getting in touch!
The icon for NameCheap was only added to the project 8 days ago, and so it's likely that Shields.io haven't updated their dependency on our library since. They're usually pretty quick, so it should be available by next week - though if you're still having issues it's worth [submitting an issue to them](https://github.com/badges/shields/issues/new/choose) to update their dependencies. Another option would be to convert the SVG available [in our repository](https://github.com/simple-icons/simple-icons/tree/master/icons) into [Base64](https://base64.guru/converter/encode/image/svg), and include it in the shields badge that way, though you won't receive updates if the icon should change.

**Comment by Latezly** [comment]
That's it, thank you for your answer
