### ISSUE TITLE
On Removing Hyphens & Symbols from File Names

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#4936]
### Kind of issue 
  - [x] Improvement
  - [ ] Bug
  - [ ] Other, namely:

### This issue concerns 
  - [x] The NPM Package
  - [x] The Packagist Package

### Description
This issue is a follow-up to @ericcornelissen's [comment](https://github.com/simple-icons/simple-icons/issues/2260#issuecomment-772689951) below:
> which, actually, raises the question of why hyphens are currently also kept when converting from [`titleToFilename`](https://github.com/simple-icons/simple-icons/blob/ac633dc120e4aa28d181f6d02bda2e417110b0be/scripts/utils.js#L6-L26)

With the addition of `slug`s in #4918 we could now, conceivably, remove `-`s from file names, freeing up their use for another purpose in the future*. Up until now they have served a purpose in, potentially, helping avoid potential name clashes - consider, for example, the completely hypothetical brands "S&Y" and "Sandy - but, with the `slug`s, that's now redundant. So _should_ we remove them? It wouldn't be a _huge_  job; by my count there are 23 icons in the current release with a `-` in their file name so I say we may as well.

If we do decide to do it, it could be rolled into #4921

(* One possible use case I'm thinking of is if we decide to generate SVGs with localised `title`s for some purpose, we can use the `-` to append the locale to the filename, e.g. `brandname-en-ie.svg`.)

**Comment by ericcornelissen** [comment]
Thanks for converting this into an issue @PeterShaggyNoble :+1: 

Just to clarify the issue a bit. Do we want to remove all  `-`s from all automatically created slugs, including [those like `-dot-` and `-and-`](https://github.com/simple-icons/simple-icons/blob/e8ba23c0e3a888878cce72741caf817ef279ba55/scripts/utils.js#L9-L14), or just those that appear in the brand name? Here's my take:

Removing hyphens entirely is the best & simplest approach, firstly because automatically created slugs just don't have hyphens which is simpler to reason about. However, we do lose the "elegance" of the automatically inserted `-dot-` and `-and-`. Which is a shame, but is easily counteracted by the introduction of custom slug in #4918 (admittedly the PR needs some changes to support this, but I would be in favor of this), which would not only allow us to keep this format for icons that currently use it but also allows us to omit them in new additions if need-be - the only downside being that reviewers need to keep in mind to check whether or not it makes sense to keep a symbol in the slug or not.


> If we do decide to do it, it could be rolled into #4921

Agreed :+1: 


> (* One possible use case I'm thinking of is if we decide to generate SVGs with localised titles for some purpose, we can use the - to append the locale to the filename, e.g. `brandname-en-ie.svg`.)

Good thinking, with some careful design we may be able to utilize hyphens in filenames to support not only localized SVGs, but also duplicates (e.g. `brandname-dup-title.svg`) and old names (e.g. `oldname.svg`)!

**Comment by PeterShaggyNoble** [comment]
> Removing hyphens entirely is the best & simplest approach

Agreed.

> However, we do lose the "elegance" of the automatically inserted `-dot-` and `-and-`.

Next question, then, is: with the advent of the `slug`, do we start stripping `.`, `&` and `+` out completely? If we're making a special case for them then why not other characters, like `_`. Also, our handling of `+` is inconsistent with the other 2.

> with some careful design we may be able to utilize hyphens in filenames to support not only localized SVGs, but also duplicates

Maybe dropping them into subdirectories of the `icons` directory might be an idea, too, to reduce the potential for name clashes. E.G.:
- `icons/brand.svg`
- `icons/duplicates/brand-duptitle.svg`
- `icons/local/brand-enie.svg`

> and old names
I don't know that that's necessary; I only envisaged old names being useful to help people find icons on the site after a rebrand.

**Comment by ericcornelissen** [comment]
> Next question, then, is: with the advent of the slug, do we start stripping ., & and + out completely? If we're making a special case for them then why not other characters, like _. Also, our handling of + is inconsistent with the other 2.

For context, the reason for the replacement logic of `.`, `&` and `+`  is that they are usually included when you say the brand name as opposed to e.g. `_` and `!`. For example (I believe these are the original brands for the decision on each character):

- `.NET` is "dot-net", not "net"
- `AT&T` is "a-t-and-t", not "a-t-t"
- `Google+` is "googleplus" not "google" (I agree that it should be "google-plus" instead)
- `Yahoo!` is "yahoo", not "yahoo-exclamation-mark"
- `Pop_OS` is (presumably) "popos", not "pop-underscore-os (perhaps we should consider "pop-os", i.e.replacing `_` by `-` though admittedly that might also cause confusion w.r.t.  #4918...)

And so far we have assumed that these rules are general (which is not unreasonable, I think) - hence they're currently automatically replaced. I do think we should keep, e.g., the slug of `.NET` as "dot-net". So, to restate what I tried to communicate in my previous comment:

- Automated replacement of these characters has the advantage of consistency
- Manual replacement of these characters (through the `slug` property in the data file) simplifies what an automatic slugs can be

And even though I like the automation, the "danger" is that, e.g., a brand comes along whose literal name is "dot-net" in which case its automatic slug would already by taken by a brand with, arguably, a different name.

So, here is a new proposal:

1. We keep hyphens in brand names
2. We replace `_` by `-` in brand names
3. Following #4918 we require `_` in custom slugs
4. To keep automation w.r.t. `+`, `.`, and `&` we update their replacement string to use `_` instead of `-` (to prevent collisions)
5. (automated replacement of `+` gets the same treatment as `.` and `&`)

In which case the custom slug still allows us to deviate from the automated replacement of `.`, `+`, and `&` in case it doesn't make sense to replace them by a literal string for a particular brand (as per the start of this comment, I believe that will be less common). The primary downside to this proposal, I believe, is that the slug of a brand like `Pop_OS` will be "popos" or "pop-os" even though "_" seem to be allowed in slugs which may be confusing to some users. My argument against that is that we intend for filenames to phonetically represent the brand name and again (presumably) it is not called "pop-underscore-os".

**Comment by PeterShaggyNoble** [comment]
> (presumably) it is not called "pop-underscore-os"

Strangely, that's exactly how I read it! 😆 Although, that could well be to do with how focussed we've been on that darn `_` in relation to its slug!

**Comment by ericcornelissen** [comment]
> > (presumably) it is not called "pop-underscore-os"
> 
> Strangely, that's exactly how I read it! laughing Although, that could well be to do with how focussed we've been on that darn `_` in relation to its slug!

Admittedly (which is why I used presumable) I'm not familiar with the brand, but "pop-underscore-os" doesn't seem like a very nice name to me :sweat_smile:

**Comment by PeterShaggyNoble** [comment]
If we're rolling this into #4921, do you want to work on it, @ericcornelissen or shall I?

**Comment by ericcornelissen** [comment]
> If we're rolling this into #4921

Not sure if we should put in the same PR (mainly because #4921 can be made not breaking after #4918 is merged). I'd say we hold of on this until at least #4918 is merged. At that point I can look into opening a PR for this :+1:

**Comment by PeterShaggyNoble** [comment]
OK, so I think we're decided that we're going to remove the hyphens but, following on from @ericcornelissen's comment in #5047 we need to decide whether or not we want to keep dots, pluses and ampersands and then, whatever we decide, whether we want to use the `slug` entry to make exceptions where the inclusion or removal of the symbol(s) doesn't make sense.

Firstly, I'm now of the opinion after Eric's comments above that we should keep those 3 symbols, converting them to words as we currently do. However, I _don't_ think we should use the `slug` to make exceptions.

The examples used in #5047 were ".NET" and "del.icio.us" which would either become `dotnet` & `deldoticiodotus` or `net` & `delicious`. In the first case, the inclusion of the "dot"s in `deldoticiodotus` doesn't make sense and the suggestion is that the `slug` entry be used to override that to be `delicious`. In the second case, the "dot"'s exclusion from `net` doesn't make sense and the suggestion is that the `slug` entry be used to override that to be `dotnet`.

Those are 2 very straightforward examples, though, where I think everyone would be in agreement as to how the stylised name should be interpreted and read. But there will be time where the interpretation could be subjective such as "Pop_OS!" above or some people reading a `+` in a brand's name as "plus" and others possibly reading it as "and", to provide 2 examples. And it's for that reason I don't think we should use the `slug` to make exceptions; whatever we decide we should use consistently, regardless of (potentially subjective) interpretation and that the `slug` entry be reserved only to resolve name clashes.

Side note: With regard to the discoverability of "del.icio.us" if it were to be named `deldoticiodotus` and people trying to find it by searching for "Delicious": In that specific case we would be adding "Delicious" as an alias as they do refer to themselves by that name in [some places](https://del.icio.us/help) (`aka` type alias) or because that's what we formerly called the brand here (`old` type alias).

**Comment by ericcornelissen** [comment]
So, to summarize @PeterShaggyNoble, your primary argument is to go with consistency? And you want to stick with the automatic replacement of `+`, `&`, and `.` because 1) that's how we do it now or/and 2) that's occurs more often? Is that somewhat correct?

I would like to push back against that a little bit and argue that we can keep it "consistent" even if we sometimes allow changes to the automatically generated slugs (sounds like a paradox :sweat_smile:). Whether it is sometimes dropping `+`, `&`, or `.` when it usually replaced by a string or the reverse. As you say, for clear-cut cases such as ".NET" and "Del.icio.us" this isn't really a problem as we go with the phonetic name (for completeness, i.e. you say "dot-net" for ".NET", not "net").

As for more subjective cases, I'm not sure it is a problem if we take a position and choose whatever we like (provided we have https://github.com/simple-icons/simple-icons/pull/5002) OR we can always go with the same approach in subjective cases. That said, I'm not sure what a subjective case would be. I feel like the only reason "Pop_OS!" is _subjective_ is because neither of us is familiar with the brand :sweat_smile:

**Comment by PeterShaggyNoble** [comment]
I guess the main crux of my argument against them is to try to keep the number of custom slugs we have as low as possible to minimise the number of times users need to reference [the lookup table](https://github.com/simple-icons/simple-icons/pull/5002), especially those who would be familiar enough with our library that they can easily convert titles to slugs without reference. But I can definitely see & understand your argument in favour of them.

Got the wife to take a run through all the brands we have that contain a dot in their name, using her as a control to see how she would interpret them and her results were, for the most part, wildly different to mine!

Any opinions from any of the other @simple-icons/maintainers? I've included a "before and after" table below for reference showing the result of simply stripping the hyphens out of the slugs of all our current icons.

If we _do_ end up allowing them then I would at least suggest that, on a case by case basis, that if one person disagrees with the `slug` for that icon then we can say that the interpretation _is_ subjective and not allow the `slug`.

Additionally, how do we want to approach this? We can either disallow `-`s for all future contributions, use the `slug` entry for all our existing icons and then remove it in `v5`. Or we can just do the whole lot in one go in `v5`.

| Brand                   | Before                  | After                 |
| ----------------------- | ----------------------- | --------------------- |
| .NET                    | dot-net                 | dotnet                |
| A-Frame                 | a-frame                 | aframe                |
| About.me                | about-dot-me            | aboutdotme            |
| AT&T                    | at-and-t                | atandt                |
| Audio-Technica          | audio-technica          | audiotechnica         |
| B&R Automation          | b-and-rautomation       | bandrautomation       |
| Battle.net              | battle-dot-net          | battledotnet          |
| Blockchain.com          | blockchain-dot-com      | blockchaindotcom      |
| Brand.ai                | brand-dot-ai            | branddotai            |
| Co-op                   | co-op                   | coop                  |
| Conda-Forge             | conda-forge             | condaforge            |
| Counter-Strike          | counter-strike          | counterstrike         |
| D-Wave Systems          | d-wavesystems           | dwavesystems          |
| D3.js                   | d3-dot-js               | d3dotjs               |
| dev.to                  | dev-dot-to              | devdotto              |
| diagrams.net            | diagrams-dot-net        | diagramsdotnet        |
| Digi-Key Electronics    | digi-keyelectronics     | digikeyelectronics    |
| Draugiem.lv             | draugiem-dot-lv         | draugiemdotlv         |
| Eclipse Vert.x          | eclipsevert-dot-x       | eclipsevertdotx       |
| Ember.js                | ember-dot-js            | emberdotjs            |
| F-Droid                 | f-droid                 | fdroid                |
| F-Secure                | f-secure                | fsecure               |
| Ferrari N.V.            | ferrarin-dot-v-dot      | ferrarindotvdot       |
| freedesktop.org         | freedesktop-dot-org     | freedesktopdotorg     |
| GOG.com                 | gog-dot-com             | gogdotcom             |
| GOV.UK                  | gov-dot-uk              | govdotuk              |
| Hotels.com              | hotels-dot-com          | hotelsdotcom          |
| Itch.io                 | itch-dot-io             | itchdotio             |
| Ko-fi                   | ko-fi                   | kofi                  |
| Last.fm                 | last-dot-fm             | lastdotfm             |
| Mail.Ru                 | mail-dot-ru             | maildotru             |
| Material-UI             | material-ui             | materialui            |
| Max-Planck-Gesellschaft | max-planck-gesellschaft | maxplanckgesellschaft |
| Micro.blog              | micro-dot-blog          | microdotblog          |
| New Japan Pro-Wrestling | newjapanpro-wrestling   | newjapanprowrestling  |
| Next.js                 | next-dot-js             | nextdotjs             |
| Node-RED                | node-red                | nodered               |
| Node.js                 | node-dot-js             | nodedotjs             |
| Nuxt.js                 | nuxt-dot-js             | nuxtdotjs             |
| p5.js                   | p5-dot-js               | p5dotjs               |
| Parse.ly                | parse-dot-ly            | parsedotly            |
| Pi-hole                 | pi-hole                 | pihole                |
| Picarto.TV              | picarto-dot-tv          | picartodottv          |
| Player.me               | player-dot-me           | playerdotme           |
| pr.co                   | pr-dot-co               | prdotco               |
| pre-commit              | pre-commit              | precommit             |
| Proto.io                | proto-dot-io            | protodotio            |
| protocols.io            | protocols-dot-io        | protocolsdotio        |
| Redux-Saga              | redux-saga              | reduxsaga             |
| repl.it                 | repl-dot-it             | repldotit             |
| Rolls-Royce             | rolls-royce             | rollsroyce            |
| rollup.js               | rollup-dot-js           | rollupdotjs           |
| Sat.1                   | sat-dot-1               | satdot1               |
| scikit-learn            | scikit-learn            | scikitlearn           |
| Shields.io              | shields-dot-io          | shieldsdotio          |
| Socket.io               | socket-dot-io           | socketdotio           |
| styled-components       | styled-components       | styledcomponents      |
| T-Mobile                | t-mobile                | tmobile               |
| Three.js                | three-dot-js            | threedotjs            |
| TP-Link                 | tp-link                 | tplink                |
| Trip.com                | trip-dot-com            | tripdotcom            |
| Vue.js                  | vue-dot-js              | vuedotjs              |
| Warner Bros.            | warnerbros-dot          | warnerbrosdot         |
| webcomponents.org       | webcomponents-dot-org   | webcomponentsdotorg   |
| Weights & Biases        | weights-and-biases      | weightsandbiases      |
| write.as                | write-dot-as            | writedotas            |
| X-Pack                  | x-pack                  | xpack                 |
| X.Org                   | x-dot-org               | xdotorg               |
| YourTravel.TV           | yourtravel-dot-tv       | yourtraveldottv       |
| Z-Wave                  | z-wave                  | zwave                 |

**Comment by ericcornelissen** [comment]
> I guess the main crux of my argument against them is to try to keep the number of custom slugs we have as low as possible to minimise the number of times users need to reference the lookup table, especially those who would be familiar enough with our library that they can easily convert titles to slugs without reference.

Thanks for the clarification, that makes sense as well.


> Additionally, how do we want to approach this? We can either disallow -s for all future contributions, use the slug entry for all our existing icons and then remove it in v5. Or we can just do the whole lot in one go in v5.

I think that if we can implement in a backwards compatible way without too much effort, and we have the resources to do so, we should do it is early as possible - provided we all agree on the decision of course.

**Comment by PeterShaggyNoble** [comment]
> I think that if we can implement in a backwards compatible way

I've made a start on disallowing `-`s in filenames for all future icons while adding a custom slug for each existing file with a `-` in its name. This will help minimise the number of files we need to rename in v5. Everything else we're discussing wouldn't be implemented until v5 anyway so we still have a bit of time to decide.

**Comment by PeterShaggyNoble** [comment]
I've started into the removal of hyphens for v5 and will have a draft PR ready for tomorrow.
