### ISSUE TITLE
Expose license data in NPM package

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons#5067]
### Kind of issue 
  - [x] Improvement
  - [ ] Bug
  - [ ] Other, namely:

### This issue concerns 
  - [x] The NPM Package
  - [ ] The Packagist Package

### Description

Following #4900 and with #4945 merged, this issue is to discuss if and how [the `"license"` field](https://github.com/simple-icons/simple-icons/blob/39269e7d3947c1280a96d4e6b996a746f3ff49f4/.jsonschema.json#L32-L143) should be exposed by the NPM package (beyond it being present in the `_data/simple-icons.json` file)

**Comment by PeterShaggyNoble** [comment]
I think this is something we should add to `index.js` for each icon so that it's exposed through `simpleIcons.get()` giving people access to licensing info for each icon they use to do with as the please.

We could include it exactly as we do in `simple_icons.json` and document how to use the `type` to look up the license name & URL through a third party. That, however, would create more work and another possible dependency for our users which may deter them from using it at all when we should probably be making it as easy as possible. So I would suggest we perform that look up ourselves when the package is being built and add `name` and `url` entries to each license entry in `index.js`.

**Comment by ericcornelissen** [comment]
> I think this is something we should add to index.js for each icon so that it's exposed through simpleIcons.get() giving people access to licensing info for each icon they use to do with as the please.

If we add it there, I think we should also add it to the tree-shakeable `[slug].js` files.


> We could include it exactly as we do in `simple_icons.json` and document how to use the `type` to look up the license name & URL through a third party. That, however, would create more work and another possible dependency for our users which may deter them from using it at all when we should probably be making it as easy as possible. So I would suggest we perform that look up ourselves when the package is being built and add `name` and `url` entries to each license entry in `index.js`.

So, to summarize, your suggestion is to add a link to the license text if the license type is one of [the SPDX license IDs](https://github.com/simple-icons/simple-icons/blob/1df43dd50bd38d703f46b9e47ee5137b06b92918/.jsonschema.json#L58-L132) such that if an icon's `license` field is not `undefined` it is always an object with a `type` and `url`? I'd agree with that :+1:

**Comment by ericcornelissen** [comment]
> So I would suggest we perform that look up ourselves when the package is being built and add name and url entries to each license entry in index.js.

Working on https://github.com/simple-icons/simple-icons-website/issues/47 now, definitely agree with this point :smile:
