### ISSUE TITLE
Unify implicit/explicit closepath commands

### ISSUE THREAD

**Issue by mondeja** [simple-icons/simple-icons#5070]
Currently in simple-icons, there are 107 icons that ends without a [closepath](https://www.w3.org/TR/SVG/paths.html#PathDataClosePathCommand) command (`z` or `Z`). As you can see in [this comment in StackOverflow](https://stackoverflow.com/a/10213649/9167585), as [SVG specification points](https://www.w3.org/TR/SVG/painting.html#SpecifyingFillPaint), if a path ends without a closepath command, will be treated as if a closepath command is added filling its geometry.

So, in order to unify all icon paths, we can:

- Force addition of explicit `z` or `Z` command at the end of the paths (explicit notation).
- Force removal of `z` or `Z` command at the end (smaller file size).

And this could be done in two ways:

- Add `[Zz]$` regex check to tests or linting process (the user must edit it manually).
- Configure some way of do this automatically, so as not to worry the user about these little optimizations, for example, doing one commit before release. I'm thinking also in the lint rule `negative-zeros`, that could be fixed in this way. There is a precedent of this kind of commit before release in #5002.

**Comment by ericcornelissen** [comment]
This seems more related to https://github.com/simple-icons/simple-icons/issues/2380 than https://github.com/simple-icons/simple-icons/pull/5002. Note that it is easy to commit changes in the context of https://github.com/simple-icons/simple-icons/pull/5002 because we are running the workflow on a schedule. On the other hand, https://github.com/simple-icons/simple-icons/issues/2380 (and by extension this suggestion) need to run in the context of pull requests from forks.

**Comment by mondeja** [comment]
Ahm, so the commits would be directly to the forked branches... :thinking: But could that not be a bit confusing for contributors? They will must pull if the changes are triggered, right?

**Comment by ericcornelissen** [comment]
I agree that it could be confusing, but I think it is possible to communicate this to the contributor (e.g. by commenting on the Pull Request when it happens) or by only doing it when triggered by one of the maintainers.

Furthermore, If I understand you correctly, I would be very wary of merging in "invalid" PRs under the assumption that problems will be fixed automatically on `develop`.

In any case, if this issue is indeed in the scope of #2380, I suggest we discuss the details about how we approach automated fixes there and leave this issue for discussion on closepath commands :slightly_smiling_face:

**Comment by mondeja** [comment]
> I would be very wary of merging in "invalid" PRs under the assumption that problems will be fixed automatically on develop.

Technically, are not "invalid" because these changes (`negative-zeros` and removal of `z`/`Z` at end) would be only file size optimizations, since the SVG spec allows negative zeros and treats missing of closepath at ends as implicit closepaths.

**Comment by ericcornelissen** [comment]
@mondeja, should we add this as a check for the linter or close this issue without adding it?

**Comment by mondeja** [comment]
I've opened a PR to add this as a check.
