### ISSUE TITLE
Request: Ask Ubuntu icon

### ISSUE THREAD

**Issue by alagos** [simple-icons/simple-icons#5095]
**Brand Name:** Ask Ubuntu
**Website:** https://askubuntu.com/
**Alexa rank:** [295k](https://www.alexa.com/siteinfo/askubuntu.com)

**Official resources for icon and color:**
I couldn't find an official media kit, but in the landing page source code there's [this svg](https://cdn.sstatic.net/Sites/askubuntu/Img/logo.svg) that could be easily cropped to fit only the "Ask" logo.
About the official color, I'm not really sure, as I've found the following versions:
- [`#dd4c00`](https://cdn.sstatic.net/Sites/askubuntu/Img/apple-touch-icon.png) ![](https://cdn.sstatic.net/Sites/askubuntu/Img/apple-touch-icon.png)
- [`#f47323`](https://cdn.sstatic.net/Sites/askubuntu/Img/apple-touch-icon@2.png) ![](https://cdn.sstatic.net/Sites/askubuntu/Img/apple-touch-icon@2.png)

- `#dc461d` in the [logo's topbar](https://askubuntu.com)

I could work on this, but I'd like opinions about what you guys do for these cases where doesn't seem to be defined an official color.

**Comment by service-paradis** [comment]
I would, personally, expect `#DC461D` to be the brand color. From the stylesheet, it is the primary color. It is used for a lot of element (ex. header, link color, ...).
For the icon, I would expect only the speech bubble with `ask` written in it:
![image](https://user-images.githubusercontent.com/12817388/108786300-4a038200-7541-11eb-8739-b6d433c4a45d.png)

Here are the trademark / Leal guideline:
- https://stackoverflow.com/legal/trademark-guidance

We can find some official logos (raster unfortunately) running the API at https://api.stackexchange.com/docs/sites#filter=default&run=true:
```json
     "high_resolution_icon_url": "https://cdn.sstatic.net/Sites/askubuntu/Img/apple-touch-icon@2.png",
      "favicon_url": "https://cdn.sstatic.net/Sites/askubuntu/Img/favicon.ico",
      "icon_url": "https://cdn.sstatic.net/Sites/askubuntu/Img/apple-touch-icon.png",
      "logo_url": "https://cdn.sstatic.net/Sites/askubuntu/Img/logo.png",
```

I also found the origin of the logo (but not really that helping):
- https://meta.stackexchange.com/questions/359130/what-does-the-logo-of-each-stack-exchange-site-represent/359131#359131
- https://meta.askubuntu.com/questions/1968/why-are-the-logos-from-some-ubuntu-related-sites-and-askubuntu-so-similar/1969#1969
- https://meta.askubuntu.com/questions/5444/is-ask-ubuntu-official-ubuntu/438#438


@PeterShaggyNoble This kind of question could probably asked in the [meta part of AskUbuntu](https://meta.askubuntu.com/).

Some questions about having official resources for logos have already been asked (without real good answers unfortunately):
- https://meta.stackexchange.com/questions/100718/what-stock-graphics-are-available-for-promoting-a-site
- https://meta.stackexchange.com/questions/329978/official-resource-to-download-stack-exchange-site-logos/329981
- https://meta.stackexchange.com/questions/244835/why-are-only-five-different-logos-available-on-the-about-logos-stack-exchange
- https://meta.stackexchange.com/questions/117766/where-can-i-find-image-files-of-stack-exchange-sites-logos/117774
- https://meta.stackexchange.com/questions/55001/where-can-i-get-a-vector-stack-overflow-logo/55036

I finally found [this thread](https://stackapps.com/questions/347/svg-versions-of-the-logos) that contains a SVG file for the ASkUbuntu icon. Unfortunately, looks like there is a problem with the font 🤦‍♂️ 

Sorry for this too long message! 😅 
Since there are no clear answer about the official brand color, do you want me to ask it on https://meta.askubuntu.com/?

**Comment by alagos** [comment]
I've just [asked on meta](https://meta.askubuntu.com/q/19534/41141), mostly linking to this issue, so hopefully we could get some official input soon.

**Comment by PeterShaggyNoble** [comment]
Woah! Thanks for the extensive research, @service-paradis 👏🏻 Although, I don't know how I managed to ping you instead of @alagos in my first comment! 😆

Thanks to you, too, @alagos for opening that question on Meta. As the consensus in the comments seems to be that the colours _should_ be Ubuntu's then I think `#dc461d` is the best choice for us as it is closest to Ubuntu's primary colours.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself?
