### ISSUE TITLE
Require brands of the same name to be sorted by slug

### ISSUE THREAD

**Issue by PeterShaggyNoble** [simple-icons/simple-icons#5098]
Currently [Handshake (Protocol) is listed before Handshake](https://github.com/simple-icons/simple-icons/blob/f464deebc2e6ecfe8da62fac3399a25141cb56f9/_data/simple-icons.json#L3432-L3442) but [Hive (Blockchain) is listed after Hive](https://github.com/simple-icons/simple-icons/blob/f464deebc2e6ecfe8da62fac3399a25141cb56f9/_data/simple-icons.json#L3558-L3568) in `simple-icons.json`.

For consistency, I suggest that we add a step to our linting process to ensure that entries with the same `title` are sorted by their `slug` with the one that doesn't have a `slug` coming first and the remainder sorted lexicographically.

**Comment by PeterShaggyNoble** [comment]
It looks like replacing [the `collector` function](https://github.com/simple-icons/simple-icons/blob/develop/scripts/lint.js#L25-L33) in `scripts/lint.js` with something like the below _should_ do the trick but I don't have a setup to allow me to test it properly. We may also need to add the `slug` to the log in some way when applicable as the `title` alone won't be enough to tell people exactly which entry is out of order.

In my manual tests, even without the changes below, I was getting a false positive on ".NET" when it's being `localCompare`d to "42" for some reason. And it looks like there's a related problem on the new website, with "42" being listed first instead of ".NET".

```
const collector = (invalidEntries, icon, index, array) => {
  if (index > 0) {
    const prev = array[index - 1];
    const compare = icon.title.localeCompare(prev.title);
    if (compare < 0) {
      invalidEntries.push(icon);
    }else if(compare === 0){
        if(prev.slug){
            if(!icon.slug){
                invalidEntries.push(icon);
            }else if(icon.slug.localeCompare(prev.slug) < 0){
                invalidEntries.push(icon);
            }
        }
    }
  }
  return invalidEntries;
};
```

**Comment by ericcornelissen** [comment]
> In my manual tests, even without the changes below, I was getting a false positive on ".NET" when it's being localCompared to "42" for some reason.

Not sure if I follow exactly what you're encountering but my guess is that it is due to our use of `localeCompare` without specifying the locale explicitly in which case it's behaviour depends on the implementation and may be either undefined entirely, always the same locale, or the locale from your device. So, even if this is not the problem you're having, we should probably fix that.

 
> And it looks like there's a related problem on the new website, with "42" being listed first instead of ".NET".

On the website it seems that [this line](https://github.com/simple-icons/simple-icons-website/blob/45309e58a3a2075dc869262d1983482d976104d6/webpack.config.js#L13) changes the ordering :thinking: And that seems to be because enumerating the keys of the `simpleIcons` object uses that ordering. Not sure what we can do about that, other than somehow forcing the ordering of the `_data/simple-icons.json` file.
