### ISSUE TITLE
Icon for Classic ASP programmers

### ISSUE THREAD

**Issue by andersoncampos** [simple-icons/simple-icons#5125]
**Brand Name:** Microsoft Classic ASP 3.0
**Website:** www.microsoft.com
**Alexa rank:**
  

**Official resources for icon and color:**
  

https://images.lejusteweb.com/logo-asp-classic-1.svg
https://en.wikipedia.org/wiki/Active_Server_Pages

**Comment by fbernhart** [comment]
Hi @andersoncampos, welcome to Simple Icons.

I'm not familiar at all with ASP, but quoting [Wikipedia](https://en.wikipedia.org/wiki/Active_Server_Pages) it seems like ASP hasn't been maintained anymore since 2002:

> It was first released in December 1996, before being superseded in January 2002 by ASP.NET.

Which leads me to assume, that ASP isn't popular enough to be added to Simple Icons. Or can you prove otherwise? Normally we're using the Alexa rank to determinate the popularity of a brand, but as ASP doesn't even seem to have a website, we can't use that.

Even if it would be popular enough, I wasn't able to find an official ASP logo. The one you've linked doesn't seem to be an official one.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @andersoncampos - as an ASP guy, I appreciate this one 👍🏻

However, I would share some of @fbernhart's concerns regarding its popularity. I do know that there are plenty of legacy systems still running ASP, which is why MS haven't killed it off completely, but that alone, for me wouldn't be enough. A [Google Trends](https://trends.google.com/trends/) comparison with an existing language we have in our collection would help but picking the right language to make it a _fair_ comparison is a bit tricky.

I also, but I may be very wrong about this, don't remember that logo you linked being the official logo or even it _having_ an official logo. The only place I can ever remember seeing that logo used is on the cover of a book from the late 90s/early 2000s and on 3rd party tutorial sites.

**Comment by service-paradis** [comment]
Closing this one for now since it appears to be out of scope and without any activity since march. Feel free to reopen this issue @andersoncampos if you find a way to assess the popularity that will meet our requirements.
