### ISSUE TITLE
Request: Eclipse Che icon

### ISSUE THREAD

**Issue by gastaldi** [simple-icons/simple-icons#5161]
**Brand Name:** Eclipse Che
**Website:** https://www.eclipse.org/che/
**Alexa rank:** 10,028
  

**Official resources for icon and color:** https://www.eclipse.org/che/

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @gastaldi.

Note that the Alexa rank is for the entire Eclipse domain, rather than the Che page so we can't use that to assess its popularity. It does, though, have [~6.3k stars on GH](https://github.com/eclipse/che/) which means it _is_ within our scope.

Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and take this one on yourself using [the SVG](https://www.eclipse.org/che/images/logo-eclipseche.svg) in their website's header?

**Comment by gastaldi** [comment]
Thanks for the quick reply @PeterShaggyNoble.  By following the guidelines, I managed to reduce the image to the file below, but I am struggling to make it monochromatic, as leaving it all black will not look nice: 

[eclipse-che.svg.zip](https://github.com/simple-icons/simple-icons/files/6078299/eclipse-che.svg.zip)

**Comment by gastaldi** [comment]
I think I did it: 

```svg
<svg role="img" xmlns="http://www.w3.org/2000/svg" version="1.1" x="0" y="0" viewBox="0 0 24 24" xml:space="preserve"><title>Eclipse Che icon</title><path d="M12 0L0 6.02v7.451l12-5.978 4.55 2.253L24 6.02zM0 10.527v7.45L12 24l12-6.021v-7.451l-12 5.978z" fill="#000" stroke-width=".465"/></svg>
```

**Comment by gastaldi** [comment]
There you go: https://github.com/simple-icons/simple-icons/pull/5163
