### ISSUE TITLE
kit.co

### ISSUE THREAD

**Issue by kishjogia** [simple-icons/simple-icons#5204]
Brand Name: Kit
Website: https://kit.co/
Alexa rank: 7,936

Official resources for icon and color: support@kit.co

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @kishjogia.

There are some brand guidelines available [here](https://help.kit.co/en/articles/1246030-what-are-your-brand-guidelines) which allow us to use the boxed "K" instead of the full wordmark. I haven't found a vector version of it yet, though, but it _should_ be straightforward enough to recreate.

**Comment by adamrusted** [comment]
Going through issues, there's now an SVG on their homepage which includes the `K` used in the rounded rectangle. With a little creative license, you could recreate their `K in rounded rectangle` icon pretty easily (though for some reason, I'm unable to. Affinity being weird)
