### ISSUE TITLE
Request: ABC

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5238]
**Name:** ABC (abbreviated as American Broadcasting Company)
**Website:** https://www.abc.com/
**Color:** `#000000`
**Official resources for icon and color:** see below on Google: https://www.google.com/search?q=ABC+logo&tbm=isch

**Comment by fbernhart** [comment]
@diegobot1977 Thanks for this request (and all the others).

Just two quick notes:
It would be helpful if you could include the Alexa rank of the brands into your requests. Basically it's just visiting the site https://www.alexa.com/siteinfo, entering the website you want to get the Alexa rank for and then adding this number to your icon request. For abc.com it would be 6,620, according to https://www.alexa.com/siteinfo/abc.com.

"Official resources for icon and color" is for linking to an **official** website of the brand, where the logo can be found. It's supposed to be a start off point to work on the icon. So instead of linking to Google, you should (in this case) link to the icon that can be found in the header of https://abc.com, which is this file --> https://assets.cdn.watchdisneyfe.com/delta/assets/abc/abc@2x.png

Ideally it should be a SVG file. But if there is no SVG file (or any other vectorized filetype), it can as well be a PNG, JPG etc. file.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @diegobot1977. However, as ABC is a Disney company, we, unfortunately, will not be able to add this one. See #2309 for more details.
