### ISSUE TITLE
Request: Gremlin Icon

### ISSUE THREAD

**Issue by Sugam1111** [simple-icons/simple-icons#5283]
**Brand Name:** Apache TinkerPop Gremlin
**Website:** https://tinkerpop.apache.org/
**Alexa rank:** [2,214](https://www.alexa.com/siteinfo/apache.org) (subdomain of apache)
  

**Official resources for icon and color:**
https://tinkerpop.apache.org/docs/current/images/gremlin-logo.png
https://tinkerpop.apache.org/docs/current/images/gremlin-running.png

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Sugam1111.

As you point out the Alexa rank is for Apache itself so we can't go by that. So the next metric we look at is GitHub stars, where we have a cut-off of 5000. Unfortunately, Tinkerpop as a whole only has [~1.3k stars](https://github.com/apache/tinkerpop) and, with Gremlin just being a part of it, it looks like this one is going to be beyond our scope.

Before we close the issue out, though, is their another metric we could use to assess the popularity of this one? A Google Trends comparison with a similar brand that's already in our collection, maybe.

**Comment by Sugam1111** [comment]
Cypher query language (in Neo4j) is the more popular alternative to Gremlin query language which I use on AWS Neptune. 
Here is a trends comparison https://trends.google.com/trends/explore?q=%2Fm%2F0hhr8wc,%2Fm%2F0_frrg4

**Comment by PeterShaggyNoble** [comment]
Thanks for the reply, @Sugam1111. Unfortunately, in order to use a comparison with another brand to measure popularity, we would first need to assess the popularity of that other brand, or have done so already when adding it to our library. Is their another brand, already in our library, that would be related that we can compare against? Or one not in our library that we can easily assess the popularity, either by Alexa rank or GitHub stars?

**Comment by service-paradis** [comment]
Closing this one for now since it appears to be out of scope and without any activity since april. Feel free to reopen this issue @Sugam1111 if you find a way to assess the popularity that will meet our requirements.
