### ISSUE TITLE
Request: Scilab Icon

### ISSUE THREAD

**Issue by shubhadeepmandal394** [simple-icons/simple-icons#5429]
**Brand Name:**  Scilab
**Website:** https://www.scilab.org/
**Alexa rank:** 152,291
  

**Official resources for icon and color:** 
https://www.scilab.org/sites/all/themes/scilab/images/scilab-logo.png

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @shubhadeepmandal394.

The branding on this one seems to be all over the place; I've found 4 difference logos so far:
1. The one in the header of their website
2. A similar one without the rectangle on [their Facebook page](https://www.facebook.com/Scilab/), among other places
3. A sideways "S" in a circle on [their LinkedIn page](https://www.linkedin.com/company/scilabenterprises/about/)
4. Some sort of ... bird? ... waveform? ... 🤷🏻‍♂️ ... in [their GitHub org](https://github.com/scilab)

Of the 4, I'm guessing the first is probably the most correct but I've yet to find a vector version of it anywhere but there are [over 350 SVGs](https://github.com/search?l=SVG&q=org%3Ascilab+svg&type=Code) in their GH org so that may hopefully yield something.

**Comment by adamrusted** [comment]
Found [this icon](https://gitlab.com/scilab/scilab/-/blob/fe880afd368833c88eb710f4813a1113b3069626/scilab/modules/gui/images/icons/scilabicon.svg) in their GitLab files, added only a month ago. Could be a good starting point?
