### ISSUE TITLE
Request: Chaturbate

### ISSUE THREAD

**Issue by SpedNSFW** [simple-icons/simple-icons#5438]
**Brand Name:** Chaturbate
**Website:** https://chaturbate.com
**Alexa rank:** [49](https://www.alexa.com/siteinfo/chaturbate.com)
  

**Official resources for icon and color:**
  
[Official logo](https://static-assets.highwebmedia.com/images/logo.svg).
I have removed all but the C in the logo as that's what they use as their favicon and it's more appropriate for an icon.
GitHub does not allow for .SVG files to be uploaded so I've zipped the file:
[chaturbate - c.zip](https://github.com/simple-icons/simple-icons/files/6293086/chaturbate.-.c.zip)

I wasn't sure if adult brands were allowed but OnlyFans is up and there's nothing in the rules prohibiting anything adult related.

**Comment by PeterShaggyNoble** [comment]
Thanks for the requests, @SpedNSFW and for getting the debate rolling on adult sites & services. As you can see in #3588, we did have an initial discussion when OnlyFans was requested where it was decided that brands that _allow_ adult content were within our scope provided:
1. They are not _solely_ an adult service, and,
2. They don't promote themselves as an adult service.

This was actually a precedent set, perhaps unintentionally, with the addition of Tumblr to our collection as that was done at a time before they changed their policies on adult material.

We did not, however, go too in depth into nor make a decision on brands that are _exclusively_ adult oriented as it was a broader discussion we wanted to have separately, which we can now do here. I myself have thought on this a few times since the addition of OnlyFans and have come up with a number of arguments against us allowing them. I'll try to get them written up later today but, after a dose of insomnia last night, it may be tomorrow before I can do so coherently!

Remember: if you want to get involved in the discussion here, I don't think it's our place to play moral police here so, whichever side you want to argue for, please do so objectively.

**Comment by SpedNSFW** [comment]
I'd love to hear your arguments as these are companies just like any other and it would be unfair to treat them any differently because of the type of content they host.

**Comment by SpedNSFW** [comment]
@adamrusted Do you have any reason why they shouldn't be included other than the fact that they host explicit content? They're technically just like OnlyFans. Users on those sites aren't obligated to post explicit content. There's plenty of creators using those platforms to engage in conversation and provide content with their fans. It might not be PG-13 but it's not XXX either.
Sure the sites are targeted towards a XXX userbase but at the end of the day, it's up to the users.

Also, OnlyFans is owned by MyFreeCams. A competitor to Chaturbate that I hadn't gotten around to making a request for. It's arguably more "wholesome" than Chaturbate as a section of it's site is non-explicit only, but it's still a camsite that you're now attached to by association.

**Comment by adamrusted** [comment]
@SpedNSFW my reasoning for not accepting them would be because they are primarily targeted at the hosting and sharing of adult content. The fact that users post explicit content isn't my issue (see DeviantArt for example which while it contains a lot of adult content, is primarily a platform for artists to share their work).

My point was that I don't think we as a project should explicitly include brands whose primary purpose and marketing angle is the distribution of adult content.

Onlyfans was accepted on the fact it's marketed more as an "exclusive community" site, as opposed to a adult brand, though given its reputation it'd fall under scrutiny if/when we make the scope suggestions suggested above by @PeterShaggyNoble legitimate, which is why I commented at the time that it can be removed in of v5 in May if necessary.

**Comment by SpedNSFW** [comment]
> My point was that I don't think we as a project should explicitly include brands whose primary purpose and marketing angle is the distribution of adult content.

@adamrusted I should have been more clear in my initial question. Why don't you think simple-icons should include explicit brands? They're legitimate brands. They pay taxes (I hope). They have as much right to exist as any other company. Is it a matter of morals? So far the only reason I've seen against adult brands is that they contain adult content and to that I say so what. What site doesn't. Hosting adult content is not a valid reason for exclusion in my opinion and it's a step backwards. Society should be more accepting of adult content instead of shunning it.

**Comment by fbernhart** [comment]
I'm agreeing with @SpedNSFW here.

Morally I don't see any reason not to add brands that explicitly contain adult content.

For me it's as well just a brand like any other.

**Comment by ericcornelissen** [comment]
Though I personally also agree that there is no real reason not to include a brand like Chaturbate (i.e. brand primarily focused on adult content), I do think we should not include it. At least not in the main project. My reasoning being twofold:

- Some of our users/us as maintainers are almost definitely not going to be happy with the inclusion of these brands, whatever their reasons I do think we should take that into account.
- Though "our" primary goal is to _just provide high quality SVGs of brand logos_, we do know of some users that use our collection to find new brands/products. For those users it may be very inconvenient to stumble upon brands like these and look them up (e.g. if they're at work or in public).

I think these two reasons are enough to exclude brands explicitly about adult content from this main project. That said, we _could_ support a separate project that is explicitly about providing icons for brands about adult content. The project would be nearly identical to this one except that it is clear from its name that it is about adult content.

**Comment by SpedNSFW** [comment]
> * Some of our users/us as maintainers are almost definitely not going to be happy with the inclusion of these brands, whatever their reasons I do think we should take that into account.

Why should it be taken into account? We wouldn't be forcing NSFW content down their throats. The brands would still have to meet the same criteria as every other brand. If they're not happy about adult content, they shouldn't be on the internet in the first place. If they think excluding these brands is going to stop icons from showing up, they're wrong. If someone wants to use an icon, they'll find one and use it so why not just skip the drama and just include it.

> * Though "our" primary goal is to _just provide high quality SVGs of brand logos_, we do know of some users that use our collection to find new brands/products. For those users it may be very inconvenient to stumble upon brands like these and look them up (e.g. if they're at work or in public).

Putting aside the possibility for a separate project for a moment, wouldn't it be simpler to add a "NSFW" flag on these and then either have a toggle to show/hide NSFW brands (hidden by default), or add a NSFW warning to the item... or both?

> I think these two reasons are enough to exclude brands explicitly about adult content from this main project. That said, we _could_ support a separate project that is explicitly about providing icons for brands about adult content. The project would be nearly identical to this one except that it is clear from its name that it is about adult content.

I'm not wholly apposed to a separate project, however I'd much rather some flag as I suggested above.

**Comment by ericcornelissen** [comment]
> Why should it be taken into account? We wouldn't be forcing NSFW content down their throats. The brands would still have to meet the same criteria as every other brand. If they're not happy about adult content, they shouldn't be on the internet in the first place. If they think excluding these brands is going to stop icons from showing up, they're wrong. If someone wants to use an icon, they'll find one and use it so why not just skip the drama and just include it.

I'm sorry but I don't find this argument very convincing. No, we are indeed not "forcing it down their throats" and yes the brand still need to meet the same criteria. That said, it is really not that hard to be on the internet and encounter next to no adult content (depending on your definition). And of course these icons are going to show up, that's not the concern. The concern is that it is going to show up (arguably) unnecessarily in place where those people are.

I very much get the sentiment that adult content "is not a big deal" and "people should just accept that there is NSFW stuff on the internet". However, at least in this day and age there are people that care deeply about this and don't like NSFW stuff, even in a "trivial" project like Simple Icons. I would also desperately want "politics to be separate from this project" but unfortunately that is just not possible.

I believe a separate project for adult content is a solution that provides a place for NSFW content while being sympathetic to those that dislike NSFW content (either entirely or just on the grounds that there is a time and a place for NSFW but not always and everywhere).


> Putting aside the possibility for a separate project for a moment, wouldn't it be simpler to add a "NSFW" flag on these and then either have a toggle to show/hide NSFW brands (hidden by default), or add a NSFW warning to the item... or both?
>
> > I think these two reasons are enough to exclude brands explicitly about adult content from this main project. That said, we could support a separate project that is explicitly about providing icons for brands about adult content. The project would be nearly identical to this one except that it is clear from its name that it is about adult content.
>
> I'm not wholly apposed to a separate project, however I'd much rather some flag as I suggested above.

While I agree that it is a suitable solution, it doesn't seem "drastic" enough for this "problem" for some people. If you're thinking just in the context of the Simple Icons website, this would be a suitable solution. However, in the context of the packages I don't think this is enough as you can just iterate over all icons and miss the "NSFW" field. At best we could introduce such a data point with a major release, but even than I think it is too easy to miss.



---


Additionally, while I'm pretty sure "providing the icon of legal NSFW services" is outside the scope of [What is not allowed by GitHub's community guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines#what-is-not-allowed), we might be better of asking for permission from GitHub explicitly if we decide to move forward with this request.

**Comment by SpedNSFW** [comment]
> While I agree that it is a suitable solution, it doesn't seem "drastic" enough for this "problem" for some people. If you're thinking just in the context of the Simple Icons website, this would be a suitable solution. However, in the context of the packages I don't think this is enough as you can just iterate over all icons and miss the "NSFW" field. At best we could introduce such a data point with a major release, but even than I think it is too easy to miss.

Okay, not going to debate in this comment but I have a question/request/suggestion... I guess it depends on the answer. I am okay with NSFW icons being in a separate package, perhaps as `simple-icons/nsfw` or something of the sort, however, would these icons still be present on the website interface? Still with a toggle/warning which would be easier given they'd be in a different package. It doesn't make sense to have a separate page just for NSFW icons when a toggle would suffice.

If they are all together on the web interface but in separate interface, I'm all for it. I'd still prefer them in this package and I don't think my comments here should end this discussion, but I think it's the route we should take if we can't agree to include them here.

> Additionally, while I'm pretty sure "providing the icon of legal NSFW services" is outside the scope of [What is not allowed by GitHub's community guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines#what-is-not-allowed), we might be better of asking for permission from GitHub explicitly if we decide to move forward with this request.

GitHub allows for a lot of adult content. I can't imagine they'd draw the line at monochromatic icons that don't include any explicit content themselves.

**Comment by ericcornelissen** [comment]
> > While I agree that it is a suitable solution, it doesn't seem "drastic" enough for this "problem" for some people. If you're thinking just in the context of the Simple Icons website, this would be a suitable solution. However, in the context of the packages I don't think this is enough as you can just iterate over all icons and miss the "NSFW" field. At best we could introduce such a data point with a major release, but even than I think it is too easy to miss.
> 
> Okay, not going to debate in this comment but I have a question/request/suggestion... I guess it depends on the answer. I am okay with NSFW icons being in a separate package, perhaps as `simple-icons/nsfw` or something of the sort, however, would these icons still be present on the website interface? Still with a toggle/warning which would be easier given they'd be in a different package. It doesn't make sense to have a separate page just for NSFW icons when a toggle would suffice.

Not signing off on it here, but I'm pretty sure they can be on the website with either a warning, toggle, or separate page.


> If they are all together on the web interface but in separate interface, I'm all for it. I'd still prefer them in this package and I don't think my comments here should end this discussion, but I think it's the route we should take if we can't agree to include them here.

Of course the discussion can continue, and if we decide NSFW icons can be in the main project it should be pretty easy to bring all the SVGs and data over provided the NSFW project follows the same standards.



> > Additionally, while I'm pretty sure "providing the icon of legal NSFW services" is outside the scope of [What is not allowed by GitHub's community guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines#what-is-not-allowed), we might be better of asking for permission from GitHub explicitly if we decide to move forward with this request.
> 
> GitHub allows for a lot of adult content. I can't imagine they'd draw the line at monochromatic icons that don't include any explicit content themselves.

My bad, I read the section on NSFW content incorrectly, you are correct.

**Comment by runxel** [comment]
Wasn't one of the concerns of @PeterShaggyNoble originally that we could be blocked by "anti virus", firewalls and therelike, since this could trigger some block lists?

**Comment by SpedNSFW** [comment]
> Wasn't one of the concerns of @PeterShaggyNoble originally that we could be blocked by "anti virus", firewalls and therelike, since this could trigger some block lists?

Any anti-virus that would trigger on the type of content in this repo is not worth downloading. Firewalls don't work like that either.

**Comment by ericcornelissen** [comment]
> Any anti-virus that would trigger on the type of content in this repo is not worth downloading.

Maybe not for you, but for others it might be worth the trade-of.


> Firewalls don't work like that either.

URL filtering could theoretically apply, not an expert but I would expect that to fall under the umbrella of firewall features. Though I agree that URL filtering would only affect NSFW-related icons and not others.

**Comment by PeterShaggyNoble** [comment]
Finally making it to back to this one after a long day getting caught up on notifications yesterday! Bear with me here, this is a long one (even by my standards!) and could get a little disjointed.

## Preamble
Firstly, let me reiterate that this is not about playing moral police, passing judgement on brands based on our own personal opinions & principles. If that were the case then there would be many, many other brands & companies that wouldn't be included in our collection because we all have some issue with the morals, ethics & business practices of some companies. But it's not our place as maintainers to let those opinions influence our work on this project in facilitating the needs & requirements of our users.

Secondly, a few rebuttals on a few things that have already been raised here.
> Society should be more accepting of adult content instead of shunning it.

That's as maybe but that's strictly an opinion and whether any or all of us agree with it shouldn't factor in here. The fact is, though, it currently isn't and even if/when a change comes about that lifts the taboos & stigmas surrounding adult brands throughout society, there will still be many individuals whose own moral compasses find it objectionable. To me the addition of adult brands to Simple Icons should be a _result_ of that societal change but it's not going to _instigate_ it, nor any other social, polictical or global change.

> If they're not happy about adult content, they shouldn't be on the internet in the first place.
> What site doesn't [host adult content?]

Very, very many. However (and I'll touch in more detail on why this is an issue later), on those sites that do allow it without it being their primary purpose you have to actively seek that content out, whereas on sites where it is their primary purpose it's right there as soon as you enter the site. For example, I was able to research the branding and guidelines for OnlyFans perfectly safely, without coming across any adult content. A bad example, maybe, because it's all hidden behind a paywall but the same is true of other sites that have been mentioned in this conversation (e.g., pre-crackdown Tumblr, DeviantArt) where it's freely accessible to everyone.

-----
As to my arguments against us allowing icons for brands that deal exclusively in adult content (in ascending order of strength as I see them):

## 1. Firewalls and content filters & monitors
This has already been touched on above so I won't dwell on it other than to say it _is_ something we have to take into consideration. Particularly for people who use our icons in professional projects who may be behind a stringent corporate firewall/filter/monitor.

## 2. Legalities
Many countries, regardless of their laws regarding adult content & services, do have laws regarding its promotion and, depending on the wording of those laws, us including adult brands could see us in contravention of those laws. This isn't just true of the adult industry in case you think I'm singling it out. We would have to have this same conversation should we ever receive a request to add, for example, a tobacco company to our collection as there are countries where their promotion is also illegal.

Additionally, we already have a policy against brands engaged in illegal activities and have precedence for rejecting brands that facilitate illegal activities without actively discouraging them. And, while most countries don't outlaw adult content outright, laws do vary wildly throughout the world as to what is & isn't allowed. So what, though? There are many other brands in our library engaged in activities that one country or another may deem legally objectionable, we're not international lawyers. A fair point, so I'll focus on terms like "leaked", "revenge", "teen", etc.; in countries where such content isn't _already_ illegal, more and more are moving to legislate against them. So why not just weed out and disallow, on a case-by-case basis, the sites that either allow such content or, at least, don't actively discourage or police it as we already do for any other brand? Because that would necessitate our contributors spending time on each site, investigating policy & content, which brings me to ...

## 3. Our Contributors
By allowing adult brands we're creating an expectation of our contributors to expose themselves to content they may be strongly morally or ethically opposed to when researching and working to fulfil a request. Even if they themselves have no objections, they could be working in an environment where others around them can see what they are doing and object to it or pass judgement on the contributor. This isn't just true of professional environments but also personal ones - my wife would go through me for a shortcut if she saw me digging around in an adult site, researching their branding! 😆

So what? Contributors could just avoid requests for brands they object to. Fair enough. But for them to be able to do that, such requests would need to be flagged in some way. You mentioned the nature of the site content in the body of both your requests but you did so because you weren't sure if we allow adult brands. As soon we did allow them, it would become normal and people would not see the need to flag them. Not such a big issue on this request as, from the domain, one could hazard a guess as to its content but the same would not be true of your other request. Yes, we could add an NSFW label for such requests but, as that would need to be manually added to each issue by a maintainer, there would be a spell of time where there would be no indication as to the nature of the request.

This would become more problematic as we made our way down through fulfilling requests for all the major, "mainstream" (if you will) brands and started finding ourselves in the territory of niche sites - yes, they exist because there's clearly a demand for them but one person's niche is another person's perversion. So, while a contributor might start off perfectly happy to work on icons for adult brands, they would eventually start finding themselves looking at sites & content that they find more and more objectionable - although it's different for everyone, everybody has a line drawn in every walk of life of what they deem acceptable.

On top of that, we have to take into consideration - _very_ seriously - that it's more than likely that a few of our contributors are legally underage in their jurisdiction and, whatever other opinion you may hold, risking exposing them to adult content is not something we should be doing.

## 4. Endorsement
My final point, you'll be glad to hear! By allowing adult brands, we're implicitly giving the endorsement of adult content on behalf all maintainers of and contributors to our project. Not such a big issue moving forward as those who object strongly enough can simply choose not to involve themselves with the project. The bigger problem is that it would also be retroactive, passing implicit endorsement on behalf of all past maintainers & contributors. Why is that such a problem you ask? Because it could have consequences in their personal and/or professional lives. Many contributors to open source projects like to somehow promote their involvement, from posting their contributions on social media to listing their participation on personal sites to even mentioning them on their CVs. If we were to allow adult brands, anyone who looks into Simple Icons from any of those sources without context and spots the icons for adult brands may draw unfair conclusions about the character of that contributor. Imagine someone applying for a job where they've mentioned Simple Icons on their CV and the recruiter looking us up - it could cost them that job. One person that sprung to mind in particular was our project founder, Dan. Although he's long since stepped down, until recently his name & Twitter profile were still featured throughout the project and he was listed as a maintainer within our organisation.

In a similar vein, we could end up putting our users in a compromising position, especially those that like to include attribution in their projects. Now, suddenly and potentially unbeknownst to them, that attribution links to a site that features adult brands. Not good for people using our icons in a professional project!

I'll take off my maintainer's hat at this point and speak personally to provide a few real world examples. I have a couple of sites where I include a link to Simple Icons in the footer so, by us allowing adult brands, that potentially puts me in the position of having to have a conversation with an irate client who's after getting an earful from one of their visitors because the visitor followed that link and spotted "Adult Brand Echh" in the list of icons - not only has an association with adult content been created for _me_ but also for my client. And I don't even want to consider that same conversation with the client whose site's target demographic is school children and their parents! Some of my other clients include (semi-)state bodies and, as such, have very strict content & HR policies with regard to, among other things, adult content with some departments enforcing that through overzealous content monitors. While such bodies in Ireland don't allow attribution, I do have links to the Simple Icons website within their website admin to allow them to look up and add new brands to their site's icon library as needed. Now, when they follow that link, that overzealous content monitor is going to pick up and flag that the site they're visiting includes mention of multiple adult brands putting _them_ in the potential position of an awkward conversation with their HR department.

## Conclusion
Hopefully I've gotten my points across in an eloquent and coherent manner; this insomnia's still kicking my ass! And hopefully I managed to do so without moralising for or against adult content itself. My primary concern here is one of perception for our community, contributors, users and, yes, also our maintainers, as individuals. I would also like to point out that, while it may be the most contentious one to date, with only maybe icons for military organisations coming anywhere close, the conversation on whether or not to allow something is by no means unique to adult brands; we've had it numerous times before (e.g., illegal services, government bodies, sports clubs, etc.) for numerous different reasons and it's a conversation we'll have again numerous times in the future.

-----
## The Solution
And, after all that, I guess I should weigh in on the solutions that have also been put forward here. If we're going to do this ourselves, I would advocate for it being done through a separate repo, website & package. I would even go so far as to suggest that it be done through a separate GitHub organisation in order to completely avoid making any implicit connection for our contributors & users to the project which could run, to a lesser extent maybe, the same risks for them as I've already raised above.

Speaking personally again, if I may, and without making any suggestions as to what I'd decide, I would have to think long & hard about my own involvement going forward if it was part of the main Simple Icons org. Again, not an issue of morals but rather one of personal & professional perception. And I also don't say that in _any_ way in my current capacity as a maintainer nor in any way to try to influence if and how we do decide to implement this, I just wanted to provide another real world example.

**Comment by jorgeamadosoria** [comment]
this looks like a settled matter. Why is this issue still open?

**Comment by ericcornelissen** [comment]
Thanks for the comment @jorgeamadosoria, as there hasn't been any comment since April I would agree that the discussion is settled - at least for now - so I will be closing this.

If anyone does have a strong opinion against the decision here, please do feel free to leave a comment :slightly_smiling_face:
