### ISSUE TITLE
Icon Request: ImageJ and FIJI

### ISSUE THREAD

**Issue by ayushnoori** [simple-icons/simple-icons#5466]
**Brand Name:** ImageJ
**Website:** https://imagej.nih.gov/ and https://imagej.net/Fiji
**Alexa rank:** 135 (for .nih site), otherwise 166,774
  

**Official resources for icon and color:**  https://imagej.net/File:Fiji-icon.png.html

**Comment by PeterShaggyNoble** [comment]
Thanks for the requests, @ayushnoori.

With an Alexa rank of 166k, ImageJ is definitely within our scope. The only thing we have to decide here is _what_ we should use. The full microscope is not going to be fun to convert to monochrome, assuming we can find a vector version of it - my research so far would suggest that there isn't one. They do, however, have a much simpler logo which can be found [in this directory](https://github.com/imagej/imagej/tree/master/logo) but I haven't seen them using it yet which makes me wonder if they're in the process of adopting it and if we shouldn't hold off for a while to see what happens.

Sadly, it's looking like Fiji is going to be beyond our scope; [their own website](https://fiji.sc/) has an Alexa rank of [~890k](https://www.alexa.com/siteinfo/fiji.sc), below our 500k cut-off, and [their primary GitHub repo](https://github.com/fiji/fiji) has just 431 stars, below our cut-off of 5k. Perhaps, though, those aren't fair metrics to be assessing it's popularity on? Is there any other means of measuring it you can think of that might bring it within our scope? If so then there's an SVG at https://github.com/fiji/fiji/blob/master/images/fiji-logo-1.0.svg that we can use.

**Comment by ayushnoori** [comment]
Hi @PeterShaggyNoble - thanks for considering my request! (Thanks also for creating such a fantastic resource for the community!) I will look into the new ImageJ logo and get back to you. Completely agree that the full microscope doesn't seem practical at all. Will reach out to the ImageJ team.

I also suggested FIJI as FIJI is simply the distribution of ImageJ which comes with several important packages pre-installed (i.e., FIJI stands for "FIJI Is Just ImageJ"). Most people I know who use ImageJ use the FIJI distribution; so, people likely visit the ImageJ website for questions/forum/etc. yet download from the FIJI one. Hence, it might make sense to use the FIJI logo instead of the ImageJ microscope, but not sure.

Perhaps we could loop @ctrueden into this discussion?

**Comment by PeterShaggyNoble** [comment]
> Will reach out to the ImageJ team.

Thanks for doing that 🙂 Let's see what they come back with.

> Most people I know who use ImageJ use the FIJI distribution; so, people likely visit the ImageJ website for questions/forum/etc. yet download from the FIJI one

That's a decent case for its inclusion, alright, and was my own line of thinking, too. What do the other @simple-icons/maintainers think?

> Hence, it might make sense to use the FIJI logo instead of the ImageJ microscope, but not sure.

No harm in including both - I have a personal goal for us to hit 2000 icons by the time we start working on v5 next month!

**Comment by ayushnoori** [comment]
Hi Peter - please see the topic which I just created at the ImageJ community forum here: https://forum.image.sc/t/imagej-logo-for-simple-icons/51725.

**Comment by ctrueden** [comment]
Thanks @anoori for raising this, and @PeterShaggyNoble for your responsiveness. :smile:

There are two major flavors of ImageJ: ImageJ1 and ImageJ2. They have different logos.

# ImageJ1

![](https://raw.githubusercontent.com/imagej/imagej/0667395bcac20e5d7a371ac9f468522c74367d59/logo/imagej1/imagej-128.png)
The original version of ImageJ, still developed by Wayne Rasband. There are no plans to change or update this logo.

# ImageJ2

![](https://raw.githubusercontent.com/imagej/imagej/0667395bcac20e5d7a371ac9f468522c74367d59/logo/imagej-256-flat.png)
The version of ImageJ funded in 2009 by NIH to redesign it with expanded capabilities. Features a backwards compatibility layer to ImageJ1, and a new data model backed by the ImgLib2 library.

Note that the logo of ImageJ2 above is new (designed by @imagejan and colorized by @elevans). We had a community logo redesign contest, and this logo was the winner. We are on the cusp of launching a new ImageJ wiki to replace the old one (preview [here](https://imagej.github.io)), which will switch over to the new logo across the board. We also still need to update the ImageJ application to use the new logo, but that is coming as well.

# Fiji

![](https://raw.githubusercontent.com/fiji/fiji/e79e3ed2edfce3b371abf977cbc3e34371458a5b/images/fiji-logo-1.0-256x256.png)
The Fiji distribution of ImageJ (spelled "Fiji", not "FIJI") is built on ImageJ2. Fiji predates the development of ImageJ2, and thus was originally built on ImageJ1, so it got its own logo at that time. There are no plans to change or update this logo.

For Simple Icons, I would advise adding the _new_ ImageJ2 logo, as well as the Fiji logo.

> Sadly, it's looking like Fiji is going to be beyond our scope

Most of the Fiji community activity takes place on imagej.net in the Fiji space—e.g. https://imagej.net/Fiji. The many Fiji plugins each have their own GitHub repo and wiki page e.g. TrackMate is [here on GitHub](https://github.com/fiji/trackmate) and [here on imagej.net](https://imagej.net/TrackMate), so it's difficult to precisely measure the impact, but I can tell you that the Fiji paper has [more than 27000 citations](https://scholar.google.com/scholar?cluster=17249863664147333646), so clearly lots of scientists are using it.

You can find SVG sources here:
* ImageJ – https://github.com/imagej/imagej/tree/master/logo
* Fiji – https://github.com/fiji/fiji/blob/master/images/fiji-logo-1.0.svg

For ImageJ, I didn't link to a specific SVG because there isn't a single canonical one—there are a couple of choices with different framings, etc. Perhaps the simple-icons team has an opinion about how best to massage the logo for your purposes?

**Comment by adamrusted** [comment]
Thanks @ctrueden for your in-depth response!
Given we've already established that ImageJ is good for addition, I'll start work on converting that logo to monochrome, and hopefully we can get it included in the next couple of releases. Fiji may take a little longer for us to reach a consensus on whether the citations are a good metric for us. I'm assuming (given we only allow one brand colour) the blue is preferred?

**Comment by ayushnoori** [comment]
Hi @adamrusted, wondering if a decision has been made on the inclusion/exclusion of the Fiji logo? Thanks so much!

**Comment by ericcornelissen** [comment]
@ayushnoori, no such decision has been made and, for the record, that discussion would happen publicly in this issue.

Personally, I'm not quite convinced that number of citation is a reasonable metric for us to use given that I find it a hard sell to consider a research paper/project a brand. If nothing else, I think the best argument in favor of including Fiji is the fact that ImageJ itself is included.

**Comment by PeterShaggyNoble** [comment]
With Fiji now ranked [below 2m](https://www.similarweb.com/website/fiji.sc) and lacking any other compelling metrics to attest to its popularity, I'm going to close this issue out.

If someone _can_ make a case in favour of Fiji's inclusion then please open a new issue for it.
