### ISSUE TITLE
On the Zotero icon

### ISSUE THREAD

**Issue by iago-pssjd** [simple-icons/simple-icons#5485]
**Brand Name:** Zotero
**Official resources for icon and color:** https://www.zotero.org/support/brand

I have seen issue #2175 and PR #4561. First of all thanks for the work. I would like to ask for trying to reproduce the colours as in the original icon, so the `z` is red filled, and not just its edges, and white inside. As it is currently, it is almost invisible on small images (as using it for https://shields.io). Otherwise, I believe it would be preferable to use simply the `z` as already suggested in the comment https://github.com/simple-icons/simple-icons/issues/2175#issuecomment-570156747

**Comment by adamrusted** [comment]
Hi @iago-pssjd, thanks for the comment!
Unfortunately, our library only allows for one colour, being the brand's primary colour, which is why the red was chosen. The white used in the previewer is just to offset the logo from the background. I agree that the lines being 0.35pt are a bit small, and in fact most of my PRs since have been 0.5pt to try and counteract that.

Looking again at this, I think you're right in that just the `Z` would suit it better - though I'll see what other @simple-icons/maintainers think before I put the work into a PR to update it.

**Comment by PeterShaggyNoble** [comment]
As it's an option they make available themselves, I too would again vote for just the "z".
