### ISSUE TITLE
Update Ford (?)

### ISSUE THREAD

**Issue by adamrusted** [simple-icons/simple-icons#5543]
**Brand Name:** Ford
**Official resources for icon and color:**
Discovered in #5539.
I've not yet found an SVG source for this one, but the PNG 'flat' logo used on their website differs to the one we have in the collection.

**Comment by PeterShaggyNoble** [comment]
At the time I added this, they were using that treatment in a few places including in a base-64 encoded SVG in their website's footer. That's since been removed but there are still a number of SVGs like [this one](https://www.ford.com/cmslibs/etc/designs/brand_ford/brand/skin/ford/img/ford-loader.svg) to be found in [their website's stylesheet](https://www.ford.com/cmslibs/etc/designs/brand_ford/brand/skin/ford.min.css).

We _should_ probably update though so I went digging again and found [this SVG](https://merchandise.ford.com/Content/Images/logo.svg) on [their merch site](https://merchandise.ford.com/) but we may also find be able to find a better vector version in one of their [brochures](https://secure.ford.com/brochures/), [manuals](https://owner.ford.com/tools/account/how-tos/owner-manuals.html), [financial statements](https://shareholder.ford.com/investors/financials-and-filings/) or [press kits](http://fordpresskits.com/).
