### ISSUE TITLE
Update Plex icon?

### ISSUE THREAD

**Issue by service-paradis** [simple-icons/simple-icons#5560]
**Brand Name:** Plex
**Official resources for icon and color:** https://brand.plex.tv/d/qxmJ3odkK0fj/style-guide

According to https://brand.plex.tv/d/qxmJ3odkK0fj/style-guide, it looks like we might need to use the full wordmark (`plex-logo-mono.`eps) instead of the app icon.

> Plex app icon to be used for Plex apps only. When using a logo to refer to Plex, the company, always use the master logo above.

What do other @simple-icons/maintainers think?

**Comment by adamrusted** [comment]
If they're that explicit in the guidelines, I'd say yes.
I know we've got a few other _app icons_ in the project, but (I think) they're when there's nothing explicit stating they can't be used.

**Comment by PeterShaggyNoble** [comment]
I'd argue that our icon is for the Plex _app_ rather than the company which would allow us to stick with the icon, although we may need to update it to include the square.

The alternative solution would be to add Plex Media Server allowing us to use the encircled icon or, alternatively, just rename our existing icon.

This also [came up](https://github.com/simple-icons/simple-icons/issues/2526#issuecomment-582286404) with Android Auto, although their wording was slightly different
