### ISSUE TITLE
Icon Request: MongoDb Compass

### ISSUE THREAD

**Issue by nitin-1926** [simple-icons/simple-icons#5639]
**Brand Name: MongoDB Compass**
**Website: https://www.mongodb.com/products/compass**
**Alexa rank: 3,770**
  

**Official resources for icon and color: https://github.com/mongodb-js/compass**

**Comment by runxel** [comment]
Hi @nitin-1926, thanks for your request.
Please bear in mind, that the Alexa rank is only viable for the main site, which is just mongodb.com.
I never heard of compass before, but alas, I'm not the database guy.
The Github repo also has a very low popularity with just ~ 400 stars, which is way below our cutoff point (5k).

Do you have any other metric for us?
Otherwise it won't meet the criteria to add it to simple-icons.
Thanks!

**Comment by nitin-1926** [comment]
Hi @runxel , thanks for taking a quick look at it. Actually Compass is the GUI tool to access MongoDB database. It is a mongoDb product only. [
<img width="1144" alt="Screenshot 2021-05-12 at 12 52 07 PM" src="https://user-images.githubusercontent.com/44253685/117935000-e0fe0000-b320-11eb-9993-349183b24b2f.png">
](url)
But since it might not have a too different logo and also doesn't have a separate github repo, so if you want you can skip it.

**Comment by adamrusted** [comment]
Yeah - it looks like the official app icon for 'Compass' is just the [Mongo logo in a white circle](https://user-images.githubusercontent.com/1830867/117941475-07f90980-b302-11eb-82ed-d177d3974102.png). I'd probably say we're best to skip this one, unless the icon changes drastically from the existing one.

**Comment by runxel** [comment]
Thanks for the clarification! Seems like adding this would be pretty redundant at the moment.
Reopen if you feel otherwise.
