### ISSUE TITLE
Include Adianti Framework

### ISSUE THREAD

**Issue by joaopaulomirandamatias** [simple-icons/simple-icons#5646]
**Brand Name:** Adianti Framework
**Website:**: https://www.adianti.com.br/framework
**Alexa rank:** 815,364
**Image**  https://www.adianti.com.br/images/logo_full.svg

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @joaopaulomirandamatias. Unfortunately it looks like this is going to be outside our scope as the Alexa rank, which is for the parent company rather than the framework, is below our threshold of 500k and declining. Before we close the issue, though, is there another metric we could you to assess the popularity of this brand?

It also doesn't look to me as though the framework has its own logo so if we do determine that this is within our scope, I think we'd need to add it as "Adianti Solutions".

**Comment by service-paradis** [comment]
Closing since it looks to be out of scope and without activity since may.
