### ISSUE TITLE
Icons for darkmode

### ISSUE THREAD

**Issue by nodiscardme** [simple-icons/simple-icons#5648]
###  Kind of issue  
  - [x] Improvement
  - [ ] Bug
  - [ ] Other, namely:

### This issue concerns 
  - [ ] The NPM Package
  - [x] The Packagist Package

### Description
The icons are dark and aren't visible clearly in the dark mode of github. Requesting for creation of coloured icons or white icons which can be visible on relevant backgrounds.

**Comment by adamrusted** [comment]
Thanks for the request @Sanketr62, though this is already in progress with #4816. While we could utilize the CSS prefers-color-scheme to solve _some_ of the issue, it doesn't account for people whose device is in 'light mode' but their GitHub is in 'Dark Mode' or vice versa. Rather than close this issue, I'll link the existing PR to close this when a solution becomes available, and if you have any ideas - feel free to contribute there!
