### ISSUE TITLE
Remove: Hatena Bookmark

### ISSUE THREAD

**Issue by davidklebanoff** [simple-icons/simple-icons#573]
It appears to be a product for a Japanese social bookmarking company. Doesn't seem like an appropriate for Simple Icons.

https://en.wikipedia.org/wiki/Hatena_(company)

**Comment by birjolaxew** [comment]
Hatena is [somewhat popular in Japan](https://www.alexa.com/siteinfo/hatena.com) - it's easy to underestimate sites that aren't popular in the west, but we generally include companies that aren't mom-and-pop-level (for perspective, processwire is roughly the same Alexa rank).

Can reopen if you feel otherwise.
