### ISSUE TITLE
Node.js

### ISSUE THREAD

**Issue by dhruvkb** [simple-icons/simple-icons#5759]
As per the Node.js [visual guidelines](https://nodejs.org/static/documents/foundation-visual-guidelines.pdf), the primary element of the logo is the hexagon with diamond-like cuts, not the one with the letters JS in it. Keeping with that, it seems the current Node.js logo (updated in December 2019) is out of date.

<img width="1183" alt="Screenshot 2021-05-22 at 6 00 20 AM" src="https://user-images.githubusercontent.com/16580576/119209201-03cba980-bac3-11eb-838d-2599efe27b1e.png">

**Brand Name:** Node.js (`node-dot-js`)

**Official resources for icon and color:**
  
- [Visual Guidelines](https://nodejs.org/static/documents/foundation-visual-guidelines.pdf)
- [Resources](https://nodejs.org/en/about/resources/#resources)

**Comment by adamrusted** [comment]
Thanks for raising this @dhruvkb!
As discussed in https://github.com/simple-icons/simple-icons/issues/1961#issuecomment-557948939 - the hexagon with `js` was settled upon as the primary hexagon icon couldn't be recognizably converted into monochrome. If you'd like to attempt this yourself - you're more than welcome to have a stab at it following the contribution guidelines, but I for one think the hexagon with `js` is recognizable enough. I'll ping the other @simple-icons/maintainers to see if the consensus has changed since the original issue though.

**Comment by dhruvkb** [comment]
I wasn't aware that a discussion on this had already taken place. Thanks for pointing me to it!

**Comment by PeterShaggyNoble** [comment]
From the previous discussion, it looks like I'd be in the minority on this but as their brand guidelines state that the hexagon is their icon and as they have [a monochrome version](https://nodejs.org/static/images/favicons/safari-pinned-tab.svg) that they use for one of their favicons, I would be in favour reverting back to it. Although I do agree that in monochrome our current version is much more identifiable with their brand. Perhaps this is a case where we could add it as a variant?

**Comment by ericcornelissen** [comment]
I'd personally say the one monochrome favicon option isn't quite enough of a precedent for using it - it doesn't help that it is a `safari-pinned-tab` favicon that we usually dislike because it's low quality. And while I'm generally in favor of using whatever monochrome version the brand suggests we use, I feel like the precedent of the discussion in https://github.com/simple-icons/simple-icons/issues/1961 and the fact that the monochrome version of the logo in [the visual guidelines](https://nodejs.org/static/documents/foundation-visual-guidelines.pdf) uses a gradient for the hexagon but one color for the JS-hexagon suggest we should stick with the current version.

> Perhaps this is a case where we could add it as a variant?

That is definitely something we should consider, good idea!

**Comment by PeterShaggyNoble** [comment]
It looks like this has been resolved in favour of keeping our current treatment but we can revisit it if someone wants to make a further case for changing it.
