### ISSUE TITLE
Request: Semrush Icon

### ISSUE THREAD

**Issue by uiuxarghya** [simple-icons/simple-icons#5822]
**Brand Name:** Semrush
**Website:** https://www.semrush.com/
**Alexa rank:** 1,099
  

**Official resources for icon and color:**
https://brand.semrush.com/

**Comment by uiuxarghya** [comment]
Assign this issue to me.

**Comment by adamrusted** [comment]
Will do, @uiuxarghya. As mentioned previously, don't worry about opening an issue if you're looking to work on it yourself immediately. It's only really needed if you're not able to look at the brand yourself.

**Comment by uiuxarghya** [comment]
> Will do, @uiuxarghya. As mentioned previously, don't worry about opening an issue if you're looking to work on it yourself immediately. It's only really needed if you're not able to look at the brand yourself.

But according to my opinion, this is the correct way to add an icon.
Because if somehow I could not manage to add the icon or if somehow I make any error that is failing the checks, anyone else can work on this issue easily by linking it to his PR.

Is this not the correct way to add an icon @adamrusted ? What do you think? 😀

**Comment by adamrusted** [comment]
> Because if somehow I could not manage to add the icon or if somehow I make any error that is failing the checks, anyone else can work on this issue easily by linking it to his PR.

Sure, I get that. My point was more that rather than creating an issue and PR out the gate, you could potentially save some time by just creating the PR in the first instance. If one of us is unable to assign you to an issue in time, there may be unnecessary duplication of work from another person - and two perfectly good PRs when we can only merge one 😅

My methodology would be to create the issue if I knew I couldn't initially commit, or no longer intended to continue the work in my PR - but while nobody else has requested the icon, I'd say you're safe to just submit a PR (see my Power Platform PRs, for example).

**Comment by uiuxarghya** [comment]
> > Because if somehow I could not manage to add the icon or if somehow I make any error that is failing the checks, anyone else can work on this issue easily by linking it to his PR.
> 
> Sure, I get that. My point was more that rather than creating an issue and PR out the gate, you could potentially save some time by just creating the PR in the first instance. If one of us is unable to assign you to an issue in time, there may be unnecessary duplication of work from another person - and two perfectly good PRs when we can only merge one 😅
> 
> My methodology would be to create the issue if I knew I couldn't initially commit, or no longer intended to continue the work in my PR - but while nobody else has requested the icon, I'd say you're safe to just submit a PR (see my Power Platform PRs, for example).

Okay 😃
I understood what you are trying to say.
