### ISSUE TITLE
Intuit

### ISSUE THREAD

**Issue by diegobot1977** [simple-icons/simple-icons#5861]
**Brand Name:** Intuit
**Website:** https://www.intuit.com
**Alexa rank:** 97
**Official resources for icon and color:** Check it out - the color is `#0076c9`, is in the Intuit logo. See below in the Intuit homepage.

**Comment by diegobot1977** [comment]
Sorry, my Alexa rank is 97, not 249.9 K. Thanks.

**Comment by diegobot1977** [comment]
Still waiting for @NovaGL!

**Comment by Diegopeter2013** [comment]
Let's close this out because it is still not waiting for @NovaGL>

**Comment by diegobot1977** [comment]
Let's close this out because somebody is still not waiting for requesting the Intuit icon.

**Comment by diegobot1977** [comment]
@ericcornelissen, consider previewing this one:

![intuit](https://user-images.githubusercontent.com/73037261/121396195-1fd3a580-c921-11eb-908e-b72f62972855.png)

I go this of third letter `T` for this Intuit icon, and just wrote in SVG-edit.

**Comment by diegobot1977** [comment]
@fbernhart, consider previewing this one:

![intuit](https://user-images.githubusercontent.com/73037261/121597273-7ff44580-ca0e-11eb-9583-73ca6e4563e3.png)

I go this of third letter `T` for this Intuit icon, and just wrote in SVG-edit.

**Comment by diegobot1977** [comment]
Consider previewing this one:

![intuit](https://user-images.githubusercontent.com/73037261/121597273-7ff44580-ca0e-11eb-9583-73ca6e4563e3.png)

I go this of third letter `T` for this Intuit icon, and just wrote in SVG-edit.

**Comment by ericcornelissen** [comment]
@diegobot1977, I noticed you removed your comment from yesterday and commented the exact same again just now, and that you have done so on a few other issues as well. **We do not accept this behavior**. If you continue with this kind of behavior, including but not limited to re-posting comments and opening new issues for existing icon requests, we will take measures that limit your ability to interact with this project. Again, this is an open source project ran by volunteers, no one related to this project is responsible for taking care of your requests. Reopening issues and re-posting comments in order to get us notifications is not acceptable.

I hope you understand. If you have any questions, please feel free to ask them here or [in a new discussion topic](https://github.com/simple-icons/simple-icons/discussions/new).

**Comment by diegobot1977** [comment]
Thanks!
