### ISSUE TITLE
Fix: React

### ISSUE THREAD

**Issue by birjolaxew** [simple-icons/simple-icons#588]
React currently has a small kink in the lower-left of the icon. This should be fixed.

**Comment by davidklebanoff** [comment]
Could it be a side effect of overdoing SVGO compression? There are a number of icons with defects when viewed at a large size, although, the React icon is worse than most.

I quick scan through the first ~50 icons revealed:
500px
bebo
codecademy
coursera
draugiemlv

**Comment by davidklebanoff** [comment]
Some playing with the SVGOMG program. I seem to be able to create "artifacts" on SVGs if I go below a precision of 3, or if I do multiple passes or use the multi-pass feature. This confirms my initial concerns.

Perhaps we could require contributed icons to be optimized, removing any extraneous elements, attributes, paths, etc, but keep the precision at 8. Then we'll have a build process optimize them to a more appropriate level (3-4 precision). Otherwise all icons will continue to degrade with each pass since the optimizations are lossy.
