### ISSUE TITLE
Autodesk Fusion360

### ISSUE THREAD

**Issue by jlnrrg** [simple-icons/simple-icons#6054]
**Brand Name:** Fusion360
**Website:** [fusion360](https://www.autodesk.com/products/fusion-360/overview)
**Alexa rank:** [823](https://www.alexa.com/siteinfo/autodesk.com), Alexa analyses autodesk (which already exists #4245), but it is indead a sub software of autodesk.

**Official resources for icon and color:**
I have not found official resources or a press kit (after a short google search).

**Question**
I can model the logo in illustrator, like I did with other logos before.
The issue here seems to be the 3D character the logo posses. Does anyone has experience with such logos?

![image](https://user-images.githubusercontent.com/77293597/123871706-5014cf80-d934-11eb-9b19-a710a4d995fb.png)

**Comment by service-paradis** [comment]
Thanks for the request, @jlnrrg!

As you said, the Alexa rank is for Autodesk, not the product itself. Since Fusion360 is not open-source, we cannot use our secondary metric of GitHub stars to assess its popularity. Is there another metric you're aware of we can use? Perhaps a Google Trends comparison with a similar product that's already included in our library or that we can easily determine the popularity of through its Alexa rank or GH stars?

**Comment by jlnrrg** [comment]
I compared the google Trends with a few other cad softwares, but the popularity seems to be limited.
I'd propose to add it to the cad list, to the likes of AutoCAD and Inventor. #1984

As there a multiple softwares under the autodesk company, maybe a collective inquision for press kits might be beneficial.

**Comment by service-paradis** [comment]
Closing as out of scope. If you find metrics that wold help assess the popularity, feel free to reopen the issue @jlnrrg.

**Comment by jlnrrg** [comment]
I imagine that the heart ranking of [alternativeto.net](https://alternativeto.net/) might be useful here.
Although based on the score I would not rank Fusion360 very high, so the ticket can stay closed from my point of view.
