### ISSUE TITLE
Question about media companies

### ISSUE THREAD

**Issue by jorgeamadosoria** [simple-icons/simple-icons#6258]
CNN is added, but not any other. Any reason for this?

I would like to add the BBC, Al Jazeera, AP, Fox News, MSNBC, PBS, as well as other media groups and channels from Cuba, Russia, Brazil and / or Mexico.
Is there a particular policy for these kind of icons? What if the media group or channel in question is government owned?

**Comment by PeterShaggyNoble** [comment]
Thanks for the enquiry, @jorgeamadosoria 👍🏻 We add individual icons for individual brands and companies as they are requested rather than adding all icons from a single industry in one go. This ensures that our library contains only the icons people _actually_ have a need for. Having said that, we have done so in the past a couple of time where it has made sense (e.g., car manufacturers & airlines). If you have a need for multiple companies from the same industry you can either turn this into a "[tracking](https://github.com/simple-icons/simple-icons/labels/tracking)" issue by creating a checklist containing everything you need that multiple contributors can work through together or open individual issues for each one you need. Alternatively, if you'd like to work on them yourself, you can just open a PR directly without the need for creating issues.

With regard to state _owned_ companies, currently they would not be allowed under the "Governmental agencies, programs, departments" item in [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md). State _funded_ companies are OK, though, with the precedent having been set by the likes of RTÉ here in Ireland. We have had some brief internal discussion about rewording that item in our guidelines or adding more exceptions to it as it excludes a lot more than we intended, which was primarily governments, government departments and military organisations - Ireland's state meteorological service would currently be disallowed, for example, as it is a part of the Department of Housing, Local Government & Heritage.

Note as well that anything that is wholly owned by Disney would also be disallowed.

**Comment by jorgeamadosoria** [comment]
> Thanks for the enquiry, @jorgeamadosoria 👍🏻 We add individual icons for individual brands and companies as they are requested rather than adding all icons from a single industry in one go. This ensures that our library contains only the icons people _actually_ have a need for. Having said that, we have done so in the past a couple of time where it has made sense (e.g., car manufacturers & airlines). If you have a need for multiple companies from the same industry you can either turn this into a "[tracking](https://github.com/simple-icons/simple-icons/labels/tracking)" issue by creating a checklist containing everything you need that multiple contributors can work through together or open individual issues for each one you need. Alternatively, if you'd like to work on them yourself, you can just open a PR directly without the need for creating issues. Don't forget to search existing open issues & PRs first, though.
> 
> With regard to state _owned_ companies, currently they would not be allowed under the "Governmental agencies, programs, departments" item in [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md). State _funded_ companies are OK, though, with the precedent having been set by the likes of RTÉ here in Ireland. We have had some brief internal discussion about rewording that item in our guidelines or adding more exceptions to it as it excludes a lot more than we intended, which was primarily governments, government departments and military organisations - Ireland's state meteorological service would currently be disallowed, for example, as it is a part of the Department of Housing, Local Government & Heritage.
> 
> Note as well that anything that is wholly owned by Disney would also be disallowed.

This seems to run against @service-paradis comment here: https://github.com/simple-icons/simple-icons/issues/6260#issuecomment-896602953

What's the problem with Disney? They are not kin on letting people use their brands, I suppose?

**Comment by jorgeamadosoria** [comment]
My concerns are satisfied. I'll be closing this one now, thank you all.
