### ISSUE TITLE
Add guidelines for several icon categories

### ISSUE THREAD

**Issue by jorgeamadosoria** [simple-icons/simple-icons#6260]
I would like to know the guidelines for:
- Airlines, train companies, shipping companies (but mainly airlines). They seem to be permitted since some are added, but the documentation does not make it clear as it does with Space agencies, for example.
- Telephone and cellphone companies in the case of being government owned. Are those allowed.
- media groups, tv channels, and media companies in general, specially in relation with government ownership.
- Government owned for profit entities.
- Banking entities, specially central bank authorities.

These are not specifically covered in the guidelines, so I assume they are allowed, but they run into special cases when the government is involved, so I think a little clarification is in order.

Also, why are there so many Metro administrations? Aren't those counted as government department / dependencies for their respective governments? Or is urban transport another exception that is not specifically mentioned?

Thanks in advance for your attention

**Comment by sachinraja** [comment]
I think you should move these questions over to [discussions](https://github.com/simple-icons/simple-icons/discussions) (there might be a button to convert them somewhere)

**Comment by ericcornelissen** [comment]
_Referencing #1207 as it's related_

These are good questions @jorgeamadosoria, basically these are not explicitly mentioned in the Contributing Guidelines either because we haven't encountered (and hence discussed) them yet, we have discussed them but forgot to add them to the guidelines, or simply because including every possible type of brand there is simply infeasible and arguably unproductive.

To clarify some general things. 1) the mention of government is primarily to avoid any controversy with regards to the topic of governments and politics (plus, using their logos almost always requires permission). 2) as alluded to above, including every possible category in the Contributing Guidelines is simply not feasible and I don't think it's a good idea to just add things if we haven't seen multiple instances of confusion or discussion. 3) I'm not sure it's productive to discuss this unless you actually want to add some of these.

To address some of your specific concerns:

- Given the precedent set, airlines, train operators, etc. are currently allowed. Space agencies are included because, at least in the past, the most popular brands in this category are government agencies (specifically NASA).
- Such phone companies are probably allowed. "Government owned" is a bit tricky here as it can mean various things, but I can't think of anything we wouldn't allow _because_ of it being government owned.
- In general I would say such media companies are fine - we already have a precedent with e.g. [BBC](https://simpleicons.org/?q=BBC) - but I do think it's a bit of a difficult one. E.g. given our largely western audience I would not be surprised if we encounter some pushback if we add e.g. a Chinese state-owned media company (for the record, given the precedent of the BBC i think we have to add that as well).
- Government owned for profit entities: this is the broad for me to comment on.
- Banking entities, specially central bank authorities: in general I see no problem with adding these - there's already [a couple of banks](https://simpleicons.org/?q=bank). Central bank authorities may prove a bit difficult indeed, assessing their popularity is a bit difficult. Our normal metrics don't really apply as I think it would exclude many and include some without good reason. I would personally say we should exclude central bank authorities for the same reason we exclude government agencies. 
- Metros are included because they were requested and added without much discussion on whether these should be considered government agencies (not sure on the details as I was very involved in many of those contributions). In short, at this point it's allowed by precedent.

> I think you should move these questions over to [discussions](https://github.com/simple-icons/simple-icons/discussions) (there might be a button to convert them somewhere)

I would prefer this as an issue, it makes it easier to act on and mark as closed when we finished with it. The only advantage to a discussion I see is that it would allow us to discuss the different bullets of the original post in separate threads of the same topic. However, this could also be achieved by opening multiple issues.

**Comment by jorgeamadosoria** [comment]
> _Referencing #1207 as it's related_
> 
> These are good questions @jorgeamadosoria, basically these are not explicitly mentioned in the Contributing Guidelines either because we haven't encountered (and hence discussed) them yet, we have discussed them but forgot to add them to the guidelines, or simply because including every possible type of brand there is simply infeasible and arguably unproductive.
> 
> To clarify some general things. 1) the mention of government is primarily to avoid any controversy with regards to the topic of governments and politics (plus, using their logos almost always requires permission). 2) as alluded to above, including every possible category in the Contributing Guidelines is simply not feasible and I don't think it's a good idea to just add things if we haven't seen multiple instances of confusion or discussion. 3) I'm not sure it's productive to discuss this unless you actually want to add some of these.
> 
> To address some of your specific concerns:
> 
> * Given the precedent set, airlines, train operators, etc. are currently allowed. Space agencies are included because, at least in the past, the most popular brands in this category are government agencies (specifically NASA).
> * Such phone companies are probably allowed. "Government owned" is a bit tricky here as it can mean various things, but I can't think of anything we wouldn't allow _because_ of it being government owned.
> * In general I would say such media companies are fine - we already have a precedent with e.g. [BBC](https://simpleicons.org/?q=BBC) - but I do think it's a bit of a difficult one. E.g. given our largely western audience I would not be surprised if we encounter some pushback if we add e.g. a Chinese state-owned media company (for the record, given the precedent of the BBC i think we have to add that as well).
> * Government owned for profit entities: this is the broad for me to comment on.
> * Banking entities, specially central bank authorities: in general I see no problem with adding these - there's already [a couple of banks](https://simpleicons.org/?q=bank). Central bank authorities may prove a bit difficult indeed, assessing their popularity is a bit difficult. Our normal metrics don't really apply as I think it would exclude many and include some without good reason. I would personally say we should exclude central bank authorities for the same reason we exclude government agencies.
> * Metros are included because they were requested and added without much discussion on whether these should be considered government agencies (not sure on the details as I was very involved in many of those contributions). In short, at this point it's allowed by precedent.
> 
> > I think you should move these questions over to [discussions](https://github.com/simple-icons/simple-icons/discussions) (there might be a button to convert them somewhere)
> 
> I would prefer this as an issue, it makes it easier to act on and mark as closed when we finished with it. The only advantage to a discussion I see is that it would allow us to discuss the different bullets of the original post in separate threads of the same topic. However, this could also be achieved by opening multiple issues.

-thanks for the reply, @ericcornelissen.
what I. got from this is:
- we evolve the guidelines as needed. Reasonable.
- Transport companies and metros are grandfathered in at this point. Maybe a threshold should be specified for this category, given that there are a significant amount of them (and more may come?)
- Phone and telecomm in general are allowed regardless of ownership. got it. Perhaps a minimum user base could be a good threshold for this, you think?
- I agree there might be pushback including non Western media. Perhaps an addendum to the disclaimer addressing this is in order? I think we can't aspire to have a complete representative list of the biggest players in a given field if we are going to be concerned with pushback at every turn. I'm thinking on people like me that make lists of brands for comparison, market share, geographic distribution, etc. All good when you stick with western media, but when you go global, then you would be missing icons and that makes the design inconsistent, leaving the potential user to drop the library. it's a self imposed limitation, which I find can be managed if we make it clear that the organization does not condone the content of the media nor their intent, and it's included just because of significance. Viewership or reach may be a good metric here, maybe?
- Excluding central banking entities because they are akin to government departments is reasonable.

Do know that I don't ask this idly. I ask because I want to include missing media companies for several countries and the US, as well as some airlines. I would like to include banks as well, but that's more of an idle wish than a necessity so I don't really mind dropping that.

**Comment by ericcornelissen** [comment]
> Transport companies and metros are grandfathered in at this point. Maybe a threshold should be specified for this category, given that there are a significant amount of them (and more may come?)

The normal popularity thresholds always apply - if those are not met we are always open to other metrics of popularity.



> I agree there might be pushback including non Western media. Perhaps an addendum to the disclaimer addressing this is in order? I think we can't aspire to have a complete representative list of the biggest players in a given field if we are going to be concerned with pushback at every turn. I'm thinking on people like me that make lists of brands for comparison, market share, geographic distribution, etc. All good when you stick with western media, but when you go global, then you would be missing icons and that makes the design inconsistent, leaving the potential user to drop the library. it's a self imposed limitation, which I find can be managed if we make it clear that the organization does not condone the content of the media nor their intent, and it's included just because of significance. Viewership or reach may be a good metric here, maybe?

From my perspective, an icon library saying "it does not condone the content of the media nor their intent" based on the icon being in the library  is a 1) a bit over the top, 2) does not help anyone reading the disclaimer, and 3) probably doesn't address any real concerns. That might just be me though.

In any case. Viewership and reach _could_ be a good metric but we would need some concrete examples to determine if that's the case and what also what reasonable numbers are.


> Do know that I don't ask this idly. I ask because I want to include missing media companies for several countries and the US, as well as some airlines. I would like to include banks as well, but that's more of an idle wish than a necessity so I don't really mind dropping that.

Thanks for clarifying.

**Comment by jorgeamadosoria** [comment]
_> From my perspective, an icon library saying "it does not condone the content of the media nor their intent" based on the icon being in the library is a 1) a bit over the top, 2) does not help anyone reading the disclaimer, and 3) probably doesn't address any real concerns. That might just be me though._

It's a way to sidestep any problem with pushback or legal issues. It helps people understand that just because they personally don't like a particular network, it doesn't mean the library is responsible for it.
For example, right now CNN and BBC are included: what if people that think these are "fake news" decide to turn against the library because of what they perceive as bias, include those and not Fox News? 
There is always someone that will be displeased, reason or not. A disclaimer is something you can use as an answer to a disgruntled unreasonable person, and something you can use as a legal protection, should the need arise.

_> In any case. Viewership and reach _could_ be a good metric but we would need some concrete examples to determine if that's the case and what also what reasonable numbers are.
>_ 

I guess that for some companies there is a good web presence, so that would fall under the Alexa ranking threshold. For the ones that don't, I can't think of anything other than viewership at this time :(

**Comment by ericcornelissen** [comment]
> For example, right now CNN and BBC are included: what if people that think these are "fake news" decide to turn against the library because of what they perceive as bias, include those and not Fox News?

I think that specifically those kind of people won't care about a line in some text file saying that we don't condone the content of the media they don't like.


> It helps people understand that just because they personally don't like a particular network, it doesn't mean the library is responsible for it.

That seems self-evident to me (what I meant by "a bit over the top"). But I suppose I agree that it seems self-evident to us isn't a particularly good reason not to include it.


> It's a way to sidestep any problem with pushback or legal issues. [...] There is always someone that will be displeased, reason or not. A disclaimer is something you can use as an answer to a disgruntled unreasonable person, and something you can use as a legal protection, should the need arise.

Not sure how it would lead to any legal issues :thinking: Did you have anything in mind?

Also, when you say "disclaimer" are you referring to [the DISCLAIMER.md file](https://github.com/simple-icons/simple-icons/blob/develop/DISCLAIMER.md) we have (because that's how I read it the first time around)? Part of my pushback is because I don't think we should add it to that file as I think it would just distract from the actually useful text it contains now.

**Comment by jorgeamadosoria** [comment]
> I think that specifically those kind of people won't care about a line in some text file saying that we don't condone the content of the media they don't like.
True, but the idea here is to protect the project from whatever spurious attacks could be leverage against it. For example, recently we had a discussion about adding Gab #6156, a far right alternative social network. Had that been included (and lacking a clear disclaimer that distances Simple Icons from whatever the icons it contains represent) you are, in theory, exposed as a platform that endorses them. 
It may be obvious that including a line saying "we are not responsible from whatever happens in the products we add" is not going to make a huge difference, but it gives you enough leeway to answer to whoever thinks about attacking you on that grounds. Why not preempt this kind of attacks and simplify the decision making process moving forward? 
The world is a crazy place, and the truth and common sense are not self evident anymore, if they ever were. 

> Not sure how it would lead to any legal issues 🤔 Did you have anything in mind?
No, I don't have anything particular in mind. Still, why not be defensive about it?

> Also, when you say "disclaimer" are you referring to the DISCLAIMER.md file ...
I wasn't referring to that particular file, but that's the right place to add this disclaimer, yes.
A line about how you provide the icons following guidelines for relevance and do not condone their symbolism nor the actions or content of the companies or products they represent does not take much space, and it is good enough to avoid discussions like "why are you including CNN and not Fox? These people are biased". Which may happen anyways, but if they happen now you would need to answer with a guideline explanation, whereas with a disclaimer you just need to say "we don't care about the content, see our disclaimer". 

I don't know, it seems like a very easy step to take for protecting the image of the brand.

**Comment by ericcornelissen** [comment]
I'm not necessarily saying I disagree I'm just pointing out a combination of concerns that make me question whether it is actually that useful. In summary:

- My gut feeling is that many people that would have objections to us including certain brands won't be satisfied with a one-liner in our documentation (or related document).
- My impression is that there's no legal issues with regards to including "controversial" icons.
- I think adding (specifically) to [the DISCLAIMER.md](https://github.com/simple-icons/simple-icons/blob/develop/DISCLAIMER.md) will be counterproductive to the goal of this file - namely addressing "legitimate" concerns w.r.t. the use of the logos in the collection.

But I would be happy to discuss this with more input from others (including @simple-icons/maintainers) :smiley: 

---

Also, just to confirm, has your original issue been resolved @jorgeamadosoria? (we can keep this issue open for the new topic)

**Comment by jorgeamadosoria** [comment]
My original issue is solved, yes. Not to my full satisfaction, but my doubts were answered.
You can close the issue if you want.
