### ISSUE TITLE
New Icon Request: Devfolio

### ISSUE THREAD

**Issue by GSri30** [simple-icons/simple-icons#6354]
**Brand Name:** Devfolio
**Website:** https://devfolio.co/home/
**Alexa rank:** 80,182
  

**Official resources for icon and color:**
  
https://devfolio.co/favicons/favicon-128.png

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @GSri30. However we will not be able to add this one due to the line below in their [brand guidelines](https://github.com/devfolioco/brand-assets/blob/main/README.md). If you, or someone else, would like to contact them seeking permission for us to do so then we can revisit this issue.

> You may not modify the assets in the manner of **color**, font, or appearance.
