### ISSUE TITLE
Request: GoLand

### ISSUE THREAD

**Issue by kkrypt0nn** [simple-icons/simple-icons#6368]
**Brand Name:** GoLand (made by JetBrains)
**Website:** https://www.jetbrains.com/go/
**Alexa rank:** 1,999

**Official resources for icon and color:**
- https://github.com/JetBrains/logos/tree/master/web/goland
- https://www.jetbrains.com/company/brand/logos/

**Comment by service-paradis** [comment]
Thanks for the request, @kkrypt0nn. As with other JetBrains products, though, the Alexa rank is for JetBrains, not the product itself. Since GoLand is not open-source, we can't use our secondary metric of GitHub stars to assess its popularity. Is there another metric you're aware of we can use? Perhaps a Google Trends comparison with a similar product that's already included in our library or that we can easily determine the popularity of through its Alexa rank or GH stars?

**Comment by jorgeamadosoria** [comment]
I'm fine with it. Slightly concerned with the fact that we are establishing precedent with this that eyeballing a google trend comparison is basis enough, but for this particular tool I have no objection.

**Comment by service-paradis** [comment]
Google Trends is used in many case where the current metrics does not apply (Apache products, Jetbrains products, etc...).
We always try to compare the requested product with a similar icon already in the project. If the comparison is pretty good, we ask other maintainers.
This comparison is not suitable for any icon and is used on a case by case basis.
