### ISSUE TITLE
Popular icons from unofficial sources

### ISSUE THREAD

**Issue by sachinraja** [simple-icons/simple-icons#6418]
It seems as though there is no official JavaScript icon, which makes sense as there is no official governing body for it. The current source:
https://github.com/simple-icons/simple-icons/blob/198c42d6f8cc91c8e5551adfe0353d06c3828c34/_data/simple-icons.json#L4555-L4557

This uses the source https://github.com/voodootikigod/logo.js, which is unofficial. I realize that it may be too late to remove this icon as I'm sure it is a very popular one, but I thought I'd open this for discussion anyway.

**Comment by gizmecano** [comment]
I understand this appreciation, but however, in this case, it is probable that other icons could be considered in the same case.

For example, Markdown icon has become a _de facto_ standard (notoriously used by [Primer Octicons](https://primer.style/octicons/markdown-16)), but it does not seem to me that it is any formal brand (by the way, source in data file refers to the work of the designer, not to [the language page](https://daringfireball.net/projects/markdown/)).

https://github.com/simple-icons/simple-icons/blob/198c42d6f8cc91c8e5551adfe0353d06c3828c34/_data/simple-icons.json#L5437-L5440

**Comment by jorgeamadosoria** [comment]
I think this one is so established as a de facto standard that it even has other icons styled after it, like [Typescript](https://www.typescriptlang.org/branding/) for example.

I feel good keeping it in, even if there is no official source. Javascript certainly is very popular and the icon is well established and necessary for technological lists and such (speaking from experience).
I vote to keep it in, with the current source (after a fashion, see #6399 and it's linked PR).

**Comment by sachinraja** [comment]
I disagree that "de facto standard" icons should be included. The [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#1-identify-official-logos-and-colors) say to "identify official logos and colors." 

Icons are supposed to represent a brand, not the community. If this icon was brought up and used by JSConf (as said in the source), it should be labeled as such. Also note that the [JS Wikipedia page](https://wikipedia.org/wiki/JavaScript) does not use the icon.

> For example, Markdown icon has become a de facto standard

I guess this issue also raises discussion on those icons.

**Comment by gizmecano** [comment]
As I wrote before, I can understand this opinion: it may sound perhaps rigorous, but reading the current guidelines, it seems founded and logical... 😕

In this vein, in addition to Javascript or Markdown, the icon currently included for CSS3 (added by @ericcornelissen in 2266a1474c86270255d5630db40d31d6c04d538f) could probably be added to this specific list. Indeed, this file doesn't seem to exist in [the source mentioned in reference](https://github.com/simple-icons/simple-icons/blob/198c42d6f8cc91c8e5551adfe0353d06c3828c34/_data/simple-icons.json#L2059): the [occurrence of the "CSS3 technology"](https://www.w3.org/html/logo/#the-technology) appears with a dissimilar icon (see below).

![w3c css3](https://user-images.githubusercontent.com/852661/131223371-8d771812-70e9-4870-a4bf-c54ac39c5627.png)

**Comment by jorgeamadosoria** [comment]
I would rather amend the guidelines to include "widely recognized de facto standards" before taking down any of the icons discussed here.
These icons are pivotal in current software development and are very, very accepted as symbols of their respective technologies. 
If the community uses two icons, then is up to us to decide which one to add, if there is one that is clearly predominant (in our consensual opinion). If there are no predominant icons (or no consensus) then we can choose not to add any. 

But in these cases there is no argument about the icons being representative or widely accepted. The only argument is that they are not official, and that the guidelines preclude this. I don't think that's enough rational to get rid of such core symbols.

**Comment by gizmecano** [comment]
Of course, the arguments of @jamesmontemagno are perfectly valid (it is why I mentioned some representations which have become _de facto_ common even if they have no such formal value).

But the comments made by @sachinraja on what appears like a peculiar contradiction currently existing between the acceptance of certain icons and the wording of the guidelines are just the same valid.

It seems there is a dilemma to be resolved.

🤷‍♂️

**Comment by jorgeamadosoria** [comment]
Ok, the guidelines say that to request an icon:

Is of **a popular brand**:
- For websites, the Alexa rank should be less than 500k.
     Note that for brands that have already been added the threshold for continued inclusion rises to 750k.
- For GitHub projects, the amount of "stars" should be above 5k.
**- For anything else, popularity will be judged on a case-by-case basis.**

I'm going to say that this is that third case. We are on the verge of accepting an icon based on eyeballing a chart of Google Trends that "looked similar" to other included icons #6368. And we voted favorably because it looked right to several of us.
I would say that if including these icons looks right to several of us, then we are not violating guidelines as written.

Still, an small amendment would make this clearer, something like "Some icons may be elegible for inclusion by maintainers for particular reasons other than the ones stated, as long as there is consensus" or something of that sort.

Again, better to change the guidelines than to eject these icons.

**Comment by sachinraja** [comment]
I have no problem with the popularity of these icons. I only have a problem with the source of these icons, so I agree with @jorgeamadosoria, I think an amendment would help clarify this.

**Comment by jorgeamadosoria** [comment]
I've added a pull request with tentative text to address this issue in the contributing guidelines. All changes welcome there. 
This PR assumes that we are already in agreement with tweaking the guidelines to make Javascript fit. I would suggest making changes to the text in the PR, and further discussion on the issue of changing the guidelines or removing the icons be kept here, if there is any.

**Comment by ericcornelissen** [comment]
You bring up an interesting issue @sachinraja, and the discussion so far has been excellent. I just want to add three things:

1. The "brands" discussed so far (CSS, JavaScript, and MarkDown) were all added pretty early in this project's life. So that's the primary reason they don't necessarily obey the _current_ requirements. They've probably not been questions before as, as [already pointed out](https://github.com/simple-icons/simple-icons/issues/6418#issuecomment-907691574), few people will take issue with their popularity. Of course, that's not to say they shouldn't obey the current requirements.
2. The "brands" mentioned so far are not the only ones. Other programming languages (notably C, see #1819 and #3868) fall in this category. But really anything that is not really a "brand" (e.g. technologies, standards, etc) can fall in this category unless some kind of governing body took the time to decide on a logo.
3. I would personally agree that we should keep these kinds of "brands" here and update the contributing guidelines so that they can be included. An alternative would be to double down on the "brands" aspect of this project and remove anything that is not a _traditional_ brand; potentially starting a spin-off project for the removed icons.

**Comment by sachinraja** [comment]
> I would personally agree that we should keep these kinds of "brands" here and update the contributing guidelines so that they can be included.

I agree, this makes the most sense to me. Does everyone agree that we should proceed with #6428 then?
