### ISSUE TITLE
New version of SVGOMG (powered by SVGO v2.5.0)

### ISSUE THREAD

**Issue by gizmecano** [simple-icons/simple-icons#6498]
### Kind of Issue

Improvement

### Description

Guess maintainers have already seen this information go by, but for all intents and purposes, I point out that [SVGOMG has been updated and is now powered by SVGO v2.5.0](https://twitter.com/jaffathecake/status/1435568725521018884): it maybe could usefulto check how this possibly impacts [contributing and optimization](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#3-optimize-the-icon).

🤔

### Contributing

Yes

**Comment by sachinraja** [comment]
I want to say that this doesn't change much as contributors using the cli have already been using svgo 2.4.0:
https://github.com/simple-icons/simple-icons/blob/b9cc1788d1efa38de69a17e1c8cb9a86eeed4954/package.json#L30

so if it was a big change, it probably would have come up earlier. Though the fact that it took 2 years to update svgo makes me question if we should be recommending SVGOMG in the docs.

**Comment by ericcornelissen** [comment]
I think allowing contributors to just use SVGOMG makes contributing a lot easier for a lot of people. If you're not comfortable with the CLI and/or don't have NodeJS installed, running `npm install` and `npm run svgo -- icons/icon.svg` can be daunting and as long as there's a web version available we might as well offer it as an option.

If we're concerned SVGOMG gets out of date and want to make sure it's always on the latest SVGO version, we could simply clone it, host it ourselves, and link that in the Contributing Guidelines. Or, if we want to invest more time, build it into our own website (in which case it could be a lot simpler as we have a fixed configuration, just the precision would be configurable).

> My opinion is that we should just remove the other two options (SVGOMG and Docker) and only recommend the cli.

The Docker option is just a wrapper for the SVGO CLI, it's _somewhat_ useful for anyone that doesn't have Node on their system or can't just run `npm install` on their machine (e.g. because of a firewall). Even if that's just a handful of contributors, I don't really see a reason to remove it.

**Comment by sachinraja** [comment]
I see, thanks for explaining. I agree then, we should keep all options open.

**Comment by sachinraja** [comment]
Going to close this as I don't believe any changes are needed, but we can reopen if necessary.

**Comment by gizmecano** [comment]
> Going to close this as I don't believe any changes are needed, but we can reopen if necessary.

No objection for closing, @ericcornelissen's answer seems self-explanatory enough.
