### ISSUE TITLE
Request: Matter.js

### ISSUE THREAD

**Issue by herokunt** [simple-icons/simple-icons#6500]
### Brand Name

Matter.js

### Website

https://brm.io/matter-js/docs/

### Popularity Metric

Github stars: 12k
https://github.com/liabru/matter-js

### Official Resources for Icon and Color

**SVG Icon**: https://camo.githubusercontent.com/77e2685e9b84be282f193a05c6571760200f8adfaf92892490ade52a596f2a7c/68747470733a2f2f62726d2e696f2f6d61747465722d6a732f696d672f6d61747465722d6a732e737667

Hex Colors: `#76f09b`, `#f5b862`, `#f55f5f`, `#4b5562`

### Contributing

Yes

**Comment by adamrusted** [comment]
SVG version of the logo is available on the homepage of the website, so that should be used as the source as opposed to the **SVG Icon** link above. Unsure how this could best be 'converted' to an icon though, short of including the full logo.
As you've indicated that you'd like to contribute this @herokunt - I'll assign the issue to you. If you have any trouble, feel free to ping a maintainer.

**Comment by herokunt** [comment]
Hi Adam, so it turns out the logo with the full text looks too small  so I've made a version based on the favicon. Not pixel-perfect but I wonder if this is still good enough to add it, and if so should I link the favicon as the source in `_data/simple-icons.json`? As for the color I'd go with the text color: `#4b5562`

![matterjs](https://user-images.githubusercontent.com/48509601/132884212-76cd7ba1-34da-455e-bab4-d2ae9120f5ec.png)
![favicon](https://user-images.githubusercontent.com/48509601/132884316-17bee2c1-2104-4794-a115-fa88fe406f62.png)

**Comment by jorgeamadosoria** [comment]
> Hi Adam, so it turns out the logo with the full text looks too small so I've made a version based on the favicon. Not pixel-perfect but I wonder if this is still good enough to add it, and if so should I link the favicon as the source in `_data/simple-icons.json`? As for the color I'd go with the text color: `#4b5562`
> 
> ![matterjs](https://user-images.githubusercontent.com/48509601/132884212-76cd7ba1-34da-455e-bab4-d2ae9120f5ec.png) ![favicon](https://user-images.githubusercontent.com/48509601/132884316-17bee2c1-2104-4794-a115-fa88fe406f62.png)

the problem I see with the favicon, other than it being too low fi, is that the borders of the icon don't seem natural. For example, the triangle is cut for no reason other than to fit the image in a square; the red rectangle is meant to be similar to the red square in the logo, so I can only assume that it was cut as well.

I tried to see if this icon or any other had an use elsewhere, but Matter.js seems to only be identified by the full watemark with the colored triangle / circle / square motif.
I understand that Matter.js is going to look tiny in 24x24, but at least for the time being, it's the only one I think they use as identifier.

I see three ways forward:
- Use the full watermark. It would look tiny, but it is the official logo.
- Expand on the work that @herokunt did, and complete the triangle and the square. that way the logo would look natural. Problem is, we would be outright inventing it.
- Email matter.js people @liabru here on Github and ask them about this.

I personally lean towards the full wordmark, however small it shows. It wouldn't be the first time we include a wordmark icon.

**Comment by liabru** [comment]
@jorgeamadosoria sorry I didn't spot this earlier, just to confirm that's right only the full wordmark is in proper use for the project: https://brm.io/matter-js/img/matter-js.svg

So it's probably not really ideal for this kind of usage unfortunately, it probably won't look right if it needs to be squashed in a small square. The other icon above is only meant for the docs as a favicon specifically, rather than as part of the brand.  

Hope that helps clear it up at least, I can get back if I work on something that would suit.

**Comment by jorgeamadosoria** [comment]
Thanks for answering, @liabru! 
It really isn't ideal for this library due to the size, you are correct. However I'm going to go ahead and add it anyways. 
The good thing about SVGs is that they scale, so even if the icons don't look all that defined in the website they may be just fine when the user finally does something with them.

**Comment by jorgeamadosoria** [comment]
@liabru 
if you could please take a look at my attempt here: https://github.com/simple-icons/simple-icons/pull/7182
