### ISSUE TITLE
Request for new cryptocurrency related icons

### ISSUE THREAD

**Issue by ElRodrigote** [simple-icons/simple-icons#6600]
Hi there!

I'd like to request for some additional logos from blockchain and cryptocurrency projects:
* [Cardano](https://www.coingecko.com/en/coins/cardano)
* [Polkadot](https://www.coingecko.com/en/coins/polkadot)
* [Avalanche](https://www.coingecko.com/en/coins/avalanche)
* [Solana](https://www.coingecko.com/en/coins/solana)
* [Polygon](https://www.coingecko.com/en/coins/polygon)
* [Axie Infinity](https://www.coingecko.com/en/coins/axie-infinity)

Cheers!
Rodrigo.

**Comment by jorgeamadosoria** [comment]
HI Rodrigo, thanks for your request.
In order for us to add any icon, they have to comply with the inclusion criteria outline in [CONTRIBUTING.md](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)

In this case, the criteria that is more appropriate would be Alexa ranking:

https://www.alexa.com/siteinfo/cardano.org (7419)
https://www.alexa.com/siteinfo/polkadot.network (24800)
https://www.alexa.com/siteinfo/avax.network (11164)
https://www.alexa.com/siteinfo/solana.com (7552)
https://www.alexa.com/siteinfo/polygon.technology (11572)
https://www.alexa.com/siteinfo/axieinfinity.com (527)

Since they are all below 500k, they qualify for inclusion.
Would you be so kind as to use the [new icon form](https://github.com/simple-icons/simple-icons/issues/new?assignees=&labels=new+icon&template=icon_request.yml&title=Request%3A+) to request each of these icon separately, providing the fields requested there? That way you would have more chances of someone taking any of the icons separately, because bulk requests are usually more involved and discourage contributions.
