### ISSUE TITLE
Develop Branch 

### ISSUE THREAD

**Issue by dirien** [simple-icons/simple-icons#6645]
hi @simple-icons/maintainers,

can someone with admin rights check the develop branch history?

![image](https://user-images.githubusercontent.com/38325136/135746623-6b1b40c9-f611-49da-9d91-9809faba9bdb.png)

There where two version bumps this morngin and, when i did a update of my fork the upstream gets an empty commit... 

I would fix it but can't as i have to rights on the gitrepo.

Thanks.

**Comment by dirien** [comment]
i would 
```
git reset --hard 8eb69b42acbc7f7eabb5e47dfcfac8251d3f3b5b
```
To the comit before the Aldi Nord Merge. Then check the Aldi Nord commit again.

**Comment by ericcornelissen** [comment]
From my local git history, it looks like there was some confusion from your side (as you committed eceb37ae967424008cf8e2692583543cb0131461). The parent commit of the second version bump is c66c2d8ac13fcc7456884c9344d9dbd90f453bc9 and was not directly committed to the develop branch of this repository (as there's no CI checks). I can't tell where the merge commit (i.e. eceb37ae967424008cf8e2692583543cb0131461) comes from though. 

```
*   eceb37ae (HEAD -> develop, origin/develop, origin/HEAD) Merge branch 'develop' into develop
|\  
| * a88c5989 version bump
* | a53cd657 Add Aldi Nord icon (#6382)
| | *   273fe227 (tag: 5.17.0, origin/master) Release 4 new icons and 14 updated icons (v5.17.0)
| | |\  
| |_|/  
|/| |   
* | | 8eb69b42 version bump
```

Since the state of this repository is fine in the end I'm not going to bother force pushing away some commits at the risk of invalidating existing Pull Requests.

Next time something's off with your fork, it's probably best not to make changes to this base repository but rather to force push the `simple-icons/simple-icons -> develop` to your fork (or create a new fork, but that's not really an option if you have open Pull Requests).

**Comment by dirien** [comment]
@ericcornelissen , sorry for the trouble. I am still thinking how this could happend. I did not merged the Aldi Nord PR. What i did was to update my fork... Github asked for a PR on my fork... Super strange..

Sorry again for this.

**Comment by ericcornelissen** [comment]
No problem @dirien :slightly_smiling_face: The Aldi Nord PR was merged by **joaopedromoraez**, see:

![image](https://user-images.githubusercontent.com/3742559/135758050-308a7d82-0702-4fae-b21f-e9e0f46e7489.png)

The eceb37ae967424008cf8e2692583543cb0131461 commit is separate from that. I also can't really tell what happened but as the source code on `develop` looks good there's not much of a problem outside of a slightly confusing commit in the history :upside_down_face:
