### ISSUE TITLE
Request: Python Requests

### ISSUE THREAD

**Issue by FayasNoushad** [simple-icons/simple-icons#6691]
### Brand Name

Python Requests

### Website

https://python-requests.org/

### Popularity Metric

The alexa rank is `50,072`.

See :- https://www.alexa.com/siteinfo/python-requests.org

### Official Resources for Icon and Color

https://raw.githubusercontent.com/psf/requests/main/docs/_static/requests-sidebar.png

### Additional Comments

- Multiple colours :- Black and Gray
- No specific license But the image in a repository ( Apache License 2.0 )
- This brand know more people. This brand is a official http python library of Python Software Foundation

### Contributing

No

**Comment by FayasNoushad** [comment]
> Can you please change the requested icon name? Current icon name is inappropriate.
> 
> Suggested name: Python Requests

Updated

**Comment by dokson** [comment]
This was closed as `completed` in May 2023, but no `requests.svg` was ever added (verified — no add/remove commits in git history for that filename). Looks like an accidental closure during the title-formatting back-and-forth.

Nothing has changed since then: `requests` still meets the PyPI popularity threshold by ~3 orders of magnitude, and the official asset situation is the same (only the raster `requests-sidebar.png` in psf/requests, no SVG upstream).

Could a maintainer reopen? I'd like to contribute the icon, vectorized from the official PNG. Brand color `#C21325`.
