### ISSUE TITLE
Request: SpigotMc

### ISSUE THREAD

**Issue by Tofpu** [simple-icons/simple-icons#6704]
### Brand Name

SpigotMc

### Website

https://www.spigotmc.org/

### Popularity Metric
Founded in 2012, SpigotMC.org is home to the community behind the biggest Minecraft server software projects and provides a place for everyone involved with Minecraft servers to connect with each other whether they seeking help and support or sharing and showcasing their work.

> https://www.alexa.com/siteinfo/spigotmc.org 

Their Alexa rank is `#16,062`

### Official Resources for Icon and Color

Official PNG file from their site:
https://static.spigotmc.org/img/spigot.png

There is no branding guidelines from what I'm aware of.

### Contributing

No

**Comment by QarthO** [comment]
Any update on this? I see another platform for Minecraft addons similar to spigot (modrinth) was added to simpleicons. I'd love for spigot to be added!

Post has been stale for years, since in the past alexa.com was used. Here's their popularity from similarweb.
https://www.similarweb.com/website/spigotmc.org/#overview
Global Rank
#18,344
