### ISSUE TITLE
I made a Simple Icons WordPress plugin

### ISSUE THREAD

**Issue by tjtaylo** [simple-icons/simple-icons#715]
https://wordpress.org/plugins/simple-icons/

Let me know if there is anything I need to change or if you want the plugin removed from the WP repository all together.

**Comment by dshanske** [comment]
I use Simple Icons in a WordPress plugin, do you want me to report same?

**Comment by tjtaylo** [comment]
The plugin is open source. Unfortunately the WordPress plugin repository uses SVN. I'm not sure if we should use a GIT to SVN bridge or what the best practice is.

**Comment by ericcornelissen** [comment]
> The plugin is open source. Unfortunately the WordPress plugin repository uses SVN. I'm not sure if we should use a GIT to SVN bridge or what the best practice is.

I think we should at least add a link to the Wordpress plugin by @tjtaylo to the README. And even though I think it would be great to have its repo incorporated into the SimpleIcons organization, given that Wordpress requires it to be an SVN repo that is too big of a hassle.

At least, that is what I think and I've never worked with SVN. I did have a quick search on Google and found that Github does [offer support](https://help.github.com/articles/support-for-subversion-clients/) for SVN repos (since [2010](https://github.com/blog/626-announcing-svn-support)). But as I understand it this will transform the SVN repo into a git repo that can be interacted with through an SVN client.


> I use Simple Icons in a WordPress plugin, do you want me to report same?

What exactly do you mean? Can you link your plugin?

**Comment by dshanske** [comment]
I meant for you to reference.

**Comment by dshanske** [comment]
http://wordpress.org/plugins/syndication-links

**Comment by ericcornelissen** [comment]
@dshanske I was talking about what kind of plugin it was 😅 Thanks for the link though. I don't think we should keep a list of projects *using*/*depending on* Simple Icons. The thing about @tjtaylo's plugin is that it is basically just making Simple Icons accessible via Wordpress and nothing else, which is very similar to CDNs and NPM.

Still, thanks for letting us know you're actually using Simple Icons!

**Comment by dshanske** [comment]
I misunderstood, apologies

**Comment by ericcornelissen** [comment]
@tjtaylo, would you be willing to write something up for the README? Just a short text explaining how one can include the plugin and an example of how to use an icon, similar to the CDN and NodeJS examples.
