### ISSUE TITLE
Plurk: I think icon should be inverted?

### ISSUE THREAD

**Issue by louistsaitszho** [simple-icons/simple-icons#721]
Source: https://www.plurk.com/brandInfo

From the brand info page, it seems that the icon should be inverted

Part of #616

**Comment by davidklebanoff** [comment]
A good eye, at first it does look like it might be inverted. I do however disagree. When looking at the icon we have on the Simple Icons homepage you have to remember that the white parts are the icon itself and the orange-red color is just the brand color. I could see why it might look wrong at first, because it might initially appears that the filled in components are inverted. But, it's just the colors happen to be inverted in that particular situation.

It's easier to see that the icon is correct by viewing just the SVG file itself:
https://github.com/simple-icons/simple-icons/blob/develop/icons/plurk.svg
