### ISSUE TITLE
Sheweny Icon

### ISSUE THREAD

**Issue by VinceTheGenius** [simple-icons/simple-icons#7363]
### Brand Name

Sheweny

### Website

https://sheweny.js.org/

### Popularity Metric

There is the github of the project : https://github.com/sheweny

### Official Resources for Icon and Color

svg : https://github.com/VinceTheGenius/sheweny-logo/blob/main/sheweny.svg
You can find also png format in this repo

### Additional Comments

No but huge thanks for your work :)

### Contributing

Yes

**Comment by sisp** [comment]
Unfortunately, this brand does not meet any of the [popularity criteria](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon): GitHub stars are significantly below 5k and the website has no Similarweb rank because of too few visits. Unless you can make a strong argument why it should be considered sufficiently popular nevertheless, I'm afraid it doesn't qualify for being added.

**Comment by VinceTheGenius** [comment]
Ok, I'll send a response soon,
thanks ! :)

**Comment by adamrusted** [comment]
Unfortunately this does not meet our inclusion criteria. I'll shut this issue for now, but please feel free to reopen should it meet the minimum of a <500k SimilarWeb rank, or >5k GitHub stars.
