### ISSUE TITLE
Simple Icons for ReactJS? 

### ISSUE THREAD

**Issue by Bsmoder** [simple-icons/simple-icons#742]
Has anyone thought about creating a reactJS library for simple icons, icons are amazing. 

If not we could probably create a library...

**Comment by birjolaxew** [comment]
[One does exist](https://www.npmjs.com/package/react-simple-icons), but is horribly outdated.

Feel free to implement an up-to-date one! Note that although we generally don't include implementations in our README (see #478 and #454) your implementation will be easily found through [NPM's dependents](https://www.npmjs.com/browse/depended/simple-icons) and through [GitHub dependents](https://github.com/simple-icons/simple-icons/network/dependents) - so it definitely wouldn't be wasted work.

I am closing this for now, since it isn't really an issue with simple-icons.
