### ISSUE TITLE
Icons in PDF format

### ISSUE THREAD

**Issue by eneko** [simple-icons/simple-icons#743]
I would like to request adding support for **PDF** format. This would make these fabulous icons available for all iOS, macOS and tvOS developers using Xcode and any other application development IDEs that also support PDF icons.

From [Sketch file formats](https://www.sketchapp.com/docs/exporting/file-formats/) documentation:
> - SVG: Stands for “Scalable Vector Graphic”, a format most commonly found on the web as the image is generated in code. Code which can also be copied straight from Sketch.
> - PDF: The most common type of vector format typically associated with documents. Applications now tend to use PDF images for assets and simple icons.

Sketch and other vector image editors allow exporting assets to both SVG and PDF format.

![screenshot 2018-01-17 10 50 15](https://user-images.githubusercontent.com/32922/35060782-4261b4a8-fb74-11e7-8566-25932a3865a6.png)

In regards of Xcode:
- [Xcode 9 Vector Images](https://useyourloaf.com/blog/xcode-9-vector-images/)
- [Creating scaled images with PDF Vectors](https://useyourloaf.com/blog/creating-scaled-images-with-pdf-vectors/)

Unfortunately, Xcode, in contrast to Android Studio, does not support SVG icons directly.

**Comment by ericcornelissen** [comment]
Interesting request 🤔 definitely word considering... Perhaps we can automate the creation of the `.pdf` files using [svg-to-pdfkit](https://www.npmjs.com/package/svg-to-pdfkit) (or something similar)?

<details><summary>That being said, this seems like the perfect issue for me to propose the following (@birjolaxew @davidklebanoff).</summary>
<p>
I've been thinking about splitting the repository (as it currently is) into two/three separate repositories: one for the website, one for the icons and possibly one for the npm package (but perhaps that should be combined with the one for the icons). This PDF issue would be a third/fourth repository, so there would be `simple-icons-svg` and `simple-icons-pdf`.

My biggest concern with this change is the main website, as I'm not sure how it would get all the icons. The website main website can get the icons, both SVG and PDF, via GitHub/HTTP requests (which would require a lot of rewriting since Jekyll/Liquid no longer works) or as a git subtree (but I have no experience with that yet...).

Sorry for the tangent, perhaps it is better to put this in a separate issue 😅 
</p>
</details>

**Comment by birjolaxew** [comment]
I'm of the position that we provide the icons as SVGs. If someone would like them in a different format, whether that be PDFs, PNGs, EPSs, or something else entirely, then they are free to convert them - but the conversion is not the responsibility of the Simple Icons project.

**Comment by ericcornelissen** [comment]
Just because it isn't our responsibility doesn't mean we shouldn't do it. I agree that we shouldn't do it if it has to be done by hand, but if a PDF (or PNG, EPS or whatever) can be generated automatically from the SVG, I see no point in not supporting it. I already created a simple [bot](https://github.com/ericcornelissen/simpleicons-svg-to-pdf) for Github that automatically converts any SVG from one branch to a PDF and pushes it to another branch

**Comment by ericcornelissen** [comment]
With your permission @birjolaxew (and @davidklebanoff), I would like to pilot test [my bot](https://github.com/ericcornelissen/simpleicons-svg-to-pdf) within the simple-icons organization.

For the test period it will read commits to `develop` from this repository and push PDF versions of any SVG added/modified/removed to a different repository within the organization (e.g. a repository named `simple-icons-pdf`). So it **won't** affect this repository at all. We can then later decide how the PDF files can be incorporated into the main website.

The repository for the bot itself can also already be transferred to the simple-icons organization, but that can wait as well 😄 

I'm also interested in you're opinion on all this @eneko? And I would also like to ask you, if we go through with this, if you can provide some feedback on the generated PDF files since I have no experience using a PDF file for the purpose you described.

**Comment by davidklebanoff** [comment]
@ericcornelissen - Go for it!

**Comment by birjolaxew** [comment]
Closed with [simple-icons-pdf](https://github.com/simple-icons/simple-icons-pdf) thanks to @ericcornelissen
