### ISSUE TITLE
Request: Tapas

### ISSUE THREAD

**Issue by Josh-Powlison** [simple-icons/simple-icons#760]
[Website](https://tapas.io/)
[Icon](https://d30womf5coomej.cloudfront.net/resources/images/logo-tapas.png)

Unfortunately, this doesn't look like an easy one to do. Their logo's fairly detailed, and I haven't found a press page for an SVG.

I think it can still be done. If somebody's willing to take up the challenge, many thanks!

(I may take care of it myself later if nobody else gets on it. But if you do, many thanks!)

**Comment by birjolaxew** [comment]
They actually have some EPS' for their logo [on Google Drive](https://drive.google.com/drive/folders/0B-Fg0ydLaq8qeWlVN2VVaWZEY2s) (found [here](https://tapas.io/about#media)). It looks like they use [this little guy](https://cdn-images-1.medium.com/fit/c/200/200/1*cIlSD5SzVvewu8VzZpfAlQ.png) as their logo.

**Comment by Josh-Powlison** [comment]
@birjolaxew Great find, I completely missed that!

**Comment by Josh-Powlison** [comment]
Working on the Tapas logo now...

**Comment by Josh-Powlison** [comment]
Welp, just learned the EPS file isn't true vector, it's just a raster image inside of an EPS file. It's high enough res though that I think I can safely trace it using auto tools...

**Comment by Josh-Powlison** [comment]
[I've finished it!](https://drive.google.com/open?id=1QxvKNomlaeLqZeOvkBht11PZQYymxMmK) w00t!

@birjolaxew @davidklebanoff I'm still a relative newb to Github, do you want me to make a pull request? Do I need to ask for permission to contribute? Or do you just want me to post the code here for you?

```
{
    "title": "Tapas",
    "hex": "FFCE00",
    "source": "https://drive.google.com/drive/folders/0B-Fg0ydLaq8qeWlVN2VVaWZEY2s"
}
```

Let me know what you'd like me to do, and thanks for heading up this really helpful project!

**Comment by birjolaxew** [comment]
@Josh-Powlison You'll want to [fork](https://user-images.githubusercontent.com/4542461/36235977-d86cd352-11f3-11e8-9721-82042edf2722.png) the Simple Icons repository. This gives you a copy of the project that you can commit changes to. On your fork you'll then want to add your SVG (making sure it [fulfills our contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#3-optimize-the-icon) - you should optimize it using [SVGO](https://jakearchibald.github.io/svgomg/) and then add a few extra attributes for accessibility) and add your JSON to the data file. Finally go back to the official project (that's here) and create a new pull request. If need be, click [compare across forks](https://user-images.githubusercontent.com/4542461/36236103-8ecff1a6-11f4-11e8-8989-e22915a0214f.png) so that you can select your fork in the dropdown list. Keep "base" set to "develop", and in "compare" choose your fork (should be Josh-Powlison/simple-icons). We'll go through your changes and merge them :)

**Comment by Josh-Powlison** [comment]
@birjolaxew Thank you so much for the clear and helpful directions, I've submitted the pull request! :D I'll mark this as resolved (if I can, I don't know if I have permissions. If I can, it'll be closed :)).
