### ISSUE TITLE
Apache HBase

### ISSUE THREAD

**Issue by anmolnar** [simple-icons/simple-icons#7624]
### Brand Name

Apache HBase

### Website

https://hbase.apache.org

### Popularity Metric

4.6k stars on GitHub.
https://github.com/apache/hbase

### Official Resources for Icon and Color

This should be an easy one to add. The icon is already black&white.
PNG: **https://hbase.apache.org/images/hbase_logo_with_orca_large.png**

### Contributing

Yes

**Comment by adamrusted** [comment]
@simple-icons/maintainers - do we have another metric for measuring popularity of Apache projects? This one doesn't meet our inclusion criteria on GitHub stars alone...

**Comment by service-paradis** [comment]
There was a discussion about it without conclusion:
https://github.com/simple-icons/simple-icons/issues/4669

There is a discussion about popularity metrics in general without conclusion:
https://github.com/simple-icons/simple-icons/issues/1207

I mentioned [here](https://github.com/simple-icons/simple-icons/issues/6715#issuecomment-967168657) that Google Trends can be a good metrics when we hava comparable projects already added.

For this particular case, since Github stars are at ~4.9k, I think we can wait a little bit until it reaches our requirements. It makes me think of https://github.com/simple-icons/simple-icons/issues/5392 that reaches it between april and june in 2021.

**Comment by service-paradis** [comment]
Also, like most of the Apache projects, we can find Vector version of their logo at https://apache.org/logos.

For this particular one: https://apache.org/logos/#hbase
