### ISSUE TITLE
Change project structure

### ISSUE THREAD

**Issue by birjolaxew** [simple-icons/simple-icons#770]
I'm not entirely happy with how the folder structure is currently set up. I see a couple of different possibilities for a new structure:

1. **Keep our current structure**
    ```
    _data
      └ simple-icons.json
    icons
      ├ 500px.svg
      ├ aboutme.svg
      ├ acm.svg
      └ ...
    ```

1. **Move our JSON out of its folder**
    There's little point having a folder for a single file.

    ```
    simple-icons.json
    icons
      ├ 500px.svg
      ├ aboutme.svg
      ├ acm.svg
      └ ...
    ```

1. **Move our JSON to the `icons` folder**
    The one upside of having the JSON in its own folder is that it is kept separate from our meta files (`CONTRIBUTING.md`, `package.json`, website files, etc.). We could instead move it to the `icons` folder, so that all of the actual icon files are in the `icons` folder.

    ```
    icons
      ├ _data.json
      ├ 500px.svg
      ├ aboutme.svg
      ├ acm.svg
      └ ...
    ```

    or

    ```
    icons
      ├ data.json
      └ svgs
        ├ 500px.svg
        ├ aboutme.svg
        ├ acm.svg
        └ ...
    ```

1. **Create self-contained folder for each icon**
    Each folder would be self-contained, meaning the current structure of `_data/simple-icons.json -> icons/[name].svg` would become `icons/[name]/icon.json -> icons/[name]/icon.svg`.

    I personally think this solution adds too many files, although I do like avoiding the monolithic JSON file we have currently.

    ```
    icons
      ├ 500px
      │  ├ icon.json
      │  └ icon.svg
      ├ aboutme
      │  ├ icon.json
      │  └ icon.svg
      ├ acm
      │  ├ icon.json
      │  └ icon.svg
      └ ...
    ```

Note that our build step will convert whatever structure we choose into one tailored for use in Webpack/NodeJS before publishing to NPM, so that is not a concern.

**Comment by ericcornelissen** [comment]
I agree that a separate folder for the icon data is not necessary (I guess it was done initially for Jekyll). I personally prefer option 2. Option 3b, with a nested directory for the SVG icons, since that could help with #743 (pdf formatted icons) .

Have you also considered restructuring code related to the NPM package and code (CSS, JS, HTML) related to the website?

> Note that our build step will convert whatever structure we choose into one tailored for use in Webpack/NodeJS before publishing to NPM, so that is not a concern.

Given that, what are the possibilities in splitting the icons and website into to separate repositories where the icons repo becomes a NPM package? Apart from some possible confusion with regards to contributing I think that would be a good change following the separation of concerns principle. Some arguments in favor of doing this:
- Removes the problem of having JavaScript code for both the NPM package and website in a single 
repository
- This makes it clearer what belongs to the website and what belongs to the NPM package/icons.
- Just like option 3b, this would easily allow for PDF (and other formats) versions of the icons.

**Comment by birjolaxew** [comment]
@ericcornelissen I like that idea. Unfortunately our website needs to have access to our icons (for linking purposes), so at least our `index.html` must stay in the root folder.

```
simple-icons
  ├ data.json
  └ icons
    ├ 500px.svg
    ├ aboutme.svg
    ├ acm.svg
    └ ...
website
  ├ images
  │  ├ favicon.ico
  │  └ ...
  ├ site_script.js
  └ stylesheet.css
.gitignore
.jsonlintschema
.travis.yml
CNAME
CONTRIBUTING.md
ISSUE_TEMPLATE.md
LICENSE.md
README.md
index.html
package.json
```

With the published NPM package having a flat file structure of ([option 3 from here](https://github.com/simple-icons/simple-icons/pull/752#issuecomment-363268117)):

```
icons
  ├ 500px.svg
  ├ aboutme.svg
  ├ acm.svg
  └ ...
500px.js
aboutme.js
acm.js
...
index.js
LICENSE.md
README.md
package.json
```

The `icons` folder is there for CDN usage and to maintain backwards compatibility. The `*.js` files are there to allow easy NodeJS/Webpack usage using `const icon = require("simple-icons/500px");`

**Comment by ericcornelissen** [comment]
Alright, that seems like a good approach if we stick to a single repository 👍

* * *

What are your main objections to splitting the project up into multiple repositories like I did below?

**simple-icons/website:** (aka simpleicons.org)
```
images
  ├ favicon.ico
  └ ...
.gitignore
CNAME
CONTRIBUTING.md
ISSUE_TEMPLATE.md
LICENSE.md
README.md
index.html
package.json             (with 'simple-icons-svg' as dependency)
site_script.js
stylesheet.css
```

**simple-icons/simple-icons-svg:** (aka the NPM package)
```
icons
  ├ 500px.svg
  ├ aboutme.svg
  ├ acm.svg
  └ ...
.gitignore
.jsonlintschema
.travis.yml
CONTRIBUTING.md
index.js
ISSUE_TEMPLATE.md
LICENSE.md
package.json
README.md
simple-icons.json
```

**simple-icons/simple-icons-pdf:** (possibly given #743)
```
icons
  ├ 500px.pdf               (automatically generated based on 'simple-icons-svg')
  ├ aboutme.pdf             (automatically generated based on 'simple-icons-svg')
  ├ acm.pdf                 (automatically generated based on 'simple-icons-svg')
  └ ...
.gitignore
.jsonlintschema
.travis.yml
CONTRIBUTING.md
index.js
ISSUE_TEMPLATE.md
LICENSE.md
package.json
README.md
simple-icons.json            (automatically generated based on 'simple-icons-svg')
```

**Comment by birjolaxew** [comment]
@ericcornelissen Our website need sot include the icons, otherwise we cannot link to them for downloading. GitHub doesn't pull in dependencies when generating the website, so having our icons as dependencies doesn't do much. That's the main argument for keeping the website in the main repo.

I do like the `simple-icons-*` structure for other formats tho.

We'd also obviously have to maintain the `simple-icons` name on our main repo and NPM package for backwards compatibility, but that's just a nitpick :P 

We'd also run into #751 with how your NPM package is set up, as discussed in #752.

**Comment by ericcornelissen** [comment]
> Our website needs to include the icons, otherwise we cannot link to them for downloading. GitHub doesn't pull in dependencies when generating the website, so having our icons as dependencies doesn't do much. That's the main argument for keeping the website in the main repo.

I was confused because of your comment about publishing an NPM package through the build process. 😅 But now I get it, we can't install dependencies for the website.

And what would you say about using [git submodules](https://github.com/blog/2104-working-with-submodules) instead? In that case the website repo would get a structure like ⬇️ Even though the submodules are only pulled when the site is being build [[1]](https://help.github.com/articles/using-submodules-with-pages/), it would be possible to request a rebuild whenever we want without needing to commit anything [[2]](https://developer.github.com/v3/repos/pages/#request-a-page-build).

I'm mainly continuing with this line of thought because of #743...

```
images
  ├ favicon.ico
  └ ...
[sub] simple-icons-svg
  ├ 500px.svg
  ├ aboutme.svg
  ├ acm.svg
  └ ...
[sub] simple-icons-pdf
  ├ 500px.pdf               (automatically generated based on 'simple-icons-svg')
  ├ aboutme.pdf             (automatically generated based on 'simple-icons-svg')
  ├ acm.pdf                 (automatically generated based on 'simple-icons-svg')
  └ ...
.gitignore
CNAME
CONTRIBUTING.md
ISSUE_TEMPLATE.md
LICENSE.md
README.md
index.html
site_script.js
stylesheet.css
```


> We'd obviously have to keep the simple-icons name on our main repo and NPM package for backwards compatibility, but that's just a nitpick

Do you mean because of existing links pointing to simple-icons/simple-icons? As long as we do not start a repository named `simple-icons` after the rename we should be fine, see the GitHub [documentation](https://help.github.com/articles/renaming-a-repository/).


> We'd also run into #751 with how your NPM package is set up, as discussed in #752.

Of course we would apply the build step in that case as well 😉

**Comment by ericcornelissen** [comment]
I want to blow some new life into this issue and would like to hear some feedback from new @simple-icons/maintainers 🙂 

I want to, as I [suggested before](https://github.com/simple-icons/simple-icons/issues/770#issuecomment-366291032), split the website code and the icons code into separate repositories. Primarily as a separation of concerns and because I believe that will make it easier to advance issues like #980.

Overall, for now, my idea is as follows:

- Create a new repository **simple-icons/website** where the website code lives without the icons included. Therefore, this step will include changing the build process for the website to a NodeJS based one with the [SimpleIcons package](https://www.npmjs.com/package/simple-icons) as dependency.
- Once that is done I want to create a GitHub Action that automatically updates that repository for us, this can be achieved in one of two ways:
  - Have a trigger in **this** repository on commits to master to rebuild the website in the **that** repository.
  - Have a regularly executed action (_cron job_) in **that** repository that will rebuild the website e.g. every 2 weeks. In this case (and in any case) it would be nice if we have an action in **this** repository that automatically generates Pull Request to create release PRs.

Until this is all set and done, I suggest we leave the actual website (i.e. www.simpleicons.org) running on this repository. Before I start working on that, what do the @simple-icons/maintainers and SimpleIcons community think?

**Comment by runxel** [comment]
I think this could be a welcomed step!
This also declutters the overall structure.

I don't know if that is still an option, but I hesitate to _rename_ this very repo.
Otherwise I support the idea and think it's a sane thing to do.

**Comment by ericcornelissen** [comment]
> I don't know if that is still an option, but I hesitate to rename this very repo.
> Otherwise I support the idea and think it's a sane thing to do.

In what I have just suggested this repository would not be renamed :wink:

That said, if I'm not mistaken, when renaming a repository GitHub allows you to redirect anyone at the old URL to the new URL (but perhaps that was a BitBucket or GitLab feature 🤔)

**Comment by birjolaxew** [comment]
Can definitely agree with your plan @ericcornelissen. I think the only tricky part is getting the trigger to work, but then I don't know much about GitHub actions.

I prefer having the website in its own repo, but in case we can't find a good trigger solution I just want to throw it out there that Netlify is an excellent alternative to GitHub Pages; it essentially functions just like a CI, except the end result gets pushed out to their CDNs for serving. It lets you do pretty much whatever you want, so we could easily have the website inside its own folder or whatever structure we'd want.

**Comment by ericcornelissen** [comment]
> Can definitely agree with your plan. I think the only tricky part is getting the trigger to work, but then I don't know much about GitHub actions.

The second options should be pretty easy to implement with the [`on.schedule`](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onschedule) feature from GitHub Actions. If we could streamline this so that the following sequence of events happens:

1. A Pull Request to merge `develop` into `master` in this repository is generated automatically, using a (custom made) scheduled GitHub Action.
2. This Pull Request is merged automatically if all check pass (using something like the [automerge-action](https://github.com/pascalgn/automerge-action)).
3. The website is rebuild in **simple-icons/website** using `simple-icons@latest`

where, say, step 1 happens every other week on Sunday at 1 PM and step 3 the same day at 2 PM, then we would have a pretty nice setup (I think).

If there is a problem with the `master <- develop` PR (which I don't see happening, but lets consider anyway) the build for the website won't update anything and we can always manually trigger the rebuild later. I think this is a relatively easy to implement.

The other option could be implement using the following sequence of events:

1. A Pull Request to merge `develop` into `master` in this repository is generated automatically, using a (custom made) scheduled GitHub Action.
2. This Pull Request is merged automatically if all check pass.
3. The merge commit on `master` (or maybe something else) triggers an action that generates a Pull Request to update the simpleicons dependency in the **simple-icons/website** repository.
2. This Pull Request is merged automatically if all check pass and the website is rebuild.

This is safer, if one step fails the chain will continue automatically whenever it is resolved, but I'd imagine it's harder to implement step 3...


However, both of these assume we have step 1 😅 But this is what I would like to see this evolve into 🙂

**Comment by ericcornelissen** [comment]
Closing this issue given it's age and lack of activity. It should be noted that since this issue was created there has been some with regards to changing the project structure, most notably the extraction of the website into a separate project.

Some of the suggestions in the original issue description could still be of interest so if someone thinks we should reconsider please leave a comment!
