### ISSUE TITLE
State default SVGO settings

### ISSUE THREAD

**Issue by joshpowlison** [simple-icons/simple-icons#771]
I'd used SVGO in the past, and my changes to the settings had been changed. I had to open Firefox to get to the default settings, which are recommended in the [CONTRIBUTING.md file](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

I'd recommend we state what the default settings should be so that anyone in a similar situation gets the right icon out (there's no reset to defaults button that I'm aware of on SVGO, besides probably removing cookies).

**Comment by davidklebanoff** [comment]
Slightly related - there is an issue for adding a reset button to SVGOMG.

https://github.com/jakearchibald/svgomg/issues/101

**Comment by EvasivePangolin** [comment]
Try using SVGOMG in private browsing / incognito mode so the browser cookie that it uses to store your settings won't be there. Or just clear your cookies.

**Comment by ericcornelissen** [comment]
I don't think it is helpful to include a full list of the settings in the contributing guidelines since there are over 40 different settings that can be changed... We already specify that we want "the" default settings with a precision of 3

> Set the precision to 3, leave the remaining settings at the default values.

Ideally we can rely on a reset button on the SVGOMG website (I might pick that issue up if I find the time), for the time being we could go with the suggestion by @EvasivePangolin, and add to the contributing guidelines that a cookie reset/using incognito mode will give you the default settings. If you feel like that is a good (temporary) solution, I invite you to open a PR for it @Josh-Powlison

**Comment by Josh-Powlison** [comment]
Resetting has been tricky for me and others as well, going incognito or even for [this person](https://github.com/jakearchibald/svgomg/issues/101) resetting cookies didn't work. :/

Okay, I'll admit, I'm lazy and don't want to do it. :P But if the success of resetting based on cookies and incognito is uncertain, and most people aren't having an issue with this anyway, it's probably something to shelf for now.

**Comment by ferdnyc** [comment]
As a data point, going incognito in Linux Chrome did successfully reset the options for me, but nothing short of doing that worked. Opening a different file, closing the tab and then manually returning to the SVGOMG URL in a new tab... I'd _expect_ both of those to reset the options. (Though I suppose on "load a new file", that point is debatable and there are valid arguments to be made on both sides.)

It does seem like a reset button/link would be helpful. (Especially if all it needs to do is clear out a cookie.)

**Comment by ericcornelissen** [comment]
As of [svgomg/#142](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) you can reset the configuration from the SVGOMG website, just scroll down the settings list and you'll find a button that says "Reset all".

Closing this issue now. I will add a note about this to the [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) later 👍
