### ISSUE TITLE
SOLID WORKS

### ISSUE THREAD

**Issue by The-Kriz** [simple-icons/simple-icons#7735]
### Brand Name

SOLID WORKS

### Website

https://www.solidworks.com/

### Popularity Metric

https://www.similarweb.com/website/solidworks.com/#overview

Global Rank
#24,945

Country Rank
#18,726

Category Rank
#495

### Official Resources for Icon and Color

#e23b3b

![SolidWorks-Logo](https://user-images.githubusercontent.com/90817926/188202176-50af9d9a-08cd-47fd-a71e-183a914ec23e.png)

### Contributing

Yes

**Comment by geoyee** [comment]
@adamrusted I also want to use SolidWorks (software), may I congratulate this icon? like this ↓
![4e7f47aa6584f367fc54549b3f202a40](https://user-images.githubusercontent.com/71769312/227775653-d28a9cdc-f0e0-4174-aa84-c54c2b7e2879.jpg)

**Comment by dirien** [comment]
Hi @adamrusted, I am not sure with the proposal of @geoyee, WDYT?

**Comment by adamrusted** [comment]
Hey @dirien, the website would still suggest it's the wordmark we mentioned above. I'm unsure on the app icon, as I've never used the software myself. Up to you and the other maintainers to make a call 😅

**Comment by jwr12135** [comment]
The solidworks cube @geoyee posted is still being used as the app icon. Apart from the app icon, though, the Dassault Systèmes icon (shown in the initial post) is being used pretty much everywhere else (both on their website, and on their app interface), so that's probably what we should use. @adamrusted, does "aka"ing let you modify the color; the solidworks brand color is "red", while the Dassault Systèmes is "blue".
