### ISSUE TITLE
Request: Qwik

### ISSUE THREAD

**Issue by CKGrafico** [simple-icons/simple-icons#7922]
### Brand Name

Qwik

### Website

https://qwik.builder.io/

### Popularity Metric

https://www.similarweb.com/website/qwik.builder.io/#ranking

### Official Resources for Icon and Color

https://raw.githubusercontent.com/BuilderIO/qwik/main/.github/assets/qwik-logo.svg

### Additional Comments

Probably @mhevery can add more info

### Contributing

Yes

**Comment by mhevery** [comment]
Hello, wondering if we could help out with this pull request to help you get this merged. Anything we could do to help you?

**Comment by thecoder93** [comment]
Hi, Is there any news? I use simple icons for create badge with shields.io. At this moment I'have found a workaround 👇

![Qwik](https://img.shields.io/badge/QWIK-black.svg?logo=data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwNiIgdmlld0JveD0iMCAwIDUwMCA1MDYiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxwYXRoIGZpbGwtcnVsZT0iZXZlbm9kZCIgY2xpcC1ydWxlPSJldmVub2RkIiBkPSJNMjUwIDQ0OS43MDdMNDMxLjEwMiA1MDUuNTExTDM0My4wMzcgNDIzLjY1MkwxMjkuMTc0IDIyNC44NTlMMTc5LjE3OCAxNzQuODZMMTU2LjE1NyAxNi4xMTdMOC4zNDgyMiAxOTMuNzAyQy0yLjc4Mjk2IDIxMi45ODIgLTIuNzgyNzMgMjM2LjczNiA4LjM0ODgzIDI1Ni4wMTZMMTAyLjE5MSA0MTguNTUxQzExMy4zMjMgNDM3LjgzMSAxMzMuODk0IDQ0OS43MDcgMTU2LjE1NiA0NDkuNzA3TDI1MCA0NDkuNzA3WiIgZmlsbD0iIzE4QjZGNiIvPgo8cGF0aCBkPSJNMzQzLjg0MyAwTDE1Ni4xNTcgMS43NDA2OWUtMDVDMTMzLjg5NCAxLjk0NzE3ZS0wNSAxMTMuMzIzIDExLjg3NzEgMTAyLjE5MiAzMS4xNTczTDguMzQ4MjIgMTkzLjcwMkwxNTYuMTU3IDE2LjExN0wzNzAuODI2IDIyNC44NTlMMzMwLjgyOCAyNjQuODZMMzQzLjAzNyA0MjMuNjUyTDQzMS4xMDIgNTA1LjUxMUM0MzYuMTggNTA3LjA3NSA0NDAuNjM1IDUwMS43NTUgNDM4LjIwNCA0OTcuMDMxTDM5Ny44MDkgNDE4LjU1MUw0OTEuNjUxIDI1Ni4wMTZDNTAyLjc4MyAyMzYuNzM2IDUwMi43ODMgMjEyLjk4MiA0OTEuNjUyIDE5My43MDJMMzk3LjgwOCAzMS4xNTcyQzM4Ni42NzcgMTEuODc3MSAzNjYuMTA2IC0yLjA2NDc1ZS0wNiAzNDMuODQzIDBaIiBmaWxsPSIjQUM3RUY0Ii8+CjxwYXRoIGQ9Ik0zNzAuODI2IDIyNC44NTlMMTU2LjE1NyAxNi4xMTdMMTc5LjE3OCAxNzQuODZMMTI5LjE3NCAyMjQuODU5TDM0My4wMzcgNDIzLjY1MkwzMzAuODI4IDI2NC44NkwzNzAuODI2IDIyNC44NTlaIiBmaWxsPSJ3aGl0ZSIvPgo8L3N2Zz4=&style=flat-square)

**Comment by PeterShaggyNoble** [comment]
As the website isn't popular enough to register a ranking on Similarweb and we're in the process of reworking our metrics of popularity to put much less import on GitHib stars, is there another metric we can use to assess the popularity of this one?

**Comment by mhevery** [comment]
![image](https://github.com/simple-icons/simple-icons/assets/111951/def2bb2d-e978-4384-9cde-adc95aa7b705)
It is about as popular as SolidJS and you already have SolidJS logo

**Comment by PeterShaggyNoble** [comment]
Thanks for the data, @mhevery. That it's on an upward trend and is now on a par with SolidJS are certainly points in favour of its inclusion. On the other hand, it's only just reached that par and only because SolidJS is on a _downward_ trend, so I think we should monitor it a little further to see if it continues its upward growth. Could you share the link for the comparison above, please?

**Comment by Lissy93** [comment]
At this point, I think it would be awesome if we could re-consider Qwik's inclusion here. It's now well established, widely used and still growing.

I'd be happy to submit a PR, if you would be okay with that @PeterShaggyNoble?

----

### Justification

Qwik made it into the [2023 StackOverflow Developer survey](https://survey.stackoverflow.co/2023/#web-frameworks-and-technologies) (as the 5th most desired frontend framework)

<img src="https://github.com/simple-icons/simple-icons/assets/1862727/e07dbc50-27c6-4426-8a66-d4cc95743476" width="400" />

Qwik has also been added to the most used frontend frameworks list, number 8 on the [JS Rising Stars](https://risingstars.js.org/2023/en)

<img src="https://github.com/simple-icons/simple-icons/assets/1862727/164c674e-dd75-4486-9a50-ec37c0751ecb" width="400" />

Qwik hit V1.0 stable almost a [year ago](https://www.builder.io/blog/qwik-v1), and since then has just been rising steadily (according to [GitHub Stars](https://seladb.github.io/StarTrack-js/#/preload?r=BuilderIO,qwik) (yes, I know not the best metric)).

<a href="https://star-history.com/#BuilderIO/qwik&Date"><img src="https://api.star-history.com/svg?repos=BuilderIO/qwik&type=Date" width="400" /></a>

It's used by many projects, as illustrated by it's [NPM downloads](https://npm-stat.com/charts.html?package=%40builder.io%2Fqwik&from=2022-01-01&to=2024-01-31) are not insignificant, and again is steadily rising

<img src="https://github.com/simple-icons/simple-icons/assets/1862727/5ab3c76e-f6d7-4cf8-b53a-5c7004373268" width="400" />

Despite being a software project, and so GitHub being their main homepage,  their website's [SimilarWeb page](https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/3m?webSource=Total&key=qwik.builder.io) still recieves fairly decent traffic (250k quarterly visits). But this is still unranked (ranked 55,231 worldwide for root domain (builder.io).

<img src="https://github.com/simple-icons/simple-icons/assets/1862727/9cf621b5-0cef-466b-a650-df736b738614" width="400" />

<img src="https://github.com/simple-icons/simple-icons/assets/1862727/a6af6d9a-d24e-489b-859a-1206daaa6037" width="400" />

---

Of course, I understand that frontend frramewoks come and go pretty regularly, and it's not feasible to add them all, especially the smaller ones. But I think that at this point Qwik has been around for over a year, has considerable usage, and is still steadily rising, so ought to be reconsidered for inclusion.
