### ISSUE TITLE
Request: Generic email icon

### ISSUE THREAD

**Issue by maghoff** [simple-icons/simple-icons#837]
I cannot find a generic email icon in the iconset. It seems like there has been such an icon previously; I found #158, #116 and #3. But I cannot find the icon presently.

So, it seems that there is no problem with including an email icon, but it is not there..?

**Comment by maghoff** [comment]
I figured that might be the case, and it is fair enough. The historical issues I found did not indicate any such policy, and there is also presently a generic RSS icon included, so I thought maybe email would be acceptable. Apparently not 🙂

Thanks for your recommendations for alternatives.

**Comment by ericcornelissen** [comment]
You bring up an interesting point with regards to the RSS icon. An argument in favor of the RSS icon is that it is used for most if not all kinds of feeds, e.g. also the [Atom standard](https://en.wikipedia.org/wiki/Atom_(Web_standard)). But a similar argument could be made for email...

I don't know anything about the historical issues and older policies as I wasn't around back then, and the issues you linked/older commits don't provide sufficient information...

I'll leave this issue open for now and we'll see what comes of it 😉

**Comment by davidklebanoff** [comment]
I've put some thought into it. I feel like the RSS icon is valid because it's an official, popular standard with an official icon. It's a brand of sorts with an official brand icon.

I'm sure one could argue email could be considered a standard or an amalgam of standards, but regardless it has no official icon/logo/mark associated with it. Defining our own icon to represent email is just a slippery slope that leads us down the path to creating icons for other things as well. That goes against the goal we have here. 

So with that said, there's no official brand icon for email to place within Simple Icons and thus I don't think it belongs.

**Comment by maghoff** [comment]
You are probably aware, but I'd like to spell out the consequence: It's difficult for me to make use of simple-icons on my site, because one of the icons I'd like to use is for email. I'd _like_ to use simple-icons, but I _must_ be able to include the email link.

Of course, I respect that projects need a scope, and need to stick to it. I don't mean to fight the descision, I am merely slightly miffed that I cannot make use of this nice project :slightly_smiling_face:

**Comment by birjolaxew** [comment]
@maghoff You can still use Simple Icons; luckily webdev isn't a pick-one-or-the-other kind of deal.

Adding various other icons is problematic since it not only removes the scope of the project, but also means that we would have to design our own icons, decide on an artstyle (or include several versions of icons for different artstyles), handle disputes about different versions of an icon, so on and so forth. It's a *massive* bag of worms that nobody is interested in handling.

I would suggest [The Noun Project](https://thenounproject.com/search/?q=envelope) for your misc icon needs.

**Comment by davidklebanoff** [comment]
@maghoff - It may be useful to know that you can easily combine different icon sets into fonts or SVG sprites through various tools. One such online tool is [IcoMoon App](https://icomoon.io/app/#/select).

This has the advantage of allowing you to mix and match icon sets and to bring in only what you need to keep file sizes down. The downside of course is a little more work upfront.

**Comment by maghoff** [comment]
Thanks for the feedback. I'm sorry about my comment in https://github.com/simple-icons/simple-icons/issues/837#issuecomment-381135092 which I made because I confused this project with another one! (The other project unifies the icons a little bit)

Simple icons is fortunately well suited to use along with an email icon from a different project.
