### ISSUE TITLE
Add Fur Affinity icon

### ISSUE THREAD

**Issue by Fauxil-Fox** [simple-icons/simple-icons#853]
The best logo I could find is http://www.furaffinity.net/themes/beta/img/banners/fa_logo.png, however, there is also http://www.furaffinity.net/themes/beta/img/favicon.ico.

I don't know that an SVG exists, but staff could likely be contacted to find one.

**Comment by Fauxil-Fox** [comment]
[furaffinity.zip](https://github.com/simple-icons/simple-icons/files/2043350/furaffinity.zip)
I went ahead and made a SVG of the fa_logo.png (as it's much more recognizable than the paw favicon).

**Comment by ericcornelissen** [comment]
Fur Affinity is a though decision. On the one hand it is a niche site but on the other hand it [is ranked](https://www.alexa.com/siteinfo/furaffinity.net) pretty high (1,352 globally).

Anyone else has any thoughts on this issue?

**Comment by davidklebanoff** [comment]
I can't vouch for the quality of the community itself, but if we are going striclty by the Alexa ranking my vote is to add it. The world is filled with many niche topics and hobbies and it's hard to say what meets a "popular enough" threshold to be added without some objective measurement.

Looking a little deeper into Alexa popularity rankings, [Ruby](https://www.alexa.com/siteinfo/ruby-lang.org), for example, is only ranked 36.4k globally. However, I assume you and I are quite aware of it and are happy to add it because we know about it because of our tech-focused backgrounds. Surely the average person has no idea what Ruby is, yet here we are.

So with all that said, we probably should have some objective guidelines on what we find acceptable to add; whether it is some popularity metric or at the very least perhaps a morality statement as seen in many social media sites. You know - banning brands that may promote illegal behavior, hate speech, war, etc.

**Comment by birjolaxew** [comment]
I agree that Fur Affinity is plenty popular enough to add.

**Comment by Fauxil-Fox** [comment]
In regards to promotion of illegal behavior and the like, FA strictly forbids any hate groups, etc in their [code of conduct](http://www.furaffinity.net/coc)
