### ISSUE TITLE
`index` files are missing in v8.12.0

### ISSUE THREAD

**Issue by LitoMore** [simple-icons/simple-icons#8588]
See https://www.jsdelivr.com/package/npm/simple-icons?tab=files&version=8.12.0

We need a quick fix as soon as possible.

I wonder why this happened. I tried `npm pack` on my local, and those `index` files can be packed into it.

I also checked the `publsih.yml` script, and we have the `npm run publish` in it so those `index` files should be generated.

@mondeja I don't have the write access to publish a new patch to npm. This might need you help.

I found we have a dependencies upgrade since this PR:

- https://github.com/simple-icons/simple-icons/pull/8558

And I have created a PR to try to fix this:

- https://github.com/simple-icons/simple-icons/pull/8589

**Comment by mondeja** [comment]
Thanks @LitoMore! This has been happened because the action `JS-DevTools/npm-publish` is calling `npm` with `--ignore-scripts` in v2 (https://github.com/JS-DevTools/npm-publish/issues/47), which doesn't triggers the `prepublishOnly` script, see [v8.11.0 run](https://github.com/simple-icons/simple-icons/actions/runs/4843689276/jobs/8631483643#step:7:1) and [v8.12.0 run](https://github.com/simple-icons/simple-icons/actions/runs/4776134386/jobs/8490966255#step:7:11).

I'll publish a new patch ASAP.

**Comment by mondeja** [comment]
Patched in v8.12.1. I'm looking for a new icon to add to ensure that the next version triggers a minor bump to avoid a version collision. After that, all should be OK.
