### ISSUE TITLE
Request: Literal.club

### ISSUE THREAD

**Issue by caarlos0** [simple-icons/simple-icons#8944]
### Brand Name

Literal.Club

### Website

https://literal.club

### Popularity Metric

The similar rank is 542,693.

### Official Resources for Icon and Color

Press kit: https://literal.club/pages/press

### Contributing

No

**Comment by adamrusted** [comment]
SimilarWeb ranking would put this out of scope, I'm afraid.
Is there another popularity metric we can consider, @caarlos0?

**Comment by caarlos0** [comment]
@adamrusted no idea, the website is pretty new AFAIK, maybe that's part of it at least...

happy to close this and check again in a couple of months

**Comment by DrewMcArthur** [comment]
hi! any chance we can check again? I'm unable to use similar web, since they're trying to charge now.  (the documentation [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) is out of date, i now get a 403 from https://http://similarweb.com/website/literal.club )

they do have 50k users according to [their about page](https://literal.club/about).

**Comment by uncenter** [comment]
They are ranked 439,837 globally at the moment (https://www.similarweb.com/website/literal.club/#overview). I think this is up for consideration now?

**Comment by uncenter** [comment]
At 347,145 globally on Similarweb, Literal.club is now in scope! 🎉
