### ISSUE TITLE
BrowserStack

### ISSUE THREAD

**Issue by mrinc** [simple-icons/simple-icons#9084]
### Brand Name

BrowserStack

### Website

https://www.browserstack.com/

### Popularity Metric

https://www.similarweb.com/website/browserstack.com/  
Global Rank: `24468`  
Category Rank: `223`

### Official Resources for Icon and Color

I cannot find a specific media kit or brand guidelines from BrowserStack directly, but: https://brandfetch.com/browserstack.com seems to have some decent info

### Contributing

No

**Comment by adamrusted** [comment]
Bear in mind this icon has already been declined multiple times (see https://github.com/simple-icons/simple-icons/issues/4668#issuecomment-758604375) due to it not converting to monochrome nicely. If there is an official monochrome treatment, then we can proceed with this - otherwise we'll have to close this issue out.

**Comment by service-paradis** [comment]
Closing for now since it is now 2 weeks without any reply.
