### ISSUE TITLE
Request: PixelFed

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [simple-icons/simple-icons#967]
https://pix.diaspodon.fr/img/pixelfed-icon-color.svg

![logo](https://pix.diaspodon.fr/img/pixelfed-icon-color.svg)

**Comment by birjolaxew** [comment]
The Alexa rank is [~2.4 million](https://www.alexa.com/siteinfo/pixelfed.org), which is a fair bit beyond [our scope of <500k](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) - probably related to the fact that the product hasn't actually launched yet.

We'd love to add it when it gains some traction, but for now I'll close this.

**Comment by Hugo-Trentesaux** [comment]
One year later, the Alexa rank of pixelfed is 789k.

**Comment by Hugo-Trentesaux** [comment]
Now, it's 614,869 and it had a maximum at 588,834 :smile: but it is on fork-awesome

**Comment by PeterShaggyNoble** [comment]
Thanks for the update, @Hugo-Trentesaux, and for staying on top of this. Personally, though, I'd like to see it spend more than a few days under the 500k mark before we revisit it.

**Comment by Hugo-Trentesaux** [comment]
Pixelfed's Alexa rank is now around 348,017 for a while.

**Comment by Hugo-Trentesaux** [comment]
Here is a list of pixelfed issues:

- #967 by @Hugo-Trentesaux 
- #7269 by @MediaActivist
- #8406 by @ghost
- #8999 by @abbluiz
- #9001 by @Alxira5

**Comment by PeterShaggyNoble** [comment]
With [a rank of 1.8m](https://www.similarweb.com/website/pixelfed.org), this is now _well_ outside our scope, @Hugo-Trentesaux.

If you have another metric we can use to assess its popularity then please do provide it and we'll revisit this issue. See #9979 for some proposed alternative metrics.

**Comment by Hugo-Trentesaux** [comment]
Haha it was only a list, not a request to reevaluate the issue :wink:

**Comment by openforfuture** [comment]
**PixeldFed** is by its nature _decentralised_, like other [Fediverse](https://en.wikipedia.org/wiki/Fediverse) platforms and the ranking of the developer website tells very little about its relevance since people don't have to pass through it to use the software. It is moreover contrary to the very spirit of the open world and the nature of the Fediverse to use an indicator created by a Big Tech.

PixelFed is the main (and maybe only) decentralised/open alternative to Instagram and its in the top 10 federated platform by popularity:
<img width="535" alt="image" src="https://github.com/simple-icons/simple-icons/assets/99279367/aeebf0c8-adb7-4ad6-a656-263bbbcd3b75">

To evaluate a federated platform popularity it's better to use:
https://fedidb.org/network
https://the-federation.info/#projects

**Comment by openforfuture** [comment]
> @openforfuture, could you open a new issue to suggest & discuss metrics of popularity for decentralised projects, please?

done! 😎

**Comment by openforfuture** [comment]
Shouldn't this issue be reopened now?

**Comment by adamrusted** [comment]
It certainly can be. Generally if we've closed an issue we wait for someone else to repost it as opposed to trawling through all closed issues when the guidelines change.
