### ISSUE TITLE
Request: ComicFury

### ISSUE THREAD

**Issue by tootaloo** [simple-icons/simple-icons#9998]
### Brand Name

ComicFury

### Website

https://comicfury.com

### Popularity Metric

ComicFury has a ranking of 78,429 on https://www.similarweb.com/website/comicfury.com/#overview

### Official Resources for Icon and Color

https://comicfury.com/images/gator-icon-black.png
https://comicfury.com/images/cf-diamond.png

### Additional Comments

There are two versions of the new logo. They both feature the website's mascot, the gator. The website itself seems to host different artist contributed interpretations of the mascot but the black and white geometric design appears to be the official logo.

**Comment by PratyushJayachandran** [comment]
What is the source/proof for which one is the original logo?

**Comment by PeterShaggyNoble** [comment]
Taking a step back on this for a second, I would have concerns about adding this one based on some of the points raised in https://github.com/simple-icons/simple-icons/issues/5438#issuecomment-818674444. Although ComicFury claim that restricted & adult content is only available to registered members over 18, it is in fact _easily_ accessible directly from their homepage by following a link to a comic and dismissing the content warning.

**Comment by PeterShaggyNoble** [comment]
My concern was with accessibility rather than availability, @tootaloo, but, rereading the comment I linked above, I realise the relevant concern I had there was with _visibility_ - can a maintainer or contributor research the requested brand without being exposed to adult content? In this case, the answer to that question is: yes, they can. Although presented on the homepage making it more easily accessible, you still have to actually _engage_ with the site in order to view any adult content, same as you have to actively search for it on the likes of DeviantArt & OnlyFans. So, unless any of the other @simple-icons/maintainers have any objections, I think we can allow this one.
